// Code generated by qtc from "index.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line namespace/template/index.qtpl:2
package template

//line namespace/template/index.qtpl:2
import (
	"github.com/andrewpillar/thrall/build"
	"github.com/andrewpillar/thrall/model"
	"github.com/andrewpillar/thrall/namespace"
	"github.com/andrewpillar/thrall/template"
)

//line namespace/template/index.qtpl:10
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line namespace/template/index.qtpl:10
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line namespace/template/index.qtpl:11
type Index struct {
	template.BasePage

	Paginator  model.Paginator
	Namespace  *namespace.Namespace
	Namespaces []*namespace.Namespace
	Search     string
}

type InviteIndex struct {
	template.BasePage

	CSRF    string
	Invites []*namespace.Invite
}

//line namespace/template/index.qtpl:29
func (p *Index) StreamTitle(qw422016 *qt422016.Writer) {
//line namespace/template/index.qtpl:29
	qw422016.N().S(` Namespaces - Thrall `)
//line namespace/template/index.qtpl:31
}

//line namespace/template/index.qtpl:31
func (p *Index) WriteTitle(qq422016 qtio422016.Writer) {
//line namespace/template/index.qtpl:31
	qw422016 := qt422016.AcquireWriter(qq422016)
//line namespace/template/index.qtpl:31
	p.StreamTitle(qw422016)
//line namespace/template/index.qtpl:31
	qt422016.ReleaseWriter(qw422016)
//line namespace/template/index.qtpl:31
}

//line namespace/template/index.qtpl:31
func (p *Index) Title() string {
//line namespace/template/index.qtpl:31
	qb422016 := qt422016.AcquireByteBuffer()
//line namespace/template/index.qtpl:31
	p.WriteTitle(qb422016)
//line namespace/template/index.qtpl:31
	qs422016 := string(qb422016.B)
//line namespace/template/index.qtpl:31
	qt422016.ReleaseByteBuffer(qb422016)
//line namespace/template/index.qtpl:31
	return qs422016
//line namespace/template/index.qtpl:31
}

//line namespace/template/index.qtpl:33
func (p *Index) StreamBody(qw422016 *qt422016.Writer) {
//line namespace/template/index.qtpl:33
	qw422016.N().S(` <div class="panel"> `)
//line namespace/template/index.qtpl:35
	if len(p.Namespaces) == 0 && p.Search == "" {
//line namespace/template/index.qtpl:35
		qw422016.N().S(` <div class="panel-message muted">Namespaces allow you to group related build resources together.</div> `)
//line namespace/template/index.qtpl:37
	} else {
//line namespace/template/index.qtpl:37
		qw422016.N().S(` <div class="panel-header">`)
//line namespace/template/index.qtpl:38
		template.StreamRenderSearch(qw422016, p.URL.Path, p.Search, "Find a namespace...")
//line namespace/template/index.qtpl:38
		qw422016.N().S(`</div> `)
//line namespace/template/index.qtpl:39
		if len(p.Namespaces) == 0 && p.Search != "" {
//line namespace/template/index.qtpl:39
			qw422016.N().S(` <div class="panel-message muted">No results found.</div> `)
//line namespace/template/index.qtpl:41
		} else {
//line namespace/template/index.qtpl:41
			qw422016.N().S(` <table class="table"> <thead> <tr> <th>NAME</th> <th>LAST BUILD</th> <th></th> <th></th> </tr> </thead> <tbody> `)
//line namespace/template/index.qtpl:52
			for _, n := range p.Namespaces {
//line namespace/template/index.qtpl:52
				qw422016.N().S(` `)
//line namespace/template/index.qtpl:53
				b, _ := n.Build.(*build.Build)

//line namespace/template/index.qtpl:53
				qw422016.N().S(` <tr> <td> <a href="`)
//line namespace/template/index.qtpl:56
				qw422016.E().S(n.Endpoint())
//line namespace/template/index.qtpl:56
				qw422016.N().S(`">`)
//line namespace/template/index.qtpl:56
				qw422016.E().S(n.Path)
//line namespace/template/index.qtpl:56
				qw422016.N().S(`</a> <div class="muted"> `)
//line namespace/template/index.qtpl:58
				if n.Description == "" {
//line namespace/template/index.qtpl:58
					qw422016.N().S(` <em>No description</em> `)
//line namespace/template/index.qtpl:60
				} else {
//line namespace/template/index.qtpl:60
					qw422016.N().S(` `)
//line namespace/template/index.qtpl:61
					qw422016.E().S(n.Description)
//line namespace/template/index.qtpl:61
					qw422016.N().S(` `)
//line namespace/template/index.qtpl:62
				}
//line namespace/template/index.qtpl:62
				qw422016.N().S(` </div> </td> <td class="muted"> `)
//line namespace/template/index.qtpl:66
				if n.Build != nil {
//line namespace/template/index.qtpl:66
					qw422016.N().S(` <a href="`)
//line namespace/template/index.qtpl:67
					qw422016.E().S(n.Build.Endpoint())
//line namespace/template/index.qtpl:67
					qw422016.N().S(`"> #`)
//line namespace/template/index.qtpl:68
					qw422016.E().V(b.ID)
//line namespace/template/index.qtpl:68
					qw422016.N().S(` `)
//line namespace/template/index.qtpl:68
					qw422016.E().S(b.Trigger.CommentTitle())
//line namespace/template/index.qtpl:68
					qw422016.N().S(` </a> `)
//line namespace/template/index.qtpl:70
				} else {
//line namespace/template/index.qtpl:70
					qw422016.N().S(` -- `)
//line namespace/template/index.qtpl:72
				}
//line namespace/template/index.qtpl:72
				qw422016.N().S(` </td> <td> `)
//line namespace/template/index.qtpl:75
				if b != nil {
//line namespace/template/index.qtpl:75
					qw422016.N().S(` `)
//line namespace/template/index.qtpl:76
					template.StreamRenderStatus(qw422016, b.Status)
//line namespace/template/index.qtpl:76
					qw422016.N().S(` `)
//line namespace/template/index.qtpl:77
				}
//line namespace/template/index.qtpl:77
				qw422016.N().S(` </td> <td class="align-right muted"> `)
//line namespace/template/index.qtpl:80
				if p.User.ID != n.UserID {
//line namespace/template/index.qtpl:80
					qw422016.N().S(` `)
//line namespace/template/index.qtpl:81
					qw422016.N().S(`<!-- Generated by IcoMoon.io -->
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
<path d="M15.984 12.984c2.344 0 7.031 1.172 7.031 3.516v2.484h-6v-2.484c0-1.5-0.797-2.625-1.969-3.469 0.328-0.047 0.656-0.047 0.938-0.047zM8.016 12.984c2.344 0 6.984 1.172 6.984 3.516v2.484h-14.016v-2.484c0-2.344 4.688-3.516 7.031-3.516zM8.016 11.016c-1.641 0-3-1.359-3-3s1.359-3 3-3 2.953 1.359 2.953 3-1.313 3-2.953 3zM15.984 11.016c-1.641 0-3-1.359-3-3s1.359-3 3-3 3 1.359 3 3-1.359 3-3 3z"></path>
</svg>
`)
//line namespace/template/index.qtpl:81
					qw422016.N().S(` `)
//line namespace/template/index.qtpl:82
				}
//line namespace/template/index.qtpl:82
				qw422016.N().S(` `)
//line namespace/template/index.qtpl:83
				switch n.Visibility {
//line namespace/template/index.qtpl:84
				case namespace.Private:
//line namespace/template/index.qtpl:84
					qw422016.N().S(` `)
//line namespace/template/index.qtpl:85
					qw422016.N().S(`<!-- Generated by IcoMoon.io -->
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
<path d="M15.094 8.016v-2.016c0-1.688-1.406-3.094-3.094-3.094s-3.094 1.406-3.094 3.094v2.016h6.188zM12 17.016c1.078 0 2.016-0.938 2.016-2.016s-0.938-2.016-2.016-2.016-2.016 0.938-2.016 2.016 0.938 2.016 2.016 2.016zM18 8.016c1.078 0 2.016 0.891 2.016 1.969v10.031c0 1.078-0.938 1.969-2.016 1.969h-12c-1.078 0-2.016-0.891-2.016-1.969v-10.031c0-1.078 0.938-1.969 2.016-1.969h0.984v-2.016c0-2.766 2.25-5.016 5.016-5.016s5.016 2.25 5.016 5.016v2.016h0.984z"></path>
</svg>
`)
//line namespace/template/index.qtpl:85
					qw422016.N().S(` `)
//line namespace/template/index.qtpl:86
				case namespace.Internal:
//line namespace/template/index.qtpl:86
					qw422016.N().S(` `)
//line namespace/template/index.qtpl:87
					qw422016.N().S(`<!-- Generated by IcoMoon.io -->
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
<path d="M12 0.984l9 4.031v6c0 5.531-3.844 10.734-9 12-5.156-1.266-9-6.469-9-12v-6zM12 12v8.953c3.703-1.172 6.469-4.828 6.984-8.953h-6.984zM12 12v-8.813l-6.984 3.094v5.719h6.984z"></path>
</svg>
`)
//line namespace/template/index.qtpl:87
					qw422016.N().S(` `)
//line namespace/template/index.qtpl:88
				case namespace.Public:
//line namespace/template/index.qtpl:88
					qw422016.N().S(` `)
//line namespace/template/index.qtpl:89
					qw422016.N().S(`<!-- Generated by IcoMoon.io -->
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
<path d="M17.906 17.391c1.313-1.406 2.109-3.328 2.109-5.391 0-3.328-2.063-6.234-5.016-7.406v0.422c0 1.078-0.938 1.969-2.016 1.969h-1.969v2.016c0 0.563-0.469 0.984-1.031 0.984h-1.969v2.016h6c0.563 0 0.984 0.422 0.984 0.984v3h0.984c0.891 0 1.641 0.609 1.922 1.406zM11.016 19.922v-1.922c-1.078 0-2.016-0.938-2.016-2.016v-0.984l-4.781-4.781c-0.141 0.563-0.234 1.172-0.234 1.781 0 4.078 3.094 7.453 7.031 7.922zM12 2.016c5.531 0 9.984 4.453 9.984 9.984s-4.453 9.984-9.984 9.984-9.984-4.453-9.984-9.984 4.453-9.984 9.984-9.984z"></path>
</svg>
`)
//line namespace/template/index.qtpl:89
					qw422016.N().S(` `)
//line namespace/template/index.qtpl:90
				}
//line namespace/template/index.qtpl:90
				qw422016.N().S(` </td> </tr> `)
//line namespace/template/index.qtpl:93
			}
//line namespace/template/index.qtpl:93
			qw422016.N().S(` </tbody> </table> `)
//line namespace/template/index.qtpl:96
		}
//line namespace/template/index.qtpl:96
		qw422016.N().S(` `)
//line namespace/template/index.qtpl:97
	}
//line namespace/template/index.qtpl:97
	qw422016.N().S(` </div> `)
//line namespace/template/index.qtpl:99
	template.StreamRenderPaginator(qw422016, p.URL.Path, p.Paginator)
//line namespace/template/index.qtpl:99
	qw422016.N().S(` `)
//line namespace/template/index.qtpl:100
}

//line namespace/template/index.qtpl:100
func (p *Index) WriteBody(qq422016 qtio422016.Writer) {
//line namespace/template/index.qtpl:100
	qw422016 := qt422016.AcquireWriter(qq422016)
//line namespace/template/index.qtpl:100
	p.StreamBody(qw422016)
//line namespace/template/index.qtpl:100
	qt422016.ReleaseWriter(qw422016)
//line namespace/template/index.qtpl:100
}

//line namespace/template/index.qtpl:100
func (p *Index) Body() string {
//line namespace/template/index.qtpl:100
	qb422016 := qt422016.AcquireByteBuffer()
//line namespace/template/index.qtpl:100
	p.WriteBody(qb422016)
//line namespace/template/index.qtpl:100
	qs422016 := string(qb422016.B)
//line namespace/template/index.qtpl:100
	qt422016.ReleaseByteBuffer(qb422016)
//line namespace/template/index.qtpl:100
	return qs422016
//line namespace/template/index.qtpl:100
}

//line namespace/template/index.qtpl:102
func (p *Index) StreamSection(qw422016 *qt422016.Writer) {
//line namespace/template/index.qtpl:102
	qw422016.N().S(` `)
//line namespace/template/index.qtpl:103
	p.StreamBody(qw422016)
//line namespace/template/index.qtpl:103
	qw422016.N().S(` `)
//line namespace/template/index.qtpl:104
}

//line namespace/template/index.qtpl:104
func (p *Index) WriteSection(qq422016 qtio422016.Writer) {
//line namespace/template/index.qtpl:104
	qw422016 := qt422016.AcquireWriter(qq422016)
//line namespace/template/index.qtpl:104
	p.StreamSection(qw422016)
//line namespace/template/index.qtpl:104
	qt422016.ReleaseWriter(qw422016)
//line namespace/template/index.qtpl:104
}

//line namespace/template/index.qtpl:104
func (p *Index) Section() string {
//line namespace/template/index.qtpl:104
	qb422016 := qt422016.AcquireByteBuffer()
//line namespace/template/index.qtpl:104
	p.WriteSection(qb422016)
//line namespace/template/index.qtpl:104
	qs422016 := string(qb422016.B)
//line namespace/template/index.qtpl:104
	qt422016.ReleaseByteBuffer(qb422016)
//line namespace/template/index.qtpl:104
	return qs422016
//line namespace/template/index.qtpl:104
}

//line namespace/template/index.qtpl:106
func (p *Index) StreamHeader(qw422016 *qt422016.Writer) {
//line namespace/template/index.qtpl:106
	qw422016.N().S(` Namespaces `)
//line namespace/template/index.qtpl:108
}

//line namespace/template/index.qtpl:108
func (p *Index) WriteHeader(qq422016 qtio422016.Writer) {
//line namespace/template/index.qtpl:108
	qw422016 := qt422016.AcquireWriter(qq422016)
//line namespace/template/index.qtpl:108
	p.StreamHeader(qw422016)
//line namespace/template/index.qtpl:108
	qt422016.ReleaseWriter(qw422016)
//line namespace/template/index.qtpl:108
}

//line namespace/template/index.qtpl:108
func (p *Index) Header() string {
//line namespace/template/index.qtpl:108
	qb422016 := qt422016.AcquireByteBuffer()
//line namespace/template/index.qtpl:108
	p.WriteHeader(qb422016)
//line namespace/template/index.qtpl:108
	qs422016 := string(qb422016.B)
//line namespace/template/index.qtpl:108
	qt422016.ReleaseByteBuffer(qb422016)
//line namespace/template/index.qtpl:108
	return qs422016
//line namespace/template/index.qtpl:108
}

//line namespace/template/index.qtpl:110
func (p *Index) StreamActions(qw422016 *qt422016.Writer) {
//line namespace/template/index.qtpl:110
	qw422016.N().S(` `)
//line namespace/template/index.qtpl:111
	if _, ok := p.User.Permissions["namespace:write"]; ok {
//line namespace/template/index.qtpl:111
		qw422016.N().S(` <li><a href="/namespaces/create" class="btn btn-primary">Create</a></li> `)
//line namespace/template/index.qtpl:113
	}
//line namespace/template/index.qtpl:113
	qw422016.N().S(` `)
//line namespace/template/index.qtpl:114
}

//line namespace/template/index.qtpl:114
func (p *Index) WriteActions(qq422016 qtio422016.Writer) {
//line namespace/template/index.qtpl:114
	qw422016 := qt422016.AcquireWriter(qq422016)
//line namespace/template/index.qtpl:114
	p.StreamActions(qw422016)
//line namespace/template/index.qtpl:114
	qt422016.ReleaseWriter(qw422016)
//line namespace/template/index.qtpl:114
}

//line namespace/template/index.qtpl:114
func (p *Index) Actions() string {
//line namespace/template/index.qtpl:114
	qb422016 := qt422016.AcquireByteBuffer()
//line namespace/template/index.qtpl:114
	p.WriteActions(qb422016)
//line namespace/template/index.qtpl:114
	qs422016 := string(qb422016.B)
//line namespace/template/index.qtpl:114
	qt422016.ReleaseByteBuffer(qb422016)
//line namespace/template/index.qtpl:114
	return qs422016
//line namespace/template/index.qtpl:114
}

//line namespace/template/index.qtpl:116
func (p *Index) StreamNavigation(qw422016 *qt422016.Writer) {
//line namespace/template/index.qtpl:116
}

//line namespace/template/index.qtpl:116
func (p *Index) WriteNavigation(qq422016 qtio422016.Writer) {
//line namespace/template/index.qtpl:116
	qw422016 := qt422016.AcquireWriter(qq422016)
//line namespace/template/index.qtpl:116
	p.StreamNavigation(qw422016)
//line namespace/template/index.qtpl:116
	qt422016.ReleaseWriter(qw422016)
//line namespace/template/index.qtpl:116
}

//line namespace/template/index.qtpl:116
func (p *Index) Navigation() string {
//line namespace/template/index.qtpl:116
	qb422016 := qt422016.AcquireByteBuffer()
//line namespace/template/index.qtpl:116
	p.WriteNavigation(qb422016)
//line namespace/template/index.qtpl:116
	qs422016 := string(qb422016.B)
//line namespace/template/index.qtpl:116
	qt422016.ReleaseByteBuffer(qb422016)
//line namespace/template/index.qtpl:116
	return qs422016
//line namespace/template/index.qtpl:116
}

//line namespace/template/index.qtpl:118
func (p *InviteIndex) StreamTitle(qw422016 *qt422016.Writer) {
//line namespace/template/index.qtpl:118
	qw422016.N().S(` Namespace Invites `)
//line namespace/template/index.qtpl:120
}

//line namespace/template/index.qtpl:120
func (p *InviteIndex) WriteTitle(qq422016 qtio422016.Writer) {
//line namespace/template/index.qtpl:120
	qw422016 := qt422016.AcquireWriter(qq422016)
//line namespace/template/index.qtpl:120
	p.StreamTitle(qw422016)
//line namespace/template/index.qtpl:120
	qt422016.ReleaseWriter(qw422016)
//line namespace/template/index.qtpl:120
}

//line namespace/template/index.qtpl:120
func (p *InviteIndex) Title() string {
//line namespace/template/index.qtpl:120
	qb422016 := qt422016.AcquireByteBuffer()
//line namespace/template/index.qtpl:120
	p.WriteTitle(qb422016)
//line namespace/template/index.qtpl:120
	qs422016 := string(qb422016.B)
//line namespace/template/index.qtpl:120
	qt422016.ReleaseByteBuffer(qb422016)
//line namespace/template/index.qtpl:120
	return qs422016
//line namespace/template/index.qtpl:120
}

//line namespace/template/index.qtpl:122
func (p *InviteIndex) StreamSection(qw422016 *qt422016.Writer) {
//line namespace/template/index.qtpl:122
	qw422016.N().S(` `)
//line namespace/template/index.qtpl:124
}

//line namespace/template/index.qtpl:124
func (p *InviteIndex) WriteSection(qq422016 qtio422016.Writer) {
//line namespace/template/index.qtpl:124
	qw422016 := qt422016.AcquireWriter(qq422016)
//line namespace/template/index.qtpl:124
	p.StreamSection(qw422016)
//line namespace/template/index.qtpl:124
	qt422016.ReleaseWriter(qw422016)
//line namespace/template/index.qtpl:124
}

//line namespace/template/index.qtpl:124
func (p *InviteIndex) Section() string {
//line namespace/template/index.qtpl:124
	qb422016 := qt422016.AcquireByteBuffer()
//line namespace/template/index.qtpl:124
	p.WriteSection(qb422016)
//line namespace/template/index.qtpl:124
	qs422016 := string(qb422016.B)
//line namespace/template/index.qtpl:124
	qt422016.ReleaseByteBuffer(qb422016)
//line namespace/template/index.qtpl:124
	return qs422016
//line namespace/template/index.qtpl:124
}
