// Code generated by qtc from "app_index.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line template/app_index.qtpl:1
package template

//line template/app_index.qtpl:1
import "djinn-ci.com/oauth2"

//line template/app_index.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line template/app_index.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line template/app_index.qtpl:4
type AppIndex struct {
	*Page

	Apps []*oauth2.App
}

//line template/app_index.qtpl:12
func (p *AppIndex) StreamTitle(qw422016 *qt422016.Writer) {
//line template/app_index.qtpl:12
	qw422016.N().S(`OAuth Apps`)
//line template/app_index.qtpl:12
}

//line template/app_index.qtpl:12
func (p *AppIndex) WriteTitle(qq422016 qtio422016.Writer) {
//line template/app_index.qtpl:12
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template/app_index.qtpl:12
	p.StreamTitle(qw422016)
//line template/app_index.qtpl:12
	qt422016.ReleaseWriter(qw422016)
//line template/app_index.qtpl:12
}

//line template/app_index.qtpl:12
func (p *AppIndex) Title() string {
//line template/app_index.qtpl:12
	qb422016 := qt422016.AcquireByteBuffer()
//line template/app_index.qtpl:12
	p.WriteTitle(qb422016)
//line template/app_index.qtpl:12
	qs422016 := string(qb422016.B)
//line template/app_index.qtpl:12
	qt422016.ReleaseByteBuffer(qb422016)
//line template/app_index.qtpl:12
	return qs422016
//line template/app_index.qtpl:12
}

//line template/app_index.qtpl:14
func (p *AppIndex) StreamHeader(qw422016 *qt422016.Writer) {
//line template/app_index.qtpl:14
	p.StreamTitle(qw422016)
//line template/app_index.qtpl:14
}

//line template/app_index.qtpl:14
func (p *AppIndex) WriteHeader(qq422016 qtio422016.Writer) {
//line template/app_index.qtpl:14
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template/app_index.qtpl:14
	p.StreamHeader(qw422016)
//line template/app_index.qtpl:14
	qt422016.ReleaseWriter(qw422016)
//line template/app_index.qtpl:14
}

//line template/app_index.qtpl:14
func (p *AppIndex) Header() string {
//line template/app_index.qtpl:14
	qb422016 := qt422016.AcquireByteBuffer()
//line template/app_index.qtpl:14
	p.WriteHeader(qb422016)
//line template/app_index.qtpl:14
	qs422016 := string(qb422016.B)
//line template/app_index.qtpl:14
	qt422016.ReleaseByteBuffer(qb422016)
//line template/app_index.qtpl:14
	return qs422016
//line template/app_index.qtpl:14
}

//line template/app_index.qtpl:16
func (p *AppIndex) StreamActions(qw422016 *qt422016.Writer) {
//line template/app_index.qtpl:16
	qw422016.N().S(` <li><a href="/settings/apps/create" class="btn btn-primary">Create</a></li> `)
//line template/app_index.qtpl:18
}

//line template/app_index.qtpl:18
func (p *AppIndex) WriteActions(qq422016 qtio422016.Writer) {
//line template/app_index.qtpl:18
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template/app_index.qtpl:18
	p.StreamActions(qw422016)
//line template/app_index.qtpl:18
	qt422016.ReleaseWriter(qw422016)
//line template/app_index.qtpl:18
}

//line template/app_index.qtpl:18
func (p *AppIndex) Actions() string {
//line template/app_index.qtpl:18
	qb422016 := qt422016.AcquireByteBuffer()
//line template/app_index.qtpl:18
	p.WriteActions(qb422016)
//line template/app_index.qtpl:18
	qs422016 := string(qb422016.B)
//line template/app_index.qtpl:18
	qt422016.ReleaseByteBuffer(qb422016)
//line template/app_index.qtpl:18
	return qs422016
//line template/app_index.qtpl:18
}

//line template/app_index.qtpl:20
func (p *AppIndex) StreamNavigation(qw422016 *qt422016.Writer) {
//line template/app_index.qtpl:20
}

//line template/app_index.qtpl:20
func (p *AppIndex) WriteNavigation(qq422016 qtio422016.Writer) {
//line template/app_index.qtpl:20
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template/app_index.qtpl:20
	p.StreamNavigation(qw422016)
//line template/app_index.qtpl:20
	qt422016.ReleaseWriter(qw422016)
//line template/app_index.qtpl:20
}

//line template/app_index.qtpl:20
func (p *AppIndex) Navigation() string {
//line template/app_index.qtpl:20
	qb422016 := qt422016.AcquireByteBuffer()
//line template/app_index.qtpl:20
	p.WriteNavigation(qb422016)
//line template/app_index.qtpl:20
	qs422016 := string(qb422016.B)
//line template/app_index.qtpl:20
	qt422016.ReleaseByteBuffer(qb422016)
//line template/app_index.qtpl:20
	return qs422016
//line template/app_index.qtpl:20
}

//line template/app_index.qtpl:21
func (p *AppIndex) StreamFooter(qw422016 *qt422016.Writer) {
//line template/app_index.qtpl:21
}

//line template/app_index.qtpl:21
func (p *AppIndex) WriteFooter(qq422016 qtio422016.Writer) {
//line template/app_index.qtpl:21
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template/app_index.qtpl:21
	p.StreamFooter(qw422016)
//line template/app_index.qtpl:21
	qt422016.ReleaseWriter(qw422016)
//line template/app_index.qtpl:21
}

//line template/app_index.qtpl:21
func (p *AppIndex) Footer() string {
//line template/app_index.qtpl:21
	qb422016 := qt422016.AcquireByteBuffer()
//line template/app_index.qtpl:21
	p.WriteFooter(qb422016)
//line template/app_index.qtpl:21
	qs422016 := string(qb422016.B)
//line template/app_index.qtpl:21
	qt422016.ReleaseByteBuffer(qb422016)
//line template/app_index.qtpl:21
	return qs422016
//line template/app_index.qtpl:21
}

//line template/app_index.qtpl:23
func (p *AppIndex) streamrenderAppItem(qw422016 *qt422016.Writer, a *oauth2.App) {
//line template/app_index.qtpl:23
	qw422016.N().S(` <tr> <td> <a href="`)
//line template/app_index.qtpl:26
	qw422016.E().S(a.Endpoint())
//line template/app_index.qtpl:26
	qw422016.N().S(`">`)
//line template/app_index.qtpl:26
	qw422016.E().S(a.Name)
//line template/app_index.qtpl:26
	qw422016.N().S(`</a> `)
//line template/app_index.qtpl:27
	if a.Description != "" {
//line template/app_index.qtpl:27
		qw422016.N().S(` <br/><span class="muted">`)
//line template/app_index.qtpl:28
		qw422016.E().S(a.Description)
//line template/app_index.qtpl:28
		qw422016.N().S(`</span> `)
//line template/app_index.qtpl:29
	}
//line template/app_index.qtpl:29
	qw422016.N().S(` </td> </tr> `)
//line template/app_index.qtpl:32
}

//line template/app_index.qtpl:32
func (p *AppIndex) writerenderAppItem(qq422016 qtio422016.Writer, a *oauth2.App) {
//line template/app_index.qtpl:32
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template/app_index.qtpl:32
	p.streamrenderAppItem(qw422016, a)
//line template/app_index.qtpl:32
	qt422016.ReleaseWriter(qw422016)
//line template/app_index.qtpl:32
}

//line template/app_index.qtpl:32
func (p *AppIndex) renderAppItem(a *oauth2.App) string {
//line template/app_index.qtpl:32
	qb422016 := qt422016.AcquireByteBuffer()
//line template/app_index.qtpl:32
	p.writerenderAppItem(qb422016, a)
//line template/app_index.qtpl:32
	qs422016 := string(qb422016.B)
//line template/app_index.qtpl:32
	qt422016.ReleaseByteBuffer(qb422016)
//line template/app_index.qtpl:32
	return qs422016
//line template/app_index.qtpl:32
}

//line template/app_index.qtpl:34
func (p *AppIndex) StreamBody(qw422016 *qt422016.Writer) {
//line template/app_index.qtpl:34
	qw422016.N().S(` <div class="panel"> `)
//line template/app_index.qtpl:36
	if len(p.Apps) == 0 {
//line template/app_index.qtpl:36
		qw422016.N().S(` <div class="panel-message muted">No OAuth applications created.</div> `)
//line template/app_index.qtpl:38
	} else {
//line template/app_index.qtpl:38
		qw422016.N().S(` <table class="table"> <tbody> `)
//line template/app_index.qtpl:41
		for _, a := range p.Apps {
//line template/app_index.qtpl:41
			qw422016.N().S(` `)
//line template/app_index.qtpl:42
			p.streamrenderAppItem(qw422016, a)
//line template/app_index.qtpl:42
			qw422016.N().S(` `)
//line template/app_index.qtpl:43
		}
//line template/app_index.qtpl:43
		qw422016.N().S(` </tbody> </table> `)
//line template/app_index.qtpl:46
	}
//line template/app_index.qtpl:46
	qw422016.N().S(` </div> `)
//line template/app_index.qtpl:48
}

//line template/app_index.qtpl:48
func (p *AppIndex) WriteBody(qq422016 qtio422016.Writer) {
//line template/app_index.qtpl:48
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template/app_index.qtpl:48
	p.StreamBody(qw422016)
//line template/app_index.qtpl:48
	qt422016.ReleaseWriter(qw422016)
//line template/app_index.qtpl:48
}

//line template/app_index.qtpl:48
func (p *AppIndex) Body() string {
//line template/app_index.qtpl:48
	qb422016 := qt422016.AcquireByteBuffer()
//line template/app_index.qtpl:48
	p.WriteBody(qb422016)
//line template/app_index.qtpl:48
	qs422016 := string(qb422016.B)
//line template/app_index.qtpl:48
	qt422016.ReleaseByteBuffer(qb422016)
//line template/app_index.qtpl:48
	return qs422016
//line template/app_index.qtpl:48
}
