// Code generated by qtc from "build_index.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line template/build_index.qtpl:2
package template

//line template/build_index.qtpl:2
import (
	"net/url"
	"strings"

	"djinn-ci.com/build"
)

//line template/build_index.qtpl:10
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line template/build_index.qtpl:10
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line template/build_index.qtpl:11
type BuildIndex struct {
	*Paginator

	Builds []*build.Build
}

func linkToQuery(url *url.URL, query map[string]string) string {
	q := url.Query()

	for k, v := range query {
		if v == "" {
			delete(q, k)
			continue
		}
		q.Set(k, v)
	}

	url2 := (*url)
	url2.RawQuery = q.Encode()

	return url2.String()
}

//line template/build_index.qtpl:36
func (p *BuildIndex) streamrenderStatusNav(qw422016 *qt422016.Writer, q url.Values) {
//line template/build_index.qtpl:36
	qw422016.N().S(` `)
//line template/build_index.qtpl:37
	qw422016.N().S(`<ul class="panel-nav"><li><a href="`)
//line template/build_index.qtpl:40
	qw422016.E().S(linkToQuery(p.URL, map[string]string{"status": "", "tag": q.Get("tag")}))
//line template/build_index.qtpl:40
	qw422016.N().S(`"`)
//line template/build_index.qtpl:40
	if !q.Has("status") {
//line template/build_index.qtpl:40
		qw422016.N().S(`class="active"`)
//line template/build_index.qtpl:40
	}
//line template/build_index.qtpl:40
	qw422016.N().S(`>`)
//line template/build_index.qtpl:41
	qw422016.N().S(`<!-- Generated by IcoMoon.io -->
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
<path d="M22.688 18.984c0.422 0.281 0.422 0.984-0.094 1.406l-2.297 2.297c-0.422 0.422-0.984 0.422-1.406 0l-9.094-9.094c-2.297 0.891-4.969 0.422-6.891-1.5-2.016-2.016-2.531-5.016-1.313-7.406l4.406 4.313 3-3-4.313-4.313c2.391-1.078 5.391-0.703 7.406 1.313 1.922 1.922 2.391 4.594 1.5 6.891z"></path>
</svg>
`)
//line template/build_index.qtpl:41
	qw422016.N().S(`<span>All</span></a></li><li><a href="`)
//line template/build_index.qtpl:45
	qw422016.E().S(linkToQuery(p.URL, map[string]string{"status": "queued", "tag": q.Get("tag")}))
//line template/build_index.qtpl:45
	qw422016.N().S(`"`)
//line template/build_index.qtpl:45
	if q.Get("status") == "queued" {
//line template/build_index.qtpl:45
		qw422016.N().S(`class="active"`)
//line template/build_index.qtpl:45
	}
//line template/build_index.qtpl:45
	qw422016.N().S(`>`)
//line template/build_index.qtpl:46
	qw422016.N().S(`<!-- Generated by IcoMoon.io -->
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
<path d="M12 11.484l3.984-3.984v-3.516h-7.969v3.516zM15.984 16.5l-3.984-3.984-3.984 3.984v3.516h7.969v-3.516zM6 2.016h12v6l-3.984 3.984 3.984 3.984v6h-12v-6l3.984-3.984-3.984-3.984v-6z"></path>
</svg>
`)
//line template/build_index.qtpl:46
	qw422016.N().S(`<span>Queued</span></a></li><li><a href="`)
//line template/build_index.qtpl:50
	qw422016.E().S(linkToQuery(p.URL, map[string]string{"status": "running", "tag": q.Get("tag")}))
//line template/build_index.qtpl:50
	qw422016.N().S(`"`)
//line template/build_index.qtpl:50
	if q.Get("status") == "running" {
//line template/build_index.qtpl:50
		qw422016.N().S(`class="active"`)
//line template/build_index.qtpl:50
	}
//line template/build_index.qtpl:50
	qw422016.N().S(`>`)
//line template/build_index.qtpl:51
	qw422016.N().S(`<!-- Generated by IcoMoon.io -->
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
<path d="M21.984 12c0 5.156-3.938 9.422-8.953 9.938v-2.016c3.938-0.516 6.984-3.891 6.984-7.922s-3.047-7.406-6.984-7.922v-2.016c5.016 0.516 8.953 4.781 8.953 9.938zM5.672 19.734l1.406-1.406c1.125 0.844 2.484 1.406 3.938 1.594v2.016c-2.016-0.188-3.844-0.984-5.344-2.203zM4.078 12.984c0.188 1.453 0.75 2.813 1.594 3.891l-1.406 1.453c-1.219-1.5-2.016-3.328-2.203-5.344h2.016zM5.672 7.078c-0.844 1.125-1.406 2.484-1.594 3.938h-2.016c0.188-2.016 0.984-3.844 2.203-5.344zM11.016 4.078c-1.453 0.188-2.813 0.75-3.938 1.594l-1.406-1.406c1.5-1.219 3.328-2.016 5.344-2.203v2.016zM13.031 9.797l2.953 2.203c-2.007 1.493-4.007 2.993-6 4.5z"></path>
</svg>
`)
//line template/build_index.qtpl:51
	qw422016.N().S(`<span>Running</span></a></li><li><a href="`)
//line template/build_index.qtpl:55
	qw422016.E().S(linkToQuery(p.URL, map[string]string{"status": "passed", "tag": q.Get("tag")}))
//line template/build_index.qtpl:55
	qw422016.N().S(`"`)
//line template/build_index.qtpl:55
	if q.Get("status") == "passed" {
//line template/build_index.qtpl:55
		qw422016.N().S(`class="active"`)
//line template/build_index.qtpl:55
	}
//line template/build_index.qtpl:55
	qw422016.N().S(`>`)
//line template/build_index.qtpl:56
	qw422016.N().S(`<!-- Generated by IcoMoon.io -->
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
<path d="M9 16.172l10.594-10.594 1.406 1.406-12 12-5.578-5.578 1.406-1.406z"></path>
</svg>
`)
//line template/build_index.qtpl:56
	qw422016.N().S(`<span>Passed</span></a></li><li><a href="`)
//line template/build_index.qtpl:60
	qw422016.E().S(linkToQuery(p.URL, map[string]string{"status": "failed", "tag": q.Get("tag")}))
//line template/build_index.qtpl:60
	qw422016.N().S(`"`)
//line template/build_index.qtpl:60
	if q.Get("status") == "failed" {
//line template/build_index.qtpl:60
		qw422016.N().S(`class="active"`)
//line template/build_index.qtpl:60
	}
//line template/build_index.qtpl:60
	qw422016.N().S(`>`)
//line template/build_index.qtpl:61
	qw422016.N().S(`<!-- Generated by IcoMoon.io -->
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
<path d="M18.984 6.422l-5.578 5.578 5.578 5.578-1.406 1.406-5.578-5.578-5.578 5.578-1.406-1.406 5.578-5.578-5.578-5.578 1.406-1.406 5.578 5.578 5.578-5.578z"></path>
</svg>
`)
//line template/build_index.qtpl:61
	qw422016.N().S(`<span>Failed</span></a></li><li><a href="`)
//line template/build_index.qtpl:65
	qw422016.E().S(linkToQuery(p.URL, map[string]string{"status": "killed", "tag": q.Get("tag")}))
//line template/build_index.qtpl:65
	qw422016.N().S(`"`)
//line template/build_index.qtpl:65
	if q.Get("status") == "killed" {
//line template/build_index.qtpl:65
		qw422016.N().S(`class="active"`)
//line template/build_index.qtpl:65
	}
//line template/build_index.qtpl:65
	qw422016.N().S(`>`)
//line template/build_index.qtpl:66
	qw422016.N().S(`<!-- Generated by IcoMoon.io -->
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
<path d="M12.984 12.984v-6h-1.969v6h1.969zM12 17.297c0.703 0 1.313-0.609 1.313-1.313s-0.609-1.266-1.313-1.266-1.313 0.563-1.313 1.266 0.609 1.313 1.313 1.313zM15.75 3l5.25 5.25v7.5l-5.25 5.25h-7.5l-5.25-5.25v-7.5l5.25-5.25h7.5z"></path>
</svg>
`)
//line template/build_index.qtpl:66
	qw422016.N().S(`<span>Killed</span></a></li><li><a href="`)
//line template/build_index.qtpl:70
	qw422016.E().S(linkToQuery(p.URL, map[string]string{"status": "timed_out", "tag": q.Get("tag")}))
//line template/build_index.qtpl:70
	qw422016.N().S(`"`)
//line template/build_index.qtpl:70
	if q.Get("status") == "timed_out" {
//line template/build_index.qtpl:70
		qw422016.N().S(`class="active"`)
//line template/build_index.qtpl:70
	}
//line template/build_index.qtpl:70
	qw422016.N().S(`>`)
//line template/build_index.qtpl:71
	qw422016.N().S(`<!-- Generated by IcoMoon.io -->
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
<path d="M12 20.016c3.891 0 6.984-3.141 6.984-7.031s-3.094-6.984-6.984-6.984-6.984 3.094-6.984 6.984 3.094 7.031 6.984 7.031zM19.031 7.406c1.219 1.547 1.969 3.469 1.969 5.578 0 4.969-4.031 9-9 9s-9-4.031-9-9 4.031-9 9-9c2.109 0 4.078 0.797 5.625 2.016l1.406-1.453c0.516 0.422 0.984 0.891 1.406 1.406zM11.016 14.016v-6h1.969v6h-1.969zM15 0.984v2.016h-6v-2.016h6z"></path>
</svg>
`)
//line template/build_index.qtpl:71
	qw422016.N().S(`<span>Timed Out</span></a></li></ul>`)
//line template/build_index.qtpl:75
	qw422016.N().S(` `)
//line template/build_index.qtpl:76
}

//line template/build_index.qtpl:76
func (p *BuildIndex) writerenderStatusNav(qq422016 qtio422016.Writer, q url.Values) {
//line template/build_index.qtpl:76
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template/build_index.qtpl:76
	p.streamrenderStatusNav(qw422016, q)
//line template/build_index.qtpl:76
	qt422016.ReleaseWriter(qw422016)
//line template/build_index.qtpl:76
}

//line template/build_index.qtpl:76
func (p *BuildIndex) renderStatusNav(q url.Values) string {
//line template/build_index.qtpl:76
	qb422016 := qt422016.AcquireByteBuffer()
//line template/build_index.qtpl:76
	p.writerenderStatusNav(qb422016, q)
//line template/build_index.qtpl:76
	qs422016 := string(qb422016.B)
//line template/build_index.qtpl:76
	qt422016.ReleaseByteBuffer(qb422016)
//line template/build_index.qtpl:76
	return qs422016
//line template/build_index.qtpl:76
}

//line template/build_index.qtpl:78
func (p *BuildIndex) StreamTitle(qw422016 *qt422016.Writer) {
//line template/build_index.qtpl:78
	qw422016.N().S(`Builds`)
//line template/build_index.qtpl:78
}

//line template/build_index.qtpl:78
func (p *BuildIndex) WriteTitle(qq422016 qtio422016.Writer) {
//line template/build_index.qtpl:78
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template/build_index.qtpl:78
	p.StreamTitle(qw422016)
//line template/build_index.qtpl:78
	qt422016.ReleaseWriter(qw422016)
//line template/build_index.qtpl:78
}

//line template/build_index.qtpl:78
func (p *BuildIndex) Title() string {
//line template/build_index.qtpl:78
	qb422016 := qt422016.AcquireByteBuffer()
//line template/build_index.qtpl:78
	p.WriteTitle(qb422016)
//line template/build_index.qtpl:78
	qs422016 := string(qb422016.B)
//line template/build_index.qtpl:78
	qt422016.ReleaseByteBuffer(qb422016)
//line template/build_index.qtpl:78
	return qs422016
//line template/build_index.qtpl:78
}

//line template/build_index.qtpl:80
func (p *BuildIndex) StreamHeader(qw422016 *qt422016.Writer) {
//line template/build_index.qtpl:80
	qw422016.N().S(` Builds `)
//line template/build_index.qtpl:82
	if tag := p.Query.Get("tag"); tag != "" {
//line template/build_index.qtpl:82
		qw422016.N().S(` <span class="pill pill-light"> `)
//line template/build_index.qtpl:84
		qw422016.E().S(tag)
//line template/build_index.qtpl:84
		qw422016.N().S(`<a href="`)
//line template/build_index.qtpl:84
		qw422016.E().S(p.Href(url.Values{"tag": {""}}))
//line template/build_index.qtpl:84
		qw422016.N().S(`">`)
//line template/build_index.qtpl:84
		qw422016.N().S(`<!-- Generated by IcoMoon.io -->
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
<path d="M18.984 6.422l-5.578 5.578 5.578 5.578-1.406 1.406-5.578-5.578-5.578 5.578-1.406-1.406 5.578-5.578-5.578-5.578 1.406-1.406 5.578 5.578 5.578-5.578z"></path>
</svg>
`)
//line template/build_index.qtpl:84
		qw422016.N().S(`</a> </span> `)
//line template/build_index.qtpl:86
	}
//line template/build_index.qtpl:86
	qw422016.N().S(` `)
//line template/build_index.qtpl:87
}

//line template/build_index.qtpl:87
func (p *BuildIndex) WriteHeader(qq422016 qtio422016.Writer) {
//line template/build_index.qtpl:87
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template/build_index.qtpl:87
	p.StreamHeader(qw422016)
//line template/build_index.qtpl:87
	qt422016.ReleaseWriter(qw422016)
//line template/build_index.qtpl:87
}

//line template/build_index.qtpl:87
func (p *BuildIndex) Header() string {
//line template/build_index.qtpl:87
	qb422016 := qt422016.AcquireByteBuffer()
//line template/build_index.qtpl:87
	p.WriteHeader(qb422016)
//line template/build_index.qtpl:87
	qs422016 := string(qb422016.B)
//line template/build_index.qtpl:87
	qt422016.ReleaseByteBuffer(qb422016)
//line template/build_index.qtpl:87
	return qs422016
//line template/build_index.qtpl:87
}

//line template/build_index.qtpl:89
func (p *BuildIndex) StreamActions(qw422016 *qt422016.Writer) {
//line template/build_index.qtpl:89
	qw422016.N().S(` `)
//line template/build_index.qtpl:90
	if _, ok := p.User.Permissions["build:write"]; ok {
//line template/build_index.qtpl:90
		qw422016.N().S(` <li><a href="/builds/create" class="btn btn-primary">Submit</a></li> `)
//line template/build_index.qtpl:92
	}
//line template/build_index.qtpl:92
	qw422016.N().S(` `)
//line template/build_index.qtpl:93
}

//line template/build_index.qtpl:93
func (p *BuildIndex) WriteActions(qq422016 qtio422016.Writer) {
//line template/build_index.qtpl:93
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template/build_index.qtpl:93
	p.StreamActions(qw422016)
//line template/build_index.qtpl:93
	qt422016.ReleaseWriter(qw422016)
//line template/build_index.qtpl:93
}

//line template/build_index.qtpl:93
func (p *BuildIndex) Actions() string {
//line template/build_index.qtpl:93
	qb422016 := qt422016.AcquireByteBuffer()
//line template/build_index.qtpl:93
	p.WriteActions(qb422016)
//line template/build_index.qtpl:93
	qs422016 := string(qb422016.B)
//line template/build_index.qtpl:93
	qt422016.ReleaseByteBuffer(qb422016)
//line template/build_index.qtpl:93
	return qs422016
//line template/build_index.qtpl:93
}

//line template/build_index.qtpl:95
func (p *BuildIndex) StreamNavigation(qw422016 *qt422016.Writer) {
//line template/build_index.qtpl:95
}

//line template/build_index.qtpl:95
func (p *BuildIndex) WriteNavigation(qq422016 qtio422016.Writer) {
//line template/build_index.qtpl:95
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template/build_index.qtpl:95
	p.StreamNavigation(qw422016)
//line template/build_index.qtpl:95
	qt422016.ReleaseWriter(qw422016)
//line template/build_index.qtpl:95
}

//line template/build_index.qtpl:95
func (p *BuildIndex) Navigation() string {
//line template/build_index.qtpl:95
	qb422016 := qt422016.AcquireByteBuffer()
//line template/build_index.qtpl:95
	p.WriteNavigation(qb422016)
//line template/build_index.qtpl:95
	qs422016 := string(qb422016.B)
//line template/build_index.qtpl:95
	qt422016.ReleaseByteBuffer(qb422016)
//line template/build_index.qtpl:95
	return qs422016
//line template/build_index.qtpl:95
}

//line template/build_index.qtpl:96
func (p *BuildIndex) StreamFooter(qw422016 *qt422016.Writer) {
//line template/build_index.qtpl:96
}

//line template/build_index.qtpl:96
func (p *BuildIndex) WriteFooter(qq422016 qtio422016.Writer) {
//line template/build_index.qtpl:96
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template/build_index.qtpl:96
	p.StreamFooter(qw422016)
//line template/build_index.qtpl:96
	qt422016.ReleaseWriter(qw422016)
//line template/build_index.qtpl:96
}

//line template/build_index.qtpl:96
func (p *BuildIndex) Footer() string {
//line template/build_index.qtpl:96
	qb422016 := qt422016.AcquireByteBuffer()
//line template/build_index.qtpl:96
	p.WriteFooter(qb422016)
//line template/build_index.qtpl:96
	qs422016 := string(qb422016.B)
//line template/build_index.qtpl:96
	qt422016.ReleaseByteBuffer(qb422016)
//line template/build_index.qtpl:96
	return qs422016
//line template/build_index.qtpl:96
}

//line template/build_index.qtpl:98
func (p *BuildIndex) streamrenderTag(qw422016 *qt422016.Writer, t *build.Tag) {
//line template/build_index.qtpl:98
	qw422016.N().S(` <a class="pill pill-light" href="`)
//line template/build_index.qtpl:99
	qw422016.E().S(p.Href(url.Values{"tag": {t.Name}}))
//line template/build_index.qtpl:99
	qw422016.N().S(`" title="`)
//line template/build_index.qtpl:99
	qw422016.E().S(t.Name)
//line template/build_index.qtpl:99
	qw422016.N().S(`"> `)
//line template/build_index.qtpl:100
	if len(t.Name) > 21 {
//line template/build_index.qtpl:100
		qw422016.N().S(` `)
//line template/build_index.qtpl:101
		qw422016.E().S(t.Name[:21])
//line template/build_index.qtpl:101
		qw422016.N().S(`... `)
//line template/build_index.qtpl:102
	} else {
//line template/build_index.qtpl:102
		qw422016.N().S(` `)
//line template/build_index.qtpl:103
		qw422016.E().S(t.Name)
//line template/build_index.qtpl:103
		qw422016.N().S(` `)
//line template/build_index.qtpl:104
	}
//line template/build_index.qtpl:104
	qw422016.N().S(` </a> `)
//line template/build_index.qtpl:106
}

//line template/build_index.qtpl:106
func (p *BuildIndex) writerenderTag(qq422016 qtio422016.Writer, t *build.Tag) {
//line template/build_index.qtpl:106
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template/build_index.qtpl:106
	p.streamrenderTag(qw422016, t)
//line template/build_index.qtpl:106
	qt422016.ReleaseWriter(qw422016)
//line template/build_index.qtpl:106
}

//line template/build_index.qtpl:106
func (p *BuildIndex) renderTag(t *build.Tag) string {
//line template/build_index.qtpl:106
	qb422016 := qt422016.AcquireByteBuffer()
//line template/build_index.qtpl:106
	p.writerenderTag(qb422016, t)
//line template/build_index.qtpl:106
	qs422016 := string(qb422016.B)
//line template/build_index.qtpl:106
	qt422016.ReleaseByteBuffer(qb422016)
//line template/build_index.qtpl:106
	return qs422016
//line template/build_index.qtpl:106
}

//line template/build_index.qtpl:108
func (p *BuildIndex) streamrenderBuildItem(qw422016 *qt422016.Writer, b *build.Build) {
//line template/build_index.qtpl:108
	qw422016.N().S(` <tr> <td>`)
//line template/build_index.qtpl:110
	StreamStatus(qw422016, b.Status)
//line template/build_index.qtpl:110
	qw422016.N().S(`</td> <td> <a href="`)
//line template/build_index.qtpl:112
	qw422016.E().S(b.Endpoint())
//line template/build_index.qtpl:112
	qw422016.N().S(`"> #`)
//line template/build_index.qtpl:113
	qw422016.E().V(b.Number)
//line template/build_index.qtpl:113
	qw422016.N().S(` `)
//line template/build_index.qtpl:114
	if b.Trigger.Comment != "" {
//line template/build_index.qtpl:114
		qw422016.N().S(` - `)
//line template/build_index.qtpl:114
		qw422016.E().S(b.Trigger.CommentTitle())
//line template/build_index.qtpl:114
	}
//line template/build_index.qtpl:114
	qw422016.N().S(` </a> </td> <td> `)
//line template/build_index.qtpl:118
	if b.Namespace != nil {
//line template/build_index.qtpl:118
		qw422016.N().S(` <a href="`)
//line template/build_index.qtpl:119
		qw422016.E().S(b.Namespace.Endpoint())
//line template/build_index.qtpl:119
		qw422016.N().S(`">`)
//line template/build_index.qtpl:119
		qw422016.E().S(b.Namespace.Path)
//line template/build_index.qtpl:119
		qw422016.N().S(`</a> `)
//line template/build_index.qtpl:120
	} else {
//line template/build_index.qtpl:120
		qw422016.N().S(` <span class="muted">--</span> `)
//line template/build_index.qtpl:122
	}
//line template/build_index.qtpl:122
	qw422016.N().S(` </td> <td class="align-right hide-mobile"> `)
//line template/build_index.qtpl:125
	for i, t := range b.Tags {
//line template/build_index.qtpl:125
		qw422016.N().S(` `)
//line template/build_index.qtpl:126
		if i > 2 {
//line template/build_index.qtpl:126
			qw422016.N().S(` `)
//line template/build_index.qtpl:127
			break
//line template/build_index.qtpl:128
		}
//line template/build_index.qtpl:128
		qw422016.N().S(` `)
//line template/build_index.qtpl:129
		p.streamrenderTag(qw422016, t)
//line template/build_index.qtpl:129
		qw422016.N().S(` `)
//line template/build_index.qtpl:130
	}
//line template/build_index.qtpl:130
	qw422016.N().S(` `)
//line template/build_index.qtpl:131
	if len(b.Tags) > 3 {
//line template/build_index.qtpl:131
		qw422016.N().S(` <a class="pill pill-light" href="`)
//line template/build_index.qtpl:132
		qw422016.E().S(b.Endpoint("tags"))
//line template/build_index.qtpl:132
		qw422016.N().S(`" title="Build tags">...</a> `)
//line template/build_index.qtpl:133
	}
//line template/build_index.qtpl:133
	qw422016.N().S(` </td> <td class="align-right"> `)
//line template/build_index.qtpl:136
	if b.Pinned {
//line template/build_index.qtpl:136
		qw422016.N().S(` `)
//line template/build_index.qtpl:137
		if p.Query.Has("pinned") {
//line template/build_index.qtpl:137
			qw422016.N().S(` <a href="`)
//line template/build_index.qtpl:138
			qw422016.E().S(p.Href(url.Values{"pinned": {""}}))
//line template/build_index.qtpl:138
			qw422016.N().S(`"> <span class="muted" title="Pinned">`)
//line template/build_index.qtpl:139
			qw422016.N().S(`<!-- Generated by IcoMoon.io -->
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
<path d="M12.75 0l-2.25 2.25 2.25 2.25-5.25 6h-5.25l4.125 4.125-6.375 8.452v0.923h0.923l8.452-6.375 4.125 4.125v-5.25l6-5.25 2.25 2.25 2.25-2.25-11.25-11.25zM10.5 12.75l-1.5-1.5 5.25-5.25 1.5 1.5-5.25 5.25z"></path>
</svg>
`)
//line template/build_index.qtpl:139
			qw422016.N().S(`</span> </a> `)
//line template/build_index.qtpl:141
		} else {
//line template/build_index.qtpl:141
			qw422016.N().S(` <a href="`)
//line template/build_index.qtpl:142
			qw422016.E().S(p.Href(url.Values{"pinned": {"true"}}))
//line template/build_index.qtpl:142
			qw422016.N().S(`"> <span class="muted" title="Pinned">`)
//line template/build_index.qtpl:143
			qw422016.N().S(`<!-- Generated by IcoMoon.io -->
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
<path d="M12.75 0l-2.25 2.25 2.25 2.25-5.25 6h-5.25l4.125 4.125-6.375 8.452v0.923h0.923l8.452-6.375 4.125 4.125v-5.25l6-5.25 2.25 2.25 2.25-2.25-11.25-11.25zM10.5 12.75l-1.5-1.5 5.25-5.25 1.5 1.5-5.25 5.25z"></path>
</svg>
`)
//line template/build_index.qtpl:143
			qw422016.N().S(`</span> </a> `)
//line template/build_index.qtpl:145
		}
//line template/build_index.qtpl:145
		qw422016.N().S(` `)
//line template/build_index.qtpl:146
	}
//line template/build_index.qtpl:146
	qw422016.N().S(` `)
//line template/build_index.qtpl:147
	if p.User.ID != b.UserID {
//line template/build_index.qtpl:147
		qw422016.N().S(` <span class="muted">`)
//line template/build_index.qtpl:148
		qw422016.N().S(`<!-- Generated by IcoMoon.io -->
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
<path d="M15.984 12.984c2.344 0 7.031 1.172 7.031 3.516v2.484h-6v-2.484c0-1.5-0.797-2.625-1.969-3.469 0.328-0.047 0.656-0.047 0.938-0.047zM8.016 12.984c2.344 0 6.984 1.172 6.984 3.516v2.484h-14.016v-2.484c0-2.344 4.688-3.516 7.031-3.516zM8.016 11.016c-1.641 0-3-1.359-3-3s1.359-3 3-3 2.953 1.359 2.953 3-1.313 3-2.953 3zM15.984 11.016c-1.641 0-3-1.359-3-3s1.359-3 3-3 3 1.359 3 3-1.359 3-3 3z"></path>
</svg>
`)
//line template/build_index.qtpl:148
		qw422016.N().S(`</span> `)
//line template/build_index.qtpl:149
	}
//line template/build_index.qtpl:149
	qw422016.N().S(` </td> </tr> `)
//line template/build_index.qtpl:152
}

//line template/build_index.qtpl:152
func (p *BuildIndex) writerenderBuildItem(qq422016 qtio422016.Writer, b *build.Build) {
//line template/build_index.qtpl:152
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template/build_index.qtpl:152
	p.streamrenderBuildItem(qw422016, b)
//line template/build_index.qtpl:152
	qt422016.ReleaseWriter(qw422016)
//line template/build_index.qtpl:152
}

//line template/build_index.qtpl:152
func (p *BuildIndex) renderBuildItem(b *build.Build) string {
//line template/build_index.qtpl:152
	qb422016 := qt422016.AcquireByteBuffer()
//line template/build_index.qtpl:152
	p.writerenderBuildItem(qb422016, b)
//line template/build_index.qtpl:152
	qs422016 := string(qb422016.B)
//line template/build_index.qtpl:152
	qt422016.ReleaseByteBuffer(qb422016)
//line template/build_index.qtpl:152
	return qs422016
//line template/build_index.qtpl:152
}

//line template/build_index.qtpl:154
func (p *BuildIndex) StreamBody(qw422016 *qt422016.Writer) {
//line template/build_index.qtpl:154
	qw422016.N().S(` <div class="panel"> `)
//line template/build_index.qtpl:156
	if len(p.Builds) == 0 {
//line template/build_index.qtpl:156
		qw422016.N().S(` `)
//line template/build_index.qtpl:157
		if query := p.Query.Get("search"); query != "" {
//line template/build_index.qtpl:157
			qw422016.N().S(` <div class="panel-header">`)
//line template/build_index.qtpl:158
			p.StreamSearch(qw422016, "Find a build...")
//line template/build_index.qtpl:158
			qw422016.N().S(`</div> <div class="panel-message muted">No results found.</div> `)
//line template/build_index.qtpl:160
		} else if status := p.Query.Get("status"); status != "" {
//line template/build_index.qtpl:160
			qw422016.N().S(` <div class="panel-message muted"> No `)
//line template/build_index.qtpl:162
			qw422016.E().S(strings.Replace(p.Query.Get("status"), "_", " ", -1))
//line template/build_index.qtpl:162
			qw422016.N().S(` builds. </div> `)
//line template/build_index.qtpl:164
		} else {
//line template/build_index.qtpl:164
			qw422016.N().S(` <div class="panel-message muted">No builds have been submitted yet.</div> `)
//line template/build_index.qtpl:166
		}
//line template/build_index.qtpl:166
		qw422016.N().S(` `)
//line template/build_index.qtpl:167
	} else {
//line template/build_index.qtpl:167
		qw422016.N().S(` <div class="panel-header"> `)
//line template/build_index.qtpl:169
		p.streamrenderStatusNav(qw422016, p.URL.Query())
//line template/build_index.qtpl:169
		qw422016.N().S(` `)
//line template/build_index.qtpl:170
		p.StreamSearch(qw422016, "Find a build...")
//line template/build_index.qtpl:170
		qw422016.N().S(` </div> <table class="table"> <thead> <tr> <th>STATUS</th> <th>BUILD</th> <th>NAMESPACE</th> <th class="hide-mobile"></th> <th></th> <th></th> </tr> </thead> <tbody> `)
//line template/build_index.qtpl:184
		for _, b := range p.Builds {
//line template/build_index.qtpl:184
			qw422016.N().S(` `)
//line template/build_index.qtpl:185
			p.streamrenderBuildItem(qw422016, b)
//line template/build_index.qtpl:185
			qw422016.N().S(` `)
//line template/build_index.qtpl:186
		}
//line template/build_index.qtpl:186
		qw422016.N().S(` </tbody> </table> `)
//line template/build_index.qtpl:189
	}
//line template/build_index.qtpl:189
	qw422016.N().S(` </div> `)
//line template/build_index.qtpl:191
	p.Paginator.StreamNavigation(qw422016)
//line template/build_index.qtpl:191
	qw422016.N().S(` `)
//line template/build_index.qtpl:192
}

//line template/build_index.qtpl:192
func (p *BuildIndex) WriteBody(qq422016 qtio422016.Writer) {
//line template/build_index.qtpl:192
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template/build_index.qtpl:192
	p.StreamBody(qw422016)
//line template/build_index.qtpl:192
	qt422016.ReleaseWriter(qw422016)
//line template/build_index.qtpl:192
}

//line template/build_index.qtpl:192
func (p *BuildIndex) Body() string {
//line template/build_index.qtpl:192
	qb422016 := qt422016.AcquireByteBuffer()
//line template/build_index.qtpl:192
	p.WriteBody(qb422016)
//line template/build_index.qtpl:192
	qs422016 := string(qb422016.B)
//line template/build_index.qtpl:192
	qt422016.ReleaseByteBuffer(qb422016)
//line template/build_index.qtpl:192
	return qs422016
//line template/build_index.qtpl:192
}
