// Code generated by qtc from "build_artifacts.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line template/build_artifacts.qtpl:1
package template

//line template/build_artifacts.qtpl:1
import "djinn-ci.com/build"

//line template/build_artifacts.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line template/build_artifacts.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line template/build_artifacts.qtpl:4
type BuildArtifacts struct {
	*Paginator

	Artifacts []*build.Artifact
}

//line template/build_artifacts.qtpl:12
func (p *BuildArtifacts) StreamTitle(qw422016 *qt422016.Writer) {
//line template/build_artifacts.qtpl:12
	qw422016.N().S(`Artifacts`)
//line template/build_artifacts.qtpl:12
}

//line template/build_artifacts.qtpl:12
func (p *BuildArtifacts) WriteTitle(qq422016 qtio422016.Writer) {
//line template/build_artifacts.qtpl:12
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template/build_artifacts.qtpl:12
	p.StreamTitle(qw422016)
//line template/build_artifacts.qtpl:12
	qt422016.ReleaseWriter(qw422016)
//line template/build_artifacts.qtpl:12
}

//line template/build_artifacts.qtpl:12
func (p *BuildArtifacts) Title() string {
//line template/build_artifacts.qtpl:12
	qb422016 := qt422016.AcquireByteBuffer()
//line template/build_artifacts.qtpl:12
	p.WriteTitle(qb422016)
//line template/build_artifacts.qtpl:12
	qs422016 := string(qb422016.B)
//line template/build_artifacts.qtpl:12
	qt422016.ReleaseByteBuffer(qb422016)
//line template/build_artifacts.qtpl:12
	return qs422016
//line template/build_artifacts.qtpl:12
}

//line template/build_artifacts.qtpl:14
func (p *BuildArtifacts) StreamHeader(qw422016 *qt422016.Writer) {
//line template/build_artifacts.qtpl:14
}

//line template/build_artifacts.qtpl:14
func (p *BuildArtifacts) WriteHeader(qq422016 qtio422016.Writer) {
//line template/build_artifacts.qtpl:14
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template/build_artifacts.qtpl:14
	p.StreamHeader(qw422016)
//line template/build_artifacts.qtpl:14
	qt422016.ReleaseWriter(qw422016)
//line template/build_artifacts.qtpl:14
}

//line template/build_artifacts.qtpl:14
func (p *BuildArtifacts) Header() string {
//line template/build_artifacts.qtpl:14
	qb422016 := qt422016.AcquireByteBuffer()
//line template/build_artifacts.qtpl:14
	p.WriteHeader(qb422016)
//line template/build_artifacts.qtpl:14
	qs422016 := string(qb422016.B)
//line template/build_artifacts.qtpl:14
	qt422016.ReleaseByteBuffer(qb422016)
//line template/build_artifacts.qtpl:14
	return qs422016
//line template/build_artifacts.qtpl:14
}

//line template/build_artifacts.qtpl:15
func (p *BuildArtifacts) StreamActions(qw422016 *qt422016.Writer) {
//line template/build_artifacts.qtpl:15
}

//line template/build_artifacts.qtpl:15
func (p *BuildArtifacts) WriteActions(qq422016 qtio422016.Writer) {
//line template/build_artifacts.qtpl:15
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template/build_artifacts.qtpl:15
	p.StreamActions(qw422016)
//line template/build_artifacts.qtpl:15
	qt422016.ReleaseWriter(qw422016)
//line template/build_artifacts.qtpl:15
}

//line template/build_artifacts.qtpl:15
func (p *BuildArtifacts) Actions() string {
//line template/build_artifacts.qtpl:15
	qb422016 := qt422016.AcquireByteBuffer()
//line template/build_artifacts.qtpl:15
	p.WriteActions(qb422016)
//line template/build_artifacts.qtpl:15
	qs422016 := string(qb422016.B)
//line template/build_artifacts.qtpl:15
	qt422016.ReleaseByteBuffer(qb422016)
//line template/build_artifacts.qtpl:15
	return qs422016
//line template/build_artifacts.qtpl:15
}

//line template/build_artifacts.qtpl:16
func (p *BuildArtifacts) StreamNavigation(qw422016 *qt422016.Writer) {
//line template/build_artifacts.qtpl:16
}

//line template/build_artifacts.qtpl:16
func (p *BuildArtifacts) WriteNavigation(qq422016 qtio422016.Writer) {
//line template/build_artifacts.qtpl:16
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template/build_artifacts.qtpl:16
	p.StreamNavigation(qw422016)
//line template/build_artifacts.qtpl:16
	qt422016.ReleaseWriter(qw422016)
//line template/build_artifacts.qtpl:16
}

//line template/build_artifacts.qtpl:16
func (p *BuildArtifacts) Navigation() string {
//line template/build_artifacts.qtpl:16
	qb422016 := qt422016.AcquireByteBuffer()
//line template/build_artifacts.qtpl:16
	p.WriteNavigation(qb422016)
//line template/build_artifacts.qtpl:16
	qs422016 := string(qb422016.B)
//line template/build_artifacts.qtpl:16
	qt422016.ReleaseByteBuffer(qb422016)
//line template/build_artifacts.qtpl:16
	return qs422016
//line template/build_artifacts.qtpl:16
}

//line template/build_artifacts.qtpl:17
func (p *BuildArtifacts) StreamFooter(qw422016 *qt422016.Writer) {
//line template/build_artifacts.qtpl:17
}

//line template/build_artifacts.qtpl:17
func (p *BuildArtifacts) WriteFooter(qq422016 qtio422016.Writer) {
//line template/build_artifacts.qtpl:17
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template/build_artifacts.qtpl:17
	p.StreamFooter(qw422016)
//line template/build_artifacts.qtpl:17
	qt422016.ReleaseWriter(qw422016)
//line template/build_artifacts.qtpl:17
}

//line template/build_artifacts.qtpl:17
func (p *BuildArtifacts) Footer() string {
//line template/build_artifacts.qtpl:17
	qb422016 := qt422016.AcquireByteBuffer()
//line template/build_artifacts.qtpl:17
	p.WriteFooter(qb422016)
//line template/build_artifacts.qtpl:17
	qs422016 := string(qb422016.B)
//line template/build_artifacts.qtpl:17
	qt422016.ReleaseByteBuffer(qb422016)
//line template/build_artifacts.qtpl:17
	return qs422016
//line template/build_artifacts.qtpl:17
}

//line template/build_artifacts.qtpl:19
func (p *BuildArtifacts) streamrenderArtifactItem(qw422016 *qt422016.Writer, a *build.Artifact) {
//line template/build_artifacts.qtpl:19
	qw422016.N().S(` <tr> <td> `)
//line template/build_artifacts.qtpl:22
	if a.DeletedAt.Valid || a.MD5 == nil && a.SHA256 == nil {
//line template/build_artifacts.qtpl:22
		qw422016.N().S(` <a `)
//line template/build_artifacts.qtpl:23
		if a.DeletedAt.Valid {
//line template/build_artifacts.qtpl:23
			qw422016.N().S(`title="Artifact deleted"`)
//line template/build_artifacts.qtpl:23
		}
//line template/build_artifacts.qtpl:23
		qw422016.N().S(`><strike>`)
//line template/build_artifacts.qtpl:23
		qw422016.E().S(a.Name)
//line template/build_artifacts.qtpl:23
		qw422016.N().S(`</strike></a> `)
//line template/build_artifacts.qtpl:24
	} else {
//line template/build_artifacts.qtpl:24
		qw422016.N().S(` <a href="`)
//line template/build_artifacts.qtpl:25
		qw422016.E().S(a.Endpoint())
//line template/build_artifacts.qtpl:25
		qw422016.N().S(`">`)
//line template/build_artifacts.qtpl:25
		qw422016.E().S(a.Name)
//line template/build_artifacts.qtpl:25
		qw422016.N().S(`</a> `)
//line template/build_artifacts.qtpl:26
	}
//line template/build_artifacts.qtpl:26
	qw422016.N().S(` </td> <td>`)
//line template/build_artifacts.qtpl:28
	qw422016.E().S(HumanSize(a.Size.Elem))
//line template/build_artifacts.qtpl:28
	qw422016.N().S(`</td> <td class="align-right"> `)
//line template/build_artifacts.qtpl:30
	if a.MD5 == nil {
//line template/build_artifacts.qtpl:30
		qw422016.N().S(` <span class="code">--</span> `)
//line template/build_artifacts.qtpl:32
	} else {
//line template/build_artifacts.qtpl:32
		qw422016.N().S(` <span class="code">`)
//line template/build_artifacts.qtpl:33
		qw422016.E().S(a.MD5.String()[:7])
//line template/build_artifacts.qtpl:33
		qw422016.N().S(`</span> `)
//line template/build_artifacts.qtpl:34
	}
//line template/build_artifacts.qtpl:34
	qw422016.N().S(` </td> <td class="align-right"> `)
//line template/build_artifacts.qtpl:37
	if a.SHA256 == nil {
//line template/build_artifacts.qtpl:37
		qw422016.N().S(` <span class="code">--</span> `)
//line template/build_artifacts.qtpl:39
	} else {
//line template/build_artifacts.qtpl:39
		qw422016.N().S(` <span class="code">`)
//line template/build_artifacts.qtpl:40
		qw422016.E().S(a.SHA256.String()[:7])
//line template/build_artifacts.qtpl:40
		qw422016.N().S(`</span> `)
//line template/build_artifacts.qtpl:41
	}
//line template/build_artifacts.qtpl:41
	qw422016.N().S(` </td> </tr> `)
//line template/build_artifacts.qtpl:44
}

//line template/build_artifacts.qtpl:44
func (p *BuildArtifacts) writerenderArtifactItem(qq422016 qtio422016.Writer, a *build.Artifact) {
//line template/build_artifacts.qtpl:44
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template/build_artifacts.qtpl:44
	p.streamrenderArtifactItem(qw422016, a)
//line template/build_artifacts.qtpl:44
	qt422016.ReleaseWriter(qw422016)
//line template/build_artifacts.qtpl:44
}

//line template/build_artifacts.qtpl:44
func (p *BuildArtifacts) renderArtifactItem(a *build.Artifact) string {
//line template/build_artifacts.qtpl:44
	qb422016 := qt422016.AcquireByteBuffer()
//line template/build_artifacts.qtpl:44
	p.writerenderArtifactItem(qb422016, a)
//line template/build_artifacts.qtpl:44
	qs422016 := string(qb422016.B)
//line template/build_artifacts.qtpl:44
	qt422016.ReleaseByteBuffer(qb422016)
//line template/build_artifacts.qtpl:44
	return qs422016
//line template/build_artifacts.qtpl:44
}

//line template/build_artifacts.qtpl:46
func (p *BuildArtifacts) StreamBody(qw422016 *qt422016.Writer) {
//line template/build_artifacts.qtpl:46
	qw422016.N().S(` <div class="panel"> `)
//line template/build_artifacts.qtpl:48
	if len(p.Artifacts) == 0 {
//line template/build_artifacts.qtpl:48
		qw422016.N().S(` `)
//line template/build_artifacts.qtpl:49
		if query := p.Query.Get("search"); query != "" {
//line template/build_artifacts.qtpl:49
			qw422016.N().S(` <div class="panel-header">`)
//line template/build_artifacts.qtpl:50
			p.StreamSearch(qw422016, "Find an artifact...")
//line template/build_artifacts.qtpl:50
			qw422016.N().S(`</div> <div class="panel-message muted">No results found.</div> `)
//line template/build_artifacts.qtpl:52
		} else {
//line template/build_artifacts.qtpl:52
			qw422016.N().S(` <div class="panel-message muted"> No artifacts have been collected from this build. </div> `)
//line template/build_artifacts.qtpl:56
		}
//line template/build_artifacts.qtpl:56
		qw422016.N().S(` `)
//line template/build_artifacts.qtpl:57
	} else {
//line template/build_artifacts.qtpl:57
		qw422016.N().S(` <div class="panel-header">`)
//line template/build_artifacts.qtpl:58
		p.StreamSearch(qw422016, "Find an artifact...")
//line template/build_artifacts.qtpl:58
		qw422016.N().S(`</div> <table class="table"> <thead> <tr> <th>NAME</th> <th>SIZE</th> <th class="align-right">MD5</th> <th class="align-right">SHA256</th> </tr> </thead> <tbody> `)
//line template/build_artifacts.qtpl:69
		for _, a := range p.Artifacts {
//line template/build_artifacts.qtpl:69
			qw422016.N().S(` `)
//line template/build_artifacts.qtpl:70
			p.streamrenderArtifactItem(qw422016, a)
//line template/build_artifacts.qtpl:70
			qw422016.N().S(` `)
//line template/build_artifacts.qtpl:71
		}
//line template/build_artifacts.qtpl:71
		qw422016.N().S(` </tbody> </table> `)
//line template/build_artifacts.qtpl:74
	}
//line template/build_artifacts.qtpl:74
	qw422016.N().S(` </div> `)
//line template/build_artifacts.qtpl:76
}

//line template/build_artifacts.qtpl:76
func (p *BuildArtifacts) WriteBody(qq422016 qtio422016.Writer) {
//line template/build_artifacts.qtpl:76
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template/build_artifacts.qtpl:76
	p.StreamBody(qw422016)
//line template/build_artifacts.qtpl:76
	qt422016.ReleaseWriter(qw422016)
//line template/build_artifacts.qtpl:76
}

//line template/build_artifacts.qtpl:76
func (p *BuildArtifacts) Body() string {
//line template/build_artifacts.qtpl:76
	qb422016 := qt422016.AcquireByteBuffer()
//line template/build_artifacts.qtpl:76
	p.WriteBody(qb422016)
//line template/build_artifacts.qtpl:76
	qs422016 := string(qb422016.B)
//line template/build_artifacts.qtpl:76
	qt422016.ReleaseByteBuffer(qb422016)
//line template/build_artifacts.qtpl:76
	return qs422016
//line template/build_artifacts.qtpl:76
}
