// Code generated by qtc from "error.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line template/error.qtpl:3
package template

//line template/error.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line template/error.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line template/error.qtpl:4
type Error struct {
	BasePage

	Code    int
	Message string
}

//line template/error.qtpl:13
func (p *Error) StreamTitle(qw422016 *qt422016.Writer) {
//line template/error.qtpl:13
	qw422016.N().S(` Error - Thrall `)
//line template/error.qtpl:15
}

//line template/error.qtpl:15
func (p *Error) WriteTitle(qq422016 qtio422016.Writer) {
//line template/error.qtpl:15
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template/error.qtpl:15
	p.StreamTitle(qw422016)
//line template/error.qtpl:15
	qt422016.ReleaseWriter(qw422016)
//line template/error.qtpl:15
}

//line template/error.qtpl:15
func (p *Error) Title() string {
//line template/error.qtpl:15
	qb422016 := qt422016.AcquireByteBuffer()
//line template/error.qtpl:15
	p.WriteTitle(qb422016)
//line template/error.qtpl:15
	qs422016 := string(qb422016.B)
//line template/error.qtpl:15
	qt422016.ReleaseByteBuffer(qb422016)
//line template/error.qtpl:15
	return qs422016
//line template/error.qtpl:15
}

//line template/error.qtpl:17
func (p *Error) StreamStyles(qw422016 *qt422016.Writer) {
//line template/error.qtpl:17
	qw422016.N().S(` <link rel="stylesheet" type="text/css" href="/assets/css/error.css"> `)
//line template/error.qtpl:19
}

//line template/error.qtpl:19
func (p *Error) WriteStyles(qq422016 qtio422016.Writer) {
//line template/error.qtpl:19
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template/error.qtpl:19
	p.StreamStyles(qw422016)
//line template/error.qtpl:19
	qt422016.ReleaseWriter(qw422016)
//line template/error.qtpl:19
}

//line template/error.qtpl:19
func (p *Error) Styles() string {
//line template/error.qtpl:19
	qb422016 := qt422016.AcquireByteBuffer()
//line template/error.qtpl:19
	p.WriteStyles(qb422016)
//line template/error.qtpl:19
	qs422016 := string(qb422016.B)
//line template/error.qtpl:19
	qt422016.ReleaseByteBuffer(qb422016)
//line template/error.qtpl:19
	return qs422016
//line template/error.qtpl:19
}

//line template/error.qtpl:21
func (p *Error) StreamBody(qw422016 *qt422016.Writer) {
//line template/error.qtpl:21
	qw422016.N().S(` <div class="error"> <h1>`)
//line template/error.qtpl:23
	qw422016.E().V(p.Code)
//line template/error.qtpl:23
	qw422016.N().S(`</h1> <h2>`)
//line template/error.qtpl:24
	qw422016.E().S(p.Message)
//line template/error.qtpl:24
	qw422016.N().S(`</h2> </div> `)
//line template/error.qtpl:26
}

//line template/error.qtpl:26
func (p *Error) WriteBody(qq422016 qtio422016.Writer) {
//line template/error.qtpl:26
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template/error.qtpl:26
	p.StreamBody(qw422016)
//line template/error.qtpl:26
	qt422016.ReleaseWriter(qw422016)
//line template/error.qtpl:26
}

//line template/error.qtpl:26
func (p *Error) Body() string {
//line template/error.qtpl:26
	qb422016 := qt422016.AcquireByteBuffer()
//line template/error.qtpl:26
	p.WriteBody(qb422016)
//line template/error.qtpl:26
	qs422016 := string(qb422016.B)
//line template/error.qtpl:26
	qt422016.ReleaseByteBuffer(qb422016)
//line template/error.qtpl:26
	return qs422016
//line template/error.qtpl:26
}
