// This file is automatically generated by qtc from "page.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line template/page.qtpl:2
package template

//line template/page.qtpl:2
import (
	"regexp"
	"strings"
)

//line template/page.qtpl:9
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line template/page.qtpl:9
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line template/page.qtpl:9
type page interface {
	//line template/page.qtpl:9
	Title() string
	//line template/page.qtpl:9
	StreamTitle(qw422016 *qt422016.Writer)
	//line template/page.qtpl:9
	WriteTitle(qq422016 qtio422016.Writer)
	//line template/page.qtpl:9
	Styles() string
	//line template/page.qtpl:9
	StreamStyles(qw422016 *qt422016.Writer)
	//line template/page.qtpl:9
	WriteStyles(qq422016 qtio422016.Writer)
	//line template/page.qtpl:9
	Body() string
	//line template/page.qtpl:9
	StreamBody(qw422016 *qt422016.Writer)
	//line template/page.qtpl:9
	WriteBody(qq422016 qtio422016.Writer)
	//line template/page.qtpl:9
	Footer() string
	//line template/page.qtpl:9
	StreamFooter(qw422016 *qt422016.Writer)
	//line template/page.qtpl:9
	WriteFooter(qq422016 qtio422016.Writer)
//line template/page.qtpl:9
}

//line template/page.qtpl:21
type Page struct {
	URI string
}

//line template/page.qtpl:27
func StreamRender(qw422016 *qt422016.Writer, p page) {
	//line template/page.qtpl:27
	qw422016.N().S(` <!DOCTYPE HTML> <html lang="en"> <head> <meta charset="utf-8"> <meta content="width=device-width, initial-scale=1" name="viewport"> <title>`)
	//line template/page.qtpl:33
	p.StreamTitle(qw422016)
	//line template/page.qtpl:33
	qw422016.N().S(`</title> `)
	//line template/page.qtpl:34
	p.StreamStyles(qw422016)
	//line template/page.qtpl:34
	qw422016.N().S(` </head> <body>`)
	//line template/page.qtpl:36
	p.StreamBody(qw422016)
	//line template/page.qtpl:36
	qw422016.N().S(`</body> <footer>`)
	//line template/page.qtpl:37
	p.StreamFooter(qw422016)
	//line template/page.qtpl:37
	qw422016.N().S(`</footer> </html> `)
//line template/page.qtpl:39
}

//line template/page.qtpl:39
func WriteRender(qq422016 qtio422016.Writer, p page) {
	//line template/page.qtpl:39
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line template/page.qtpl:39
	StreamRender(qw422016, p)
	//line template/page.qtpl:39
	qt422016.ReleaseWriter(qw422016)
//line template/page.qtpl:39
}

//line template/page.qtpl:39
func Render(p page) string {
	//line template/page.qtpl:39
	qb422016 := qt422016.AcquireByteBuffer()
	//line template/page.qtpl:39
	WriteRender(qb422016, p)
	//line template/page.qtpl:39
	qs422016 := string(qb422016.B)
	//line template/page.qtpl:39
	qt422016.ReleaseByteBuffer(qb422016)
	//line template/page.qtpl:39
	return qs422016
//line template/page.qtpl:39
}

//line template/page.qtpl:42
func StreamRenderLink(qw422016 *qt422016.Writer, href, uri string, classes ...string) {
	//line template/page.qtpl:42
	qw422016.N().S(`<a href="`)
	//line template/page.qtpl:43
	qw422016.E().S(href)
	//line template/page.qtpl:43
	qw422016.N().S(`" class="`)
	//line template/page.qtpl:43
	if href == uri {
		//line template/page.qtpl:43
		qw422016.N().S(`active`)
		//line template/page.qtpl:43
	}
	//line template/page.qtpl:43
	qw422016.E().S(strings.Join(classes, " "))
	//line template/page.qtpl:43
	qw422016.N().S(`">`)
//line template/page.qtpl:44
}

//line template/page.qtpl:44
func WriteRenderLink(qq422016 qtio422016.Writer, href, uri string, classes ...string) {
	//line template/page.qtpl:44
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line template/page.qtpl:44
	StreamRenderLink(qw422016, href, uri, classes...)
	//line template/page.qtpl:44
	qt422016.ReleaseWriter(qw422016)
//line template/page.qtpl:44
}

//line template/page.qtpl:44
func RenderLink(href, uri string, classes ...string) string {
	//line template/page.qtpl:44
	qb422016 := qt422016.AcquireByteBuffer()
	//line template/page.qtpl:44
	WriteRenderLink(qb422016, href, uri, classes...)
	//line template/page.qtpl:44
	qs422016 := string(qb422016.B)
	//line template/page.qtpl:44
	qt422016.ReleaseByteBuffer(qb422016)
	//line template/page.qtpl:44
	return qs422016
//line template/page.qtpl:44
}

//line template/page.qtpl:46
func StreamRenderLinkPattern(qw422016 *qt422016.Writer, href, pattern, uri string, classes ...string) {
	//line template/page.qtpl:46
	qw422016.N().S(`<a href="`)
	//line template/page.qtpl:47
	qw422016.E().S(href)
	//line template/page.qtpl:47
	qw422016.N().S(`" class="`)
	//line template/page.qtpl:47
	if matched, _ := regexp.Match(pattern, []byte(uri)); matched {
		//line template/page.qtpl:47
		qw422016.N().S(`active`)
		//line template/page.qtpl:47
	}
	//line template/page.qtpl:47
	qw422016.N().S(`">`)
//line template/page.qtpl:48
}

//line template/page.qtpl:48
func WriteRenderLinkPattern(qq422016 qtio422016.Writer, href, pattern, uri string, classes ...string) {
	//line template/page.qtpl:48
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line template/page.qtpl:48
	StreamRenderLinkPattern(qw422016, href, pattern, uri, classes...)
	//line template/page.qtpl:48
	qt422016.ReleaseWriter(qw422016)
//line template/page.qtpl:48
}

//line template/page.qtpl:48
func RenderLinkPattern(href, pattern, uri string, classes ...string) string {
	//line template/page.qtpl:48
	qb422016 := qt422016.AcquireByteBuffer()
	//line template/page.qtpl:48
	WriteRenderLinkPattern(qb422016, href, pattern, uri, classes...)
	//line template/page.qtpl:48
	qs422016 := string(qb422016.B)
	//line template/page.qtpl:48
	qt422016.ReleaseByteBuffer(qb422016)
	//line template/page.qtpl:48
	return qs422016
//line template/page.qtpl:48
}

//line template/page.qtpl:50
func StreamRenderCode(qw422016 *qt422016.Writer, code string) {
	//line template/page.qtpl:52
	lines := strings.Split(code, "\n")

	//line template/page.qtpl:54
	for i, l := range lines {
		//line template/page.qtpl:54
		qw422016.N().S(`<code id="line-`)
		//line template/page.qtpl:55
		qw422016.E().V(i + 1)
		//line template/page.qtpl:55
		qw422016.N().S(`"><a href="#line-`)
		//line template/page.qtpl:56
		qw422016.E().V(i + 1)
		//line template/page.qtpl:56
		qw422016.N().S(`">`)
		//line template/page.qtpl:56
		qw422016.E().V(i + 1)
		//line template/page.qtpl:56
		qw422016.N().S(`</a><span>`)
		//line template/page.qtpl:57
		qw422016.E().S(l)
		//line template/page.qtpl:57
		qw422016.N().S(`</span></code>`)
		//line template/page.qtpl:59
	}
//line template/page.qtpl:60
}

//line template/page.qtpl:60
func WriteRenderCode(qq422016 qtio422016.Writer, code string) {
	//line template/page.qtpl:60
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line template/page.qtpl:60
	StreamRenderCode(qw422016, code)
	//line template/page.qtpl:60
	qt422016.ReleaseWriter(qw422016)
//line template/page.qtpl:60
}

//line template/page.qtpl:60
func RenderCode(code string) string {
	//line template/page.qtpl:60
	qb422016 := qt422016.AcquireByteBuffer()
	//line template/page.qtpl:60
	WriteRenderCode(qb422016, code)
	//line template/page.qtpl:60
	qs422016 := string(qb422016.B)
	//line template/page.qtpl:60
	qt422016.ReleaseByteBuffer(qb422016)
	//line template/page.qtpl:60
	return qs422016
//line template/page.qtpl:60
}

//line template/page.qtpl:63
func (p *Page) StreamTitle(qw422016 *qt422016.Writer) {
	//line template/page.qtpl:63
	qw422016.N().S(` Thrall `)
//line template/page.qtpl:65
}

//line template/page.qtpl:65
func (p *Page) WriteTitle(qq422016 qtio422016.Writer) {
	//line template/page.qtpl:65
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line template/page.qtpl:65
	p.StreamTitle(qw422016)
	//line template/page.qtpl:65
	qt422016.ReleaseWriter(qw422016)
//line template/page.qtpl:65
}

//line template/page.qtpl:65
func (p *Page) Title() string {
	//line template/page.qtpl:65
	qb422016 := qt422016.AcquireByteBuffer()
	//line template/page.qtpl:65
	p.WriteTitle(qb422016)
	//line template/page.qtpl:65
	qs422016 := string(qb422016.B)
	//line template/page.qtpl:65
	qt422016.ReleaseByteBuffer(qb422016)
	//line template/page.qtpl:65
	return qs422016
//line template/page.qtpl:65
}

//line template/page.qtpl:67
func (p *Page) StreamStyles(qw422016 *qt422016.Writer) {
	//line template/page.qtpl:67
	qw422016.N().S(` <link rel="stylesheet" type="text/css" href="/assets/css/main.css"> `)
//line template/page.qtpl:69
}

//line template/page.qtpl:69
func (p *Page) WriteStyles(qq422016 qtio422016.Writer) {
	//line template/page.qtpl:69
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line template/page.qtpl:69
	p.StreamStyles(qw422016)
	//line template/page.qtpl:69
	qt422016.ReleaseWriter(qw422016)
//line template/page.qtpl:69
}

//line template/page.qtpl:69
func (p *Page) Styles() string {
	//line template/page.qtpl:69
	qb422016 := qt422016.AcquireByteBuffer()
	//line template/page.qtpl:69
	p.WriteStyles(qb422016)
	//line template/page.qtpl:69
	qs422016 := string(qb422016.B)
	//line template/page.qtpl:69
	qt422016.ReleaseByteBuffer(qb422016)
	//line template/page.qtpl:69
	return qs422016
//line template/page.qtpl:69
}

//line template/page.qtpl:71
func (p *Page) StreamBody(qw422016 *qt422016.Writer) {
	//line template/page.qtpl:71
	qw422016.N().S(` `)
//line template/page.qtpl:72
}

//line template/page.qtpl:72
func (p *Page) WriteBody(qq422016 qtio422016.Writer) {
	//line template/page.qtpl:72
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line template/page.qtpl:72
	p.StreamBody(qw422016)
	//line template/page.qtpl:72
	qt422016.ReleaseWriter(qw422016)
//line template/page.qtpl:72
}

//line template/page.qtpl:72
func (p *Page) Body() string {
	//line template/page.qtpl:72
	qb422016 := qt422016.AcquireByteBuffer()
	//line template/page.qtpl:72
	p.WriteBody(qb422016)
	//line template/page.qtpl:72
	qs422016 := string(qb422016.B)
	//line template/page.qtpl:72
	qt422016.ReleaseByteBuffer(qb422016)
	//line template/page.qtpl:72
	return qs422016
//line template/page.qtpl:72
}

//line template/page.qtpl:74
func (p *Page) StreamFooter(qw422016 *qt422016.Writer) {
	//line template/page.qtpl:74
	qw422016.N().S(` `)
//line template/page.qtpl:75
}

//line template/page.qtpl:75
func (p *Page) WriteFooter(qq422016 qtio422016.Writer) {
	//line template/page.qtpl:75
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line template/page.qtpl:75
	p.StreamFooter(qw422016)
	//line template/page.qtpl:75
	qt422016.ReleaseWriter(qw422016)
//line template/page.qtpl:75
}

//line template/page.qtpl:75
func (p *Page) Footer() string {
	//line template/page.qtpl:75
	qb422016 := qt422016.AcquireByteBuffer()
	//line template/page.qtpl:75
	p.WriteFooter(qb422016)
	//line template/page.qtpl:75
	qs422016 := string(qb422016.B)
	//line template/page.qtpl:75
	qt422016.ReleaseByteBuffer(qb422016)
	//line template/page.qtpl:75
	return qs422016
//line template/page.qtpl:75
}
