// This file is automatically generated by qtc from "render.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line template/render.qtpl:2
package template

//line template/render.qtpl:2
import (
	"fmt"
	"strings"

	"github.com/andrewpillar/thrall/runner"
)

//line template/render.qtpl:10
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line template/render.qtpl:10
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line template/render.qtpl:11
func RenderSize(n int64) string {
	units := []string{"B", "KB", "MB", "GB", "TB", "PB"}
	i := 0

	for ; n > 1024; i++ {
		n /= 1024
	}

	return fmt.Sprintf("%d %s", n, units[i])
}

//line template/render.qtpl:25
func StreamRenderCode(qw422016 *qt422016.Writer, c string) {
	//line template/render.qtpl:27
	lines := strings.Split(c, "\n")

	//line template/render.qtpl:28
	qw422016.N().S(`<div class="code-wrap"><table class="code"><tbody>`)
	//line template/render.qtpl:32
	for i, l := range lines {
		//line template/render.qtpl:32
		qw422016.N().S(`<tr><td class="line-number"><a href="#L`)
		//line template/render.qtpl:34
		qw422016.E().V(i + 1)
		//line template/render.qtpl:34
		qw422016.N().S(`">`)
		//line template/render.qtpl:34
		qw422016.E().V(i + 1)
		//line template/render.qtpl:34
		qw422016.N().S(`</a></td><td id="L`)
		//line template/render.qtpl:35
		qw422016.E().V(i + 1)
		//line template/render.qtpl:35
		qw422016.N().S(`" class="line">`)
		//line template/render.qtpl:35
		qw422016.E().S(l)
		//line template/render.qtpl:35
		qw422016.N().S(`</td></tr>`)
		//line template/render.qtpl:37
	}
	//line template/render.qtpl:37
	qw422016.N().S(`</tbody></table></div>`)
//line template/render.qtpl:41
}

//line template/render.qtpl:41
func WriteRenderCode(qq422016 qtio422016.Writer, c string) {
	//line template/render.qtpl:41
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line template/render.qtpl:41
	StreamRenderCode(qw422016, c)
	//line template/render.qtpl:41
	qt422016.ReleaseWriter(qw422016)
//line template/render.qtpl:41
}

//line template/render.qtpl:41
func RenderCode(c string) string {
	//line template/render.qtpl:41
	qb422016 := qt422016.AcquireByteBuffer()
	//line template/render.qtpl:41
	WriteRenderCode(qb422016, c)
	//line template/render.qtpl:41
	qs422016 := string(qb422016.B)
	//line template/render.qtpl:41
	qt422016.ReleaseByteBuffer(qb422016)
	//line template/render.qtpl:41
	return qs422016
//line template/render.qtpl:41
}

//line template/render.qtpl:44
func StreamRenderSearch(qw422016 *qt422016.Writer, uri, search, prompt string) {
	//line template/render.qtpl:44
	qw422016.N().S(` <form class="form-field form-search"> <input type="text" name="search" class="form-text" placeholder="`)
	//line template/render.qtpl:46
	qw422016.E().S(prompt)
	//line template/render.qtpl:46
	qw422016.N().S(`" autocomplete="off" value="`)
	//line template/render.qtpl:46
	qw422016.E().S(search)
	//line template/render.qtpl:46
	qw422016.N().S(`"/> `)
	//line template/render.qtpl:47
	if search != "" {
		//line template/render.qtpl:47
		qw422016.N().S(` <a class="muted" href="`)
		//line template/render.qtpl:48
		qw422016.E().S(uri)
		//line template/render.qtpl:48
		qw422016.N().S(`">`)
		//line template/render.qtpl:48
		qw422016.N().S(`<!-- Generated by IcoMoon.io -->
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
<path d="M18.984 6.422l-5.578 5.578 5.578 5.578-1.406 1.406-5.578-5.578-5.578 5.578-1.406-1.406 5.578-5.578-5.578-5.578 1.406-1.406 5.578 5.578 5.578-5.578z"></path>
</svg>
`)
		//line template/render.qtpl:48
		qw422016.N().S(`</a> `)
		//line template/render.qtpl:49
	}
	//line template/render.qtpl:49
	qw422016.N().S(` </form> `)
//line template/render.qtpl:51
}

//line template/render.qtpl:51
func WriteRenderSearch(qq422016 qtio422016.Writer, uri, search, prompt string) {
	//line template/render.qtpl:51
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line template/render.qtpl:51
	StreamRenderSearch(qw422016, uri, search, prompt)
	//line template/render.qtpl:51
	qt422016.ReleaseWriter(qw422016)
//line template/render.qtpl:51
}

//line template/render.qtpl:51
func RenderSearch(uri, search, prompt string) string {
	//line template/render.qtpl:51
	qb422016 := qt422016.AcquireByteBuffer()
	//line template/render.qtpl:51
	WriteRenderSearch(qb422016, uri, search, prompt)
	//line template/render.qtpl:51
	qs422016 := string(qb422016.B)
	//line template/render.qtpl:51
	qt422016.ReleaseByteBuffer(qb422016)
	//line template/render.qtpl:51
	return qs422016
//line template/render.qtpl:51
}

//line template/render.qtpl:53
func StreamRenderStatus(qw422016 *qt422016.Writer, s runner.Status) {
	//line template/render.qtpl:53
	qw422016.N().S(` `)
	//line template/render.qtpl:54
	switch s {
	//line template/render.qtpl:55
	case runner.Queued:
		//line template/render.qtpl:55
		qw422016.N().S(` <span class="pill w-90 pill-dark">`)
		//line template/render.qtpl:56
		qw422016.N().S(`<!-- Generated by IcoMoon.io -->
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
<path d="M12 11.484l3.984-3.984v-3.516h-7.969v3.516zM15.984 16.5l-3.984-3.984-3.984 3.984v3.516h7.969v-3.516zM6 2.016h12v6l-3.984 3.984 3.984 3.984v6h-12v-6l3.984-3.984-3.984-3.984v-6z"></path>
</svg>
`)
		//line template/render.qtpl:56
		qw422016.N().S(` Queued</span> `)
	//line template/render.qtpl:57
	case runner.Running:
		//line template/render.qtpl:57
		qw422016.N().S(` <span class="pill w-90 pill-blue">`)
		//line template/render.qtpl:58
		qw422016.N().S(`<!-- Generated by IcoMoon.io -->
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
<path d="M21.984 12c0 5.156-3.938 9.422-8.953 9.938v-2.016c3.938-0.516 6.984-3.891 6.984-7.922s-3.047-7.406-6.984-7.922v-2.016c5.016 0.516 8.953 4.781 8.953 9.938zM5.672 19.734l1.406-1.406c1.125 0.844 2.484 1.406 3.938 1.594v2.016c-2.016-0.188-3.844-0.984-5.344-2.203zM4.078 12.984c0.188 1.453 0.75 2.813 1.594 3.891l-1.406 1.453c-1.219-1.5-2.016-3.328-2.203-5.344h2.016zM5.672 7.078c-0.844 1.125-1.406 2.484-1.594 3.938h-2.016c0.188-2.016 0.984-3.844 2.203-5.344zM11.016 4.078c-1.453 0.188-2.813 0.75-3.938 1.594l-1.406-1.406c1.5-1.219 3.328-2.016 5.344-2.203v2.016zM13.031 9.797l2.953 2.203c-2.007 1.493-4.007 2.993-6 4.5z"></path>
</svg>
`)
		//line template/render.qtpl:58
		qw422016.N().S(` Running</span> `)
	//line template/render.qtpl:59
	case runner.Passed:
		//line template/render.qtpl:59
		qw422016.N().S(` <span class="pill w-90 pill-green">`)
		//line template/render.qtpl:60
		qw422016.N().S(`<!-- Generated by IcoMoon.io -->
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
<path d="M9 16.172l10.594-10.594 1.406 1.406-12 12-5.578-5.578 1.406-1.406z"></path>
</svg>
`)
		//line template/render.qtpl:60
		qw422016.N().S(` Passed</span> `)
	//line template/render.qtpl:61
	case runner.PassedWithFailures:
		//line template/render.qtpl:61
		qw422016.N().S(` <span class="pill w-90 pill-orange">`)
		//line template/render.qtpl:62
		qw422016.N().S(`<!-- Generated by IcoMoon.io -->
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
<path d="M12.984 14.016v-4.031h-1.969v4.031h1.969zM12.984 18v-2.016h-1.969v2.016h1.969zM0.984 21l11.016-18.984 11.016 18.984h-22.031z"></path>
</svg>
`)
		//line template/render.qtpl:62
		qw422016.N().S(` Passed</span> `)
	//line template/render.qtpl:63
	case runner.Failed:
		//line template/render.qtpl:63
		qw422016.N().S(` <span class="pill w-90 pill-red">`)
		//line template/render.qtpl:64
		qw422016.N().S(`<!-- Generated by IcoMoon.io -->
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
<path d="M18.984 6.422l-5.578 5.578 5.578 5.578-1.406 1.406-5.578-5.578-5.578 5.578-1.406-1.406 5.578-5.578-5.578-5.578 1.406-1.406 5.578 5.578 5.578-5.578z"></path>
</svg>
`)
		//line template/render.qtpl:64
		qw422016.N().S(` Failed</span> `)
	//line template/render.qtpl:65
	case runner.Killed:
		//line template/render.qtpl:65
		qw422016.N().S(` <span class="pill w-90 pill-red">`)
		//line template/render.qtpl:66
		qw422016.N().S(`<!-- Generated by IcoMoon.io -->
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
<path d="M12.984 12.984v-6h-1.969v6h1.969zM12 17.297c0.703 0 1.313-0.609 1.313-1.313s-0.609-1.266-1.313-1.266-1.313 0.563-1.313 1.266 0.609 1.313 1.313 1.313zM15.75 3l5.25 5.25v7.5l-5.25 5.25h-7.5l-5.25-5.25v-7.5l5.25-5.25h7.5z"></path>
</svg>
`)
		//line template/render.qtpl:66
		qw422016.N().S(` Killed</span> `)
	//line template/render.qtpl:67
	case runner.TimedOut:
		//line template/render.qtpl:67
		qw422016.N().S(` <span class="pill w-90 pill-gray">`)
		//line template/render.qtpl:68
		qw422016.N().S(`<!-- Generated by IcoMoon.io -->
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
<path d="M12 20.016c3.891 0 6.984-3.141 6.984-7.031s-3.094-6.984-6.984-6.984-6.984 3.094-6.984 6.984 3.094 7.031 6.984 7.031zM19.031 7.406c1.219 1.547 1.969 3.469 1.969 5.578 0 4.969-4.031 9-9 9s-9-4.031-9-9 4.031-9 9-9c2.109 0 4.078 0.797 5.625 2.016l1.406-1.453c0.516 0.422 0.984 0.891 1.406 1.406zM11.016 14.016v-6h1.969v6h-1.969zM15 0.984v2.016h-6v-2.016h6z"></path>
</svg>
`)
		//line template/render.qtpl:68
		qw422016.N().S(` Timed Out</span> `)
		//line template/render.qtpl:69
	}
	//line template/render.qtpl:69
	qw422016.N().S(` `)
//line template/render.qtpl:70
}

//line template/render.qtpl:70
func WriteRenderStatus(qq422016 qtio422016.Writer, s runner.Status) {
	//line template/render.qtpl:70
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line template/render.qtpl:70
	StreamRenderStatus(qw422016, s)
	//line template/render.qtpl:70
	qt422016.ReleaseWriter(qw422016)
//line template/render.qtpl:70
}

//line template/render.qtpl:70
func RenderStatus(s runner.Status) string {
	//line template/render.qtpl:70
	qb422016 := qt422016.AcquireByteBuffer()
	//line template/render.qtpl:70
	WriteRenderStatus(qb422016, s)
	//line template/render.qtpl:70
	qs422016 := string(qb422016.B)
	//line template/render.qtpl:70
	qt422016.ReleaseByteBuffer(qb422016)
	//line template/render.qtpl:70
	return qs422016
//line template/render.qtpl:70
}
