// Code generated by qtc from "repo_index.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line template/repo_index.qtpl:2
package template

//line template/repo_index.qtpl:2
import (
	"djinn-ci.com/provider"
	"djinn-ci.com/template/form"
)

//line template/repo_index.qtpl:8
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line template/repo_index.qtpl:8
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line template/repo_index.qtpl:9
type RepoIndex struct {
	*Paginator

	Repos     []*provider.Repo
	Provider  *provider.Provider
	Providers []*provider.Provider
}

//line template/repo_index.qtpl:19
func (p *RepoIndex) StreamTitle(qw422016 *qt422016.Writer) {
//line template/repo_index.qtpl:19
	qw422016.N().S(`Repositories`)
//line template/repo_index.qtpl:19
}

//line template/repo_index.qtpl:19
func (p *RepoIndex) WriteTitle(qq422016 qtio422016.Writer) {
//line template/repo_index.qtpl:19
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template/repo_index.qtpl:19
	p.StreamTitle(qw422016)
//line template/repo_index.qtpl:19
	qt422016.ReleaseWriter(qw422016)
//line template/repo_index.qtpl:19
}

//line template/repo_index.qtpl:19
func (p *RepoIndex) Title() string {
//line template/repo_index.qtpl:19
	qb422016 := qt422016.AcquireByteBuffer()
//line template/repo_index.qtpl:19
	p.WriteTitle(qb422016)
//line template/repo_index.qtpl:19
	qs422016 := string(qb422016.B)
//line template/repo_index.qtpl:19
	qt422016.ReleaseByteBuffer(qb422016)
//line template/repo_index.qtpl:19
	return qs422016
//line template/repo_index.qtpl:19
}

//line template/repo_index.qtpl:20
func (p *RepoIndex) StreamHeader(qw422016 *qt422016.Writer) {
//line template/repo_index.qtpl:20
	p.StreamTitle(qw422016)
//line template/repo_index.qtpl:20
}

//line template/repo_index.qtpl:20
func (p *RepoIndex) WriteHeader(qq422016 qtio422016.Writer) {
//line template/repo_index.qtpl:20
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template/repo_index.qtpl:20
	p.StreamHeader(qw422016)
//line template/repo_index.qtpl:20
	qt422016.ReleaseWriter(qw422016)
//line template/repo_index.qtpl:20
}

//line template/repo_index.qtpl:20
func (p *RepoIndex) Header() string {
//line template/repo_index.qtpl:20
	qb422016 := qt422016.AcquireByteBuffer()
//line template/repo_index.qtpl:20
	p.WriteHeader(qb422016)
//line template/repo_index.qtpl:20
	qs422016 := string(qb422016.B)
//line template/repo_index.qtpl:20
	qt422016.ReleaseByteBuffer(qb422016)
//line template/repo_index.qtpl:20
	return qs422016
//line template/repo_index.qtpl:20
}

//line template/repo_index.qtpl:21
func (p *RepoIndex) StreamNavigation(qw422016 *qt422016.Writer) {
//line template/repo_index.qtpl:21
}

//line template/repo_index.qtpl:21
func (p *RepoIndex) WriteNavigation(qq422016 qtio422016.Writer) {
//line template/repo_index.qtpl:21
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template/repo_index.qtpl:21
	p.StreamNavigation(qw422016)
//line template/repo_index.qtpl:21
	qt422016.ReleaseWriter(qw422016)
//line template/repo_index.qtpl:21
}

//line template/repo_index.qtpl:21
func (p *RepoIndex) Navigation() string {
//line template/repo_index.qtpl:21
	qb422016 := qt422016.AcquireByteBuffer()
//line template/repo_index.qtpl:21
	p.WriteNavigation(qb422016)
//line template/repo_index.qtpl:21
	qs422016 := string(qb422016.B)
//line template/repo_index.qtpl:21
	qt422016.ReleaseByteBuffer(qb422016)
//line template/repo_index.qtpl:21
	return qs422016
//line template/repo_index.qtpl:21
}

//line template/repo_index.qtpl:22
func (p *RepoIndex) StreamFooter(qw422016 *qt422016.Writer) {
//line template/repo_index.qtpl:22
}

//line template/repo_index.qtpl:22
func (p *RepoIndex) WriteFooter(qq422016 qtio422016.Writer) {
//line template/repo_index.qtpl:22
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template/repo_index.qtpl:22
	p.StreamFooter(qw422016)
//line template/repo_index.qtpl:22
	qt422016.ReleaseWriter(qw422016)
//line template/repo_index.qtpl:22
}

//line template/repo_index.qtpl:22
func (p *RepoIndex) Footer() string {
//line template/repo_index.qtpl:22
	qb422016 := qt422016.AcquireByteBuffer()
//line template/repo_index.qtpl:22
	p.WriteFooter(qb422016)
//line template/repo_index.qtpl:22
	qs422016 := string(qb422016.B)
//line template/repo_index.qtpl:22
	qt422016.ReleaseByteBuffer(qb422016)
//line template/repo_index.qtpl:22
	return qs422016
//line template/repo_index.qtpl:22
}

//line template/repo_index.qtpl:24
func (p *RepoIndex) StreamActions(qw422016 *qt422016.Writer) {
//line template/repo_index.qtpl:24
	qw422016.N().S(` `)
//line template/repo_index.qtpl:25
	if p.Provider != nil && p.Provider.Connected {
//line template/repo_index.qtpl:25
		qw422016.N().S(` <form method="POST" action="/repos/reload?provider=`)
//line template/repo_index.qtpl:26
		qw422016.E().S(p.Provider.Name)
//line template/repo_index.qtpl:26
		qw422016.N().S(`&page=`)
//line template/repo_index.qtpl:26
		qw422016.E().V(p.Paginator.Page)
//line template/repo_index.qtpl:26
		qw422016.N().S(`"> `)
//line template/repo_index.qtpl:27
		form.StreamMethod(qw422016, "PATCH")
//line template/repo_index.qtpl:27
		qw422016.N().S(` `)
//line template/repo_index.qtpl:28
		qw422016.N().V(p.CSRF)
//line template/repo_index.qtpl:28
		qw422016.N().S(` <button type="submit" class="btn btn-primary">Reload</button> </form> `)
//line template/repo_index.qtpl:31
	}
//line template/repo_index.qtpl:31
	qw422016.N().S(` `)
//line template/repo_index.qtpl:32
}

//line template/repo_index.qtpl:32
func (p *RepoIndex) WriteActions(qq422016 qtio422016.Writer) {
//line template/repo_index.qtpl:32
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template/repo_index.qtpl:32
	p.StreamActions(qw422016)
//line template/repo_index.qtpl:32
	qt422016.ReleaseWriter(qw422016)
//line template/repo_index.qtpl:32
}

//line template/repo_index.qtpl:32
func (p *RepoIndex) Actions() string {
//line template/repo_index.qtpl:32
	qb422016 := qt422016.AcquireByteBuffer()
//line template/repo_index.qtpl:32
	p.WriteActions(qb422016)
//line template/repo_index.qtpl:32
	qs422016 := string(qb422016.B)
//line template/repo_index.qtpl:32
	qt422016.ReleaseByteBuffer(qb422016)
//line template/repo_index.qtpl:32
	return qs422016
//line template/repo_index.qtpl:32
}

//line template/repo_index.qtpl:34
func (p *RepoIndex) streamrenderProviders(qw422016 *qt422016.Writer) {
//line template/repo_index.qtpl:34
	qw422016.N().S(` `)
//line template/repo_index.qtpl:35
	qw422016.N().S(`<ul class="panel-nav">`)
//line template/repo_index.qtpl:37
	for _, prv := range p.Providers {
//line template/repo_index.qtpl:37
		qw422016.N().S(`<li>`)
//line template/repo_index.qtpl:39
		if p.Provider.Name == prv.Name {
//line template/repo_index.qtpl:39
			qw422016.N().S(`<a class="active" href="`)
//line template/repo_index.qtpl:40
			qw422016.E().S(p.URL.Path)
//line template/repo_index.qtpl:40
			qw422016.N().S(`?provider=`)
//line template/repo_index.qtpl:40
			qw422016.E().S(prv.Name)
//line template/repo_index.qtpl:40
			qw422016.N().S(`">`)
//line template/repo_index.qtpl:40
			qw422016.E().S(providerNames[prv.Name])
//line template/repo_index.qtpl:40
			qw422016.N().S(`</a>`)
//line template/repo_index.qtpl:41
		} else {
//line template/repo_index.qtpl:41
			qw422016.N().S(`<a href="`)
//line template/repo_index.qtpl:42
			qw422016.E().S(p.URL.Path)
//line template/repo_index.qtpl:42
			qw422016.N().S(`?provider=`)
//line template/repo_index.qtpl:42
			qw422016.E().S(prv.Name)
//line template/repo_index.qtpl:42
			qw422016.N().S(`">`)
//line template/repo_index.qtpl:42
			qw422016.E().S(providerNames[prv.Name])
//line template/repo_index.qtpl:42
			qw422016.N().S(`</a>`)
//line template/repo_index.qtpl:43
		}
//line template/repo_index.qtpl:43
		qw422016.N().S(`</li>`)
//line template/repo_index.qtpl:45
	}
//line template/repo_index.qtpl:45
	qw422016.N().S(`</ul>`)
//line template/repo_index.qtpl:47
	qw422016.N().S(` `)
//line template/repo_index.qtpl:48
}

//line template/repo_index.qtpl:48
func (p *RepoIndex) writerenderProviders(qq422016 qtio422016.Writer) {
//line template/repo_index.qtpl:48
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template/repo_index.qtpl:48
	p.streamrenderProviders(qw422016)
//line template/repo_index.qtpl:48
	qt422016.ReleaseWriter(qw422016)
//line template/repo_index.qtpl:48
}

//line template/repo_index.qtpl:48
func (p *RepoIndex) renderProviders() string {
//line template/repo_index.qtpl:48
	qb422016 := qt422016.AcquireByteBuffer()
//line template/repo_index.qtpl:48
	p.writerenderProviders(qb422016)
//line template/repo_index.qtpl:48
	qs422016 := string(qb422016.B)
//line template/repo_index.qtpl:48
	qt422016.ReleaseByteBuffer(qb422016)
//line template/repo_index.qtpl:48
	return qs422016
//line template/repo_index.qtpl:48
}

//line template/repo_index.qtpl:50
func (p *RepoIndex) streamrenderRepoItem(qw422016 *qt422016.Writer, r *provider.Repo) {
//line template/repo_index.qtpl:50
	qw422016.N().S(` <tr> <td> <span class="muted"> `)
//line template/repo_index.qtpl:54
	switch r.Provider.Name {
//line template/repo_index.qtpl:55
	case "github":
//line template/repo_index.qtpl:55
		qw422016.N().S(` `)
//line template/repo_index.qtpl:56
		qw422016.N().S(`<!-- Generated by IcoMoon.io -->
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
<path d="M12 0.297c-6.63 0-12 5.373-12 12 0 5.303 3.438 9.8 8.205 11.385 0.6 0.113 0.82-0.258 0.82-0.577 0-0.285-0.010-1.040-0.015-2.040-3.338 0.724-4.042-1.61-4.042-1.61-0.546-1.385-1.335-1.755-1.335-1.755-1.087-0.744 0.084-0.729 0.084-0.729 1.205 0.084 1.838 1.236 1.838 1.236 1.070 1.835 2.809 1.305 3.495 0.998 0.108-0.776 0.417-1.305 0.76-1.605-2.665-0.3-5.466-1.332-5.466-5.93 0-1.31 0.465-2.38 1.235-3.22-0.135-0.303-0.54-1.523 0.105-3.176 0 0 1.005-0.322 3.3 1.23 0.96-0.267 1.98-0.399 3-0.405 1.020 0.006 2.040 0.138 3 0.405 2.28-1.552 3.285-1.23 3.285-1.23 0.645 1.653 0.24 2.873 0.12 3.176 0.765 0.84 1.23 1.91 1.23 3.22 0 4.61-2.805 5.625-5.475 5.92 0.42 0.36 0.81 1.096 0.81 2.22 0 1.606-0.015 2.896-0.015 3.286 0 0.315 0.21 0.69 0.825 0.57 4.801-1.574 8.236-6.074 8.236-11.369 0-6.627-5.373-12-12-12z"></path>
</svg>
`)
//line template/repo_index.qtpl:56
		qw422016.N().S(` `)
//line template/repo_index.qtpl:57
	case "gitlab":
//line template/repo_index.qtpl:57
		qw422016.N().S(` `)
//line template/repo_index.qtpl:58
		qw422016.N().S(`<!-- Generated by IcoMoon.io -->
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
<path d="M23.955 13.587l-1.342-4.135-2.664-8.189c-0.135-0.423-0.73-0.423-0.867 0l-2.664 8.187h-8.836l-2.663-8.187c-0.136-0.423-0.734-0.423-0.869-0.003l-2.664 8.189-1.342 4.138c-0.121 0.375 0.014 0.789 0.331 1.023l11.625 8.444 11.625-8.443c0.318-0.235 0.453-0.647 0.33-1.024z"></path>
</svg>
`)
//line template/repo_index.qtpl:58
		qw422016.N().S(` `)
//line template/repo_index.qtpl:59
	}
//line template/repo_index.qtpl:59
	qw422016.N().S(` </span> <a href="`)
//line template/repo_index.qtpl:61
	qw422016.E().S(r.Href)
//line template/repo_index.qtpl:61
	qw422016.N().S(`" target="_blank">`)
//line template/repo_index.qtpl:61
	qw422016.E().S(r.Name)
//line template/repo_index.qtpl:61
	qw422016.N().S(`</a> </td> `)
//line template/repo_index.qtpl:63
	if !r.Provider.Connected {
//line template/repo_index.qtpl:63
		qw422016.N().S(` <td class="warning"> `)
//line template/repo_index.qtpl:65
		qw422016.N().S(`<!-- Generated by IcoMoon.io -->
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
<path d="M12.984 14.016v-4.031h-1.969v4.031h1.969zM12.984 18v-2.016h-1.969v2.016h1.969zM0.984 21l11.016-18.984 11.016 18.984h-22.031z"></path>
</svg>
`)
//line template/repo_index.qtpl:65
		qw422016.N().S(` Disconnected from `)
//line template/repo_index.qtpl:65
		qw422016.E().S(providerNames[r.Provider.Name])
//line template/repo_index.qtpl:65
		qw422016.N().S(` </td> `)
//line template/repo_index.qtpl:67
	} else {
//line template/repo_index.qtpl:67
		qw422016.N().S(` <td></td> `)
//line template/repo_index.qtpl:69
	}
//line template/repo_index.qtpl:69
	qw422016.N().S(` <td class="align-right"> `)
//line template/repo_index.qtpl:71
	if !r.Enabled {
//line template/repo_index.qtpl:71
		qw422016.N().S(` <form method="POST" action="/repos/enable"> `)
//line template/repo_index.qtpl:73
		qw422016.N().V(p.CSRF)
//line template/repo_index.qtpl:73
		qw422016.N().S(` <input type="hidden" name="provider_id" value="`)
//line template/repo_index.qtpl:74
		qw422016.E().V(r.ProviderID)
//line template/repo_index.qtpl:74
		qw422016.N().S(`"> <input type="hidden" name="repo_id" value="`)
//line template/repo_index.qtpl:75
		qw422016.E().V(r.RepoID)
//line template/repo_index.qtpl:75
		qw422016.N().S(`"> <input type="hidden" name="name" value="`)
//line template/repo_index.qtpl:76
		qw422016.E().S(r.Name)
//line template/repo_index.qtpl:76
		qw422016.N().S(`"> <input type="hidden" name="href" value="`)
//line template/repo_index.qtpl:77
		qw422016.E().S(r.Href)
//line template/repo_index.qtpl:77
		qw422016.N().S(`"> <button type="submit" class="btn btn-primary" `)
//line template/repo_index.qtpl:78
		if !r.Provider.Connected {
//line template/repo_index.qtpl:78
			qw422016.N().S(`disabled="true"`)
//line template/repo_index.qtpl:78
		}
//line template/repo_index.qtpl:78
		qw422016.N().S(`> Enable </button> </form> `)
//line template/repo_index.qtpl:82
	} else {
//line template/repo_index.qtpl:82
		qw422016.N().S(` <form method="POST" action="/repos/enable/`)
//line template/repo_index.qtpl:83
		qw422016.E().V(r.ID)
//line template/repo_index.qtpl:83
		qw422016.N().S(`"> `)
//line template/repo_index.qtpl:84
		form.StreamMethod(qw422016, "DELETE")
//line template/repo_index.qtpl:84
		qw422016.N().S(` `)
//line template/repo_index.qtpl:85
		qw422016.N().V(p.CSRF)
//line template/repo_index.qtpl:85
		qw422016.N().S(` <button type="submit" class="btn btn-danger" `)
//line template/repo_index.qtpl:86
		if !r.Provider.Connected {
//line template/repo_index.qtpl:86
			qw422016.N().S(`disabled="true"`)
//line template/repo_index.qtpl:86
		}
//line template/repo_index.qtpl:86
		qw422016.N().S(`> Disable </button> </form> `)
//line template/repo_index.qtpl:90
	}
//line template/repo_index.qtpl:90
	qw422016.N().S(` </td> </tr> `)
//line template/repo_index.qtpl:93
}

//line template/repo_index.qtpl:93
func (p *RepoIndex) writerenderRepoItem(qq422016 qtio422016.Writer, r *provider.Repo) {
//line template/repo_index.qtpl:93
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template/repo_index.qtpl:93
	p.streamrenderRepoItem(qw422016, r)
//line template/repo_index.qtpl:93
	qt422016.ReleaseWriter(qw422016)
//line template/repo_index.qtpl:93
}

//line template/repo_index.qtpl:93
func (p *RepoIndex) renderRepoItem(r *provider.Repo) string {
//line template/repo_index.qtpl:93
	qb422016 := qt422016.AcquireByteBuffer()
//line template/repo_index.qtpl:93
	p.writerenderRepoItem(qb422016, r)
//line template/repo_index.qtpl:93
	qs422016 := string(qb422016.B)
//line template/repo_index.qtpl:93
	qt422016.ReleaseByteBuffer(qb422016)
//line template/repo_index.qtpl:93
	return qs422016
//line template/repo_index.qtpl:93
}

//line template/repo_index.qtpl:95
func (p *RepoIndex) StreamBody(qw422016 *qt422016.Writer) {
//line template/repo_index.qtpl:95
	qw422016.N().S(` <div class="panel"> <div class="panel-header">`)
//line template/repo_index.qtpl:97
	p.streamrenderProviders(qw422016)
//line template/repo_index.qtpl:97
	qw422016.N().S(`</div> `)
//line template/repo_index.qtpl:98
	if len(p.Providers) == 0 {
//line template/repo_index.qtpl:98
		qw422016.N().S(` <div class="panel-message muted">No 3rd party git providers have been configured to connect to.</div> `)
//line template/repo_index.qtpl:100
	} else {
//line template/repo_index.qtpl:100
		qw422016.N().S(` `)
//line template/repo_index.qtpl:101
		if !p.Provider.Connected {
//line template/repo_index.qtpl:101
			qw422016.N().S(` <div class="panel-message muted"> Connect to `)
//line template/repo_index.qtpl:103
			qw422016.E().S(providerNames[p.Provider.Name])
//line template/repo_index.qtpl:103
			qw422016.N().S(` from your account <a href="/settings">settings</a>. </div> `)
//line template/repo_index.qtpl:105
		} else if len(p.Repos) == 0 {
//line template/repo_index.qtpl:105
			qw422016.N().S(` <div class="panel-message muted">No `)
//line template/repo_index.qtpl:106
			qw422016.E().S(providerNames[p.Provider.Name])
//line template/repo_index.qtpl:106
			qw422016.N().S(` repositories.</div> `)
//line template/repo_index.qtpl:107
		} else {
//line template/repo_index.qtpl:107
			qw422016.N().S(` <table class="table"> <thead> <tr> <th>NAME</th> <th></th> <th></th> </tr> </thead> <tbody> `)
//line template/repo_index.qtpl:117
			for _, r := range p.Repos {
//line template/repo_index.qtpl:117
				qw422016.N().S(` `)
//line template/repo_index.qtpl:118
				p.streamrenderRepoItem(qw422016, r)
//line template/repo_index.qtpl:118
				qw422016.N().S(` `)
//line template/repo_index.qtpl:119
			}
//line template/repo_index.qtpl:119
			qw422016.N().S(` </tbody> </table> `)
//line template/repo_index.qtpl:122
		}
//line template/repo_index.qtpl:122
		qw422016.N().S(` `)
//line template/repo_index.qtpl:123
	}
//line template/repo_index.qtpl:123
	qw422016.N().S(` </div> `)
//line template/repo_index.qtpl:125
	p.Paginator.StreamNavigation(qw422016)
//line template/repo_index.qtpl:125
	qw422016.N().S(` `)
//line template/repo_index.qtpl:126
}

//line template/repo_index.qtpl:126
func (p *RepoIndex) WriteBody(qq422016 qtio422016.Writer) {
//line template/repo_index.qtpl:126
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template/repo_index.qtpl:126
	p.StreamBody(qw422016)
//line template/repo_index.qtpl:126
	qt422016.ReleaseWriter(qw422016)
//line template/repo_index.qtpl:126
}

//line template/repo_index.qtpl:126
func (p *RepoIndex) Body() string {
//line template/repo_index.qtpl:126
	qb422016 := qt422016.AcquireByteBuffer()
//line template/repo_index.qtpl:126
	p.WriteBody(qb422016)
//line template/repo_index.qtpl:126
	qs422016 := string(qb422016.B)
//line template/repo_index.qtpl:126
	qt422016.ReleaseByteBuffer(qb422016)
//line template/repo_index.qtpl:126
	return qs422016
//line template/repo_index.qtpl:126
}
