// Code generated by qtc from "settings.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line template/settings.qtpl:2
package template

//line template/settings.qtpl:2
import (
	"regexp"

	"djinn-ci.com/auth"
	"djinn-ci.com/provider"
	"djinn-ci.com/template/form"
)

//line template/settings.qtpl:11
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line template/settings.qtpl:11
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line template/settings.qtpl:12
type Settings struct {
	*form.Form

	Page      *Page
	Providers []*provider.Provider
	Partial   Partial
}

var settingsLinks = []NavLink{
	{
		Title:   "Account",
		Href:    "/settings",
		Icon:    "static/svg/user.svg",
		Pattern: regexp.MustCompile("^\\/settings$"),
	},
	{
		Title:   "OAuth Apps",
		Href:    "/settings/apps",
		Icon:    "static/svg/folder.svg",
		Pattern: regexp.MustCompile("\\/settings\\/apps"),
	},
	{
		Title:   "Access Tokens",
		Href:    "/settings/tokens",
		Icon:    "static/svg/code.svg",
		Pattern: regexp.MustCompile("\\/settings\\/tokens\\/?"),
	},
	{
		Title:   "Authorized OAuth apps",
		Href:    "/settings/connections",
		Icon:    "static/svg/apps.svg",
		Pattern: regexp.MustCompile("\\/settings\\/connections\\/?"),
	},
}

func cleanup(u *auth.User) string {
	return HumanSize(u.RawData["cleanup"].(int64))
}

//line template/settings.qtpl:53
func (p *Settings) StreamTitle(qw422016 *qt422016.Writer) {
//line template/settings.qtpl:53
	qw422016.N().S(` Settings`)
//line template/settings.qtpl:54
	if p.Partial != nil {
//line template/settings.qtpl:54
		qw422016.N().S(` - `)
//line template/settings.qtpl:54
		p.Partial.StreamTitle(qw422016)
//line template/settings.qtpl:54
	}
//line template/settings.qtpl:54
	qw422016.N().S(` `)
//line template/settings.qtpl:55
}

//line template/settings.qtpl:55
func (p *Settings) WriteTitle(qq422016 qtio422016.Writer) {
//line template/settings.qtpl:55
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template/settings.qtpl:55
	p.StreamTitle(qw422016)
//line template/settings.qtpl:55
	qt422016.ReleaseWriter(qw422016)
//line template/settings.qtpl:55
}

//line template/settings.qtpl:55
func (p *Settings) Title() string {
//line template/settings.qtpl:55
	qb422016 := qt422016.AcquireByteBuffer()
//line template/settings.qtpl:55
	p.WriteTitle(qb422016)
//line template/settings.qtpl:55
	qs422016 := string(qb422016.B)
//line template/settings.qtpl:55
	qt422016.ReleaseByteBuffer(qb422016)
//line template/settings.qtpl:55
	return qs422016
//line template/settings.qtpl:55
}

//line template/settings.qtpl:57
func (p *Settings) StreamHeader(qw422016 *qt422016.Writer) {
//line template/settings.qtpl:57
	qw422016.N().S(` `)
//line template/settings.qtpl:58
	if p.Partial == nil {
//line template/settings.qtpl:58
		qw422016.N().S(` Settings `)
//line template/settings.qtpl:60
	} else {
//line template/settings.qtpl:60
		qw422016.N().S(` `)
//line template/settings.qtpl:61
		p.Partial.StreamHeader(qw422016)
//line template/settings.qtpl:61
		qw422016.N().S(` `)
//line template/settings.qtpl:62
	}
//line template/settings.qtpl:62
	qw422016.N().S(` `)
//line template/settings.qtpl:63
}

//line template/settings.qtpl:63
func (p *Settings) WriteHeader(qq422016 qtio422016.Writer) {
//line template/settings.qtpl:63
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template/settings.qtpl:63
	p.StreamHeader(qw422016)
//line template/settings.qtpl:63
	qt422016.ReleaseWriter(qw422016)
//line template/settings.qtpl:63
}

//line template/settings.qtpl:63
func (p *Settings) Header() string {
//line template/settings.qtpl:63
	qb422016 := qt422016.AcquireByteBuffer()
//line template/settings.qtpl:63
	p.WriteHeader(qb422016)
//line template/settings.qtpl:63
	qs422016 := string(qb422016.B)
//line template/settings.qtpl:63
	qt422016.ReleaseByteBuffer(qb422016)
//line template/settings.qtpl:63
	return qs422016
//line template/settings.qtpl:63
}

//line template/settings.qtpl:65
func (p *Settings) StreamFooter(qw422016 *qt422016.Writer) {
//line template/settings.qtpl:65
}

//line template/settings.qtpl:65
func (p *Settings) WriteFooter(qq422016 qtio422016.Writer) {
//line template/settings.qtpl:65
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template/settings.qtpl:65
	p.StreamFooter(qw422016)
//line template/settings.qtpl:65
	qt422016.ReleaseWriter(qw422016)
//line template/settings.qtpl:65
}

//line template/settings.qtpl:65
func (p *Settings) Footer() string {
//line template/settings.qtpl:65
	qb422016 := qt422016.AcquireByteBuffer()
//line template/settings.qtpl:65
	p.WriteFooter(qb422016)
//line template/settings.qtpl:65
	qs422016 := string(qb422016.B)
//line template/settings.qtpl:65
	qt422016.ReleaseByteBuffer(qb422016)
//line template/settings.qtpl:65
	return qs422016
//line template/settings.qtpl:65
}

//line template/settings.qtpl:67
func (p *Settings) StreamActions(qw422016 *qt422016.Writer) {
//line template/settings.qtpl:67
	qw422016.N().S(` `)
//line template/settings.qtpl:68
	if p.Partial != nil {
//line template/settings.qtpl:68
		qw422016.N().S(` `)
//line template/settings.qtpl:69
		p.Partial.StreamActions(qw422016)
//line template/settings.qtpl:69
		qw422016.N().S(` `)
//line template/settings.qtpl:70
	}
//line template/settings.qtpl:70
	qw422016.N().S(` `)
//line template/settings.qtpl:71
}

//line template/settings.qtpl:71
func (p *Settings) WriteActions(qq422016 qtio422016.Writer) {
//line template/settings.qtpl:71
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template/settings.qtpl:71
	p.StreamActions(qw422016)
//line template/settings.qtpl:71
	qt422016.ReleaseWriter(qw422016)
//line template/settings.qtpl:71
}

//line template/settings.qtpl:71
func (p *Settings) Actions() string {
//line template/settings.qtpl:71
	qb422016 := qt422016.AcquireByteBuffer()
//line template/settings.qtpl:71
	p.WriteActions(qb422016)
//line template/settings.qtpl:71
	qs422016 := string(qb422016.B)
//line template/settings.qtpl:71
	qt422016.ReleaseByteBuffer(qb422016)
//line template/settings.qtpl:71
	return qs422016
//line template/settings.qtpl:71
}

//line template/settings.qtpl:73
func (p *Settings) StreamNavigation(qw422016 *qt422016.Writer) {
//line template/settings.qtpl:73
	qw422016.N().S(` `)
//line template/settings.qtpl:74
	for _, link := range settingsLinks {
//line template/settings.qtpl:74
		qw422016.N().S(` <li>`)
//line template/settings.qtpl:75
		link.StreamRender(qw422016, p.Page.URL.Path)
//line template/settings.qtpl:75
		qw422016.N().S(`</li> `)
//line template/settings.qtpl:76
	}
//line template/settings.qtpl:76
	qw422016.N().S(` `)
//line template/settings.qtpl:77
}

//line template/settings.qtpl:77
func (p *Settings) WriteNavigation(qq422016 qtio422016.Writer) {
//line template/settings.qtpl:77
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template/settings.qtpl:77
	p.StreamNavigation(qw422016)
//line template/settings.qtpl:77
	qt422016.ReleaseWriter(qw422016)
//line template/settings.qtpl:77
}

//line template/settings.qtpl:77
func (p *Settings) Navigation() string {
//line template/settings.qtpl:77
	qb422016 := qt422016.AcquireByteBuffer()
//line template/settings.qtpl:77
	p.WriteNavigation(qb422016)
//line template/settings.qtpl:77
	qs422016 := string(qb422016.B)
//line template/settings.qtpl:77
	qt422016.ReleaseByteBuffer(qb422016)
//line template/settings.qtpl:77
	return qs422016
//line template/settings.qtpl:77
}

//line template/settings.qtpl:79
func (p *Settings) streamverifyForm(qw422016 *qt422016.Writer) {
//line template/settings.qtpl:79
	qw422016.N().S(` `)
//line template/settings.qtpl:80
	if !verified(p.Page.User) {
//line template/settings.qtpl:80
		qw422016.N().S(` <form method="POST" action="/settings/verify"> <h2>Verify account</h2> `)
//line template/settings.qtpl:83
		qw422016.N().V(p.CSRF)
//line template/settings.qtpl:83
		qw422016.N().S(` <div class="form-field"> <button type="submit" class="btn btn-primary">Send verification email</button> </div> </form> <div class="separator"></div> `)
//line template/settings.qtpl:89
	}
//line template/settings.qtpl:89
	qw422016.N().S(` `)
//line template/settings.qtpl:90
}

//line template/settings.qtpl:90
func (p *Settings) writeverifyForm(qq422016 qtio422016.Writer) {
//line template/settings.qtpl:90
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template/settings.qtpl:90
	p.streamverifyForm(qw422016)
//line template/settings.qtpl:90
	qt422016.ReleaseWriter(qw422016)
//line template/settings.qtpl:90
}

//line template/settings.qtpl:90
func (p *Settings) verifyForm() string {
//line template/settings.qtpl:90
	qb422016 := qt422016.AcquireByteBuffer()
//line template/settings.qtpl:90
	p.writeverifyForm(qb422016)
//line template/settings.qtpl:90
	qs422016 := string(qb422016.B)
//line template/settings.qtpl:90
	qt422016.ReleaseByteBuffer(qb422016)
//line template/settings.qtpl:90
	return qs422016
//line template/settings.qtpl:90
}

//line template/settings.qtpl:92
func (p *Settings) streamproviderForm(qw422016 *qt422016.Writer, prv *provider.Provider) {
//line template/settings.qtpl:92
	qw422016.N().S(` `)
//line template/settings.qtpl:93
	if !prv.Connected {
//line template/settings.qtpl:93
		qw422016.N().S(` <form method="POST" action="/oauth" class="inline-block"> `)
//line template/settings.qtpl:95
		qw422016.N().V(p.CSRF)
//line template/settings.qtpl:95
		qw422016.N().S(` <input type="hidden" name="auth_mech" value="oauth2.`)
//line template/settings.qtpl:96
		qw422016.E().S(prv.Name)
//line template/settings.qtpl:96
		qw422016.N().S(`"/> <button type="submit" class="provider-btn provider-`)
//line template/settings.qtpl:97
		qw422016.E().S(prv.Name)
//line template/settings.qtpl:97
		qw422016.N().S(`"> `)
//line template/settings.qtpl:98
		switch prv.Name {
//line template/settings.qtpl:99
		case "github":
//line template/settings.qtpl:99
			qw422016.N().S(` `)
//line template/settings.qtpl:100
			qw422016.N().S(`<!-- Generated by IcoMoon.io -->
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
<path d="M12 0.297c-6.63 0-12 5.373-12 12 0 5.303 3.438 9.8 8.205 11.385 0.6 0.113 0.82-0.258 0.82-0.577 0-0.285-0.010-1.040-0.015-2.040-3.338 0.724-4.042-1.61-4.042-1.61-0.546-1.385-1.335-1.755-1.335-1.755-1.087-0.744 0.084-0.729 0.084-0.729 1.205 0.084 1.838 1.236 1.838 1.236 1.070 1.835 2.809 1.305 3.495 0.998 0.108-0.776 0.417-1.305 0.76-1.605-2.665-0.3-5.466-1.332-5.466-5.93 0-1.31 0.465-2.38 1.235-3.22-0.135-0.303-0.54-1.523 0.105-3.176 0 0 1.005-0.322 3.3 1.23 0.96-0.267 1.98-0.399 3-0.405 1.020 0.006 2.040 0.138 3 0.405 2.28-1.552 3.285-1.23 3.285-1.23 0.645 1.653 0.24 2.873 0.12 3.176 0.765 0.84 1.23 1.91 1.23 3.22 0 4.61-2.805 5.625-5.475 5.92 0.42 0.36 0.81 1.096 0.81 2.22 0 1.606-0.015 2.896-0.015 3.286 0 0.315 0.21 0.69 0.825 0.57 4.801-1.574 8.236-6.074 8.236-11.369 0-6.627-5.373-12-12-12z"></path>
</svg>
`)
//line template/settings.qtpl:100
			qw422016.N().S(` `)
//line template/settings.qtpl:101
		case "gitlab":
//line template/settings.qtpl:101
			qw422016.N().S(` `)
//line template/settings.qtpl:102
			qw422016.N().S(`<!-- Generated by IcoMoon.io -->
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
<path d="M23.955 13.587l-1.342-4.135-2.664-8.189c-0.135-0.423-0.73-0.423-0.867 0l-2.664 8.187h-8.836l-2.663-8.187c-0.136-0.423-0.734-0.423-0.869-0.003l-2.664 8.189-1.342 4.138c-0.121 0.375 0.014 0.789 0.331 1.023l11.625 8.444 11.625-8.443c0.318-0.235 0.453-0.647 0.33-1.024z"></path>
</svg>
`)
//line template/settings.qtpl:102
			qw422016.N().S(` `)
//line template/settings.qtpl:103
		}
//line template/settings.qtpl:103
		qw422016.N().S(` <span>Connect</span> </button> </form> `)
//line template/settings.qtpl:107
	} else {
//line template/settings.qtpl:107
		qw422016.N().S(` <form method="POST" action="/oauth/`)
//line template/settings.qtpl:108
		qw422016.E().S(prv.Name)
//line template/settings.qtpl:108
		qw422016.N().S(`" class="inline-block"> `)
//line template/settings.qtpl:109
		form.StreamMethod(qw422016, "DELETE")
//line template/settings.qtpl:109
		qw422016.N().S(` `)
//line template/settings.qtpl:110
		qw422016.N().V(p.CSRF)
//line template/settings.qtpl:110
		qw422016.N().S(` <button type="submit" class="provider-btn provider-`)
//line template/settings.qtpl:111
		qw422016.E().S(prv.Name)
//line template/settings.qtpl:111
		qw422016.N().S(`"> `)
//line template/settings.qtpl:112
		switch prv.Name {
//line template/settings.qtpl:113
		case "github":
//line template/settings.qtpl:113
			qw422016.N().S(` `)
//line template/settings.qtpl:114
			qw422016.N().S(`<!-- Generated by IcoMoon.io -->
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
<path d="M12 0.297c-6.63 0-12 5.373-12 12 0 5.303 3.438 9.8 8.205 11.385 0.6 0.113 0.82-0.258 0.82-0.577 0-0.285-0.010-1.040-0.015-2.040-3.338 0.724-4.042-1.61-4.042-1.61-0.546-1.385-1.335-1.755-1.335-1.755-1.087-0.744 0.084-0.729 0.084-0.729 1.205 0.084 1.838 1.236 1.838 1.236 1.070 1.835 2.809 1.305 3.495 0.998 0.108-0.776 0.417-1.305 0.76-1.605-2.665-0.3-5.466-1.332-5.466-5.93 0-1.31 0.465-2.38 1.235-3.22-0.135-0.303-0.54-1.523 0.105-3.176 0 0 1.005-0.322 3.3 1.23 0.96-0.267 1.98-0.399 3-0.405 1.020 0.006 2.040 0.138 3 0.405 2.28-1.552 3.285-1.23 3.285-1.23 0.645 1.653 0.24 2.873 0.12 3.176 0.765 0.84 1.23 1.91 1.23 3.22 0 4.61-2.805 5.625-5.475 5.92 0.42 0.36 0.81 1.096 0.81 2.22 0 1.606-0.015 2.896-0.015 3.286 0 0.315 0.21 0.69 0.825 0.57 4.801-1.574 8.236-6.074 8.236-11.369 0-6.627-5.373-12-12-12z"></path>
</svg>
`)
//line template/settings.qtpl:114
			qw422016.N().S(` `)
//line template/settings.qtpl:115
		case "gitlab":
//line template/settings.qtpl:115
			qw422016.N().S(` `)
//line template/settings.qtpl:116
			qw422016.N().S(`<!-- Generated by IcoMoon.io -->
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
<path d="M23.955 13.587l-1.342-4.135-2.664-8.189c-0.135-0.423-0.73-0.423-0.867 0l-2.664 8.187h-8.836l-2.663-8.187c-0.136-0.423-0.734-0.423-0.869-0.003l-2.664 8.189-1.342 4.138c-0.121 0.375 0.014 0.789 0.331 1.023l11.625 8.444 11.625-8.443c0.318-0.235 0.453-0.647 0.33-1.024z"></path>
</svg>
`)
//line template/settings.qtpl:116
			qw422016.N().S(` `)
//line template/settings.qtpl:117
		}
//line template/settings.qtpl:117
		qw422016.N().S(` <span>Disconnect</span> </button> </form> `)
//line template/settings.qtpl:121
	}
//line template/settings.qtpl:121
	qw422016.N().S(` `)
//line template/settings.qtpl:122
}

//line template/settings.qtpl:122
func (p *Settings) writeproviderForm(qq422016 qtio422016.Writer, prv *provider.Provider) {
//line template/settings.qtpl:122
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template/settings.qtpl:122
	p.streamproviderForm(qw422016, prv)
//line template/settings.qtpl:122
	qt422016.ReleaseWriter(qw422016)
//line template/settings.qtpl:122
}

//line template/settings.qtpl:122
func (p *Settings) providerForm(prv *provider.Provider) string {
//line template/settings.qtpl:122
	qb422016 := qt422016.AcquireByteBuffer()
//line template/settings.qtpl:122
	p.writeproviderForm(qb422016, prv)
//line template/settings.qtpl:122
	qs422016 := string(qb422016.B)
//line template/settings.qtpl:122
	qt422016.ReleaseByteBuffer(qb422016)
//line template/settings.qtpl:122
	return qs422016
//line template/settings.qtpl:122
}

//line template/settings.qtpl:124
func (p *Settings) streamproviderForms(qw422016 *qt422016.Writer) {
//line template/settings.qtpl:124
	qw422016.N().S(` `)
//line template/settings.qtpl:125
	if len(p.Providers) > 0 {
//line template/settings.qtpl:125
		qw422016.N().S(` <h2>Connected accounts</h2> `)
//line template/settings.qtpl:127
		for _, prv := range p.Providers {
//line template/settings.qtpl:127
			qw422016.N().S(` `)
//line template/settings.qtpl:128
			p.streamproviderForm(qw422016, prv)
//line template/settings.qtpl:128
			qw422016.N().S(` `)
//line template/settings.qtpl:129
		}
//line template/settings.qtpl:129
		qw422016.N().S(` `)
//line template/settings.qtpl:130
	}
//line template/settings.qtpl:130
	qw422016.N().S(` `)
//line template/settings.qtpl:131
}

//line template/settings.qtpl:131
func (p *Settings) writeproviderForms(qq422016 qtio422016.Writer) {
//line template/settings.qtpl:131
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template/settings.qtpl:131
	p.streamproviderForms(qw422016)
//line template/settings.qtpl:131
	qt422016.ReleaseWriter(qw422016)
//line template/settings.qtpl:131
}

//line template/settings.qtpl:131
func (p *Settings) providerForms() string {
//line template/settings.qtpl:131
	qb422016 := qt422016.AcquireByteBuffer()
//line template/settings.qtpl:131
	p.writeproviderForms(qb422016)
//line template/settings.qtpl:131
	qs422016 := string(qb422016.B)
//line template/settings.qtpl:131
	qt422016.ReleaseByteBuffer(qb422016)
//line template/settings.qtpl:131
	return qs422016
//line template/settings.qtpl:131
}

//line template/settings.qtpl:133
func (p *Settings) streamcleanupForm(qw422016 *qt422016.Writer) {
//line template/settings.qtpl:133
	qw422016.N().S(` <form method="POST" action="/settings/cleanup"> `)
//line template/settings.qtpl:135
	form.StreamMethod(qw422016, "PATCH")
//line template/settings.qtpl:135
	qw422016.N().S(` `)
//line template/settings.qtpl:136
	qw422016.N().V(p.CSRF)
//line template/settings.qtpl:136
	qw422016.N().S(` `)
//line template/settings.qtpl:137
	p.StreamField(qw422016, form.Field{
		ID:    "cleanup",
		Name:  "Cleanup threshold",
		Type:  form.Text,
		Desc:  "The size threshold after which old artifacts should be deleted",
		Value: cleanup(p.Page.User),
	})
//line template/settings.qtpl:143
	qw422016.N().S(` <div class="form-field"> <button type="submit" class="btn btn-primary">Update</button> </div> </form> `)
//line template/settings.qtpl:148
}

//line template/settings.qtpl:148
func (p *Settings) writecleanupForm(qq422016 qtio422016.Writer) {
//line template/settings.qtpl:148
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template/settings.qtpl:148
	p.streamcleanupForm(qw422016)
//line template/settings.qtpl:148
	qt422016.ReleaseWriter(qw422016)
//line template/settings.qtpl:148
}

//line template/settings.qtpl:148
func (p *Settings) cleanupForm() string {
//line template/settings.qtpl:148
	qb422016 := qt422016.AcquireByteBuffer()
//line template/settings.qtpl:148
	p.writecleanupForm(qb422016)
//line template/settings.qtpl:148
	qs422016 := string(qb422016.B)
//line template/settings.qtpl:148
	qt422016.ReleaseByteBuffer(qb422016)
//line template/settings.qtpl:148
	return qs422016
//line template/settings.qtpl:148
}

//line template/settings.qtpl:150
func (p *Settings) streamemailForm(qw422016 *qt422016.Writer) {
//line template/settings.qtpl:150
	qw422016.N().S(` <form method="POST" action="/settings/email"> <h2>Change email</h2> `)
//line template/settings.qtpl:153
	form.StreamMethod(qw422016, "PATCH")
//line template/settings.qtpl:153
	qw422016.N().S(` `)
//line template/settings.qtpl:154
	qw422016.N().V(p.CSRF)
//line template/settings.qtpl:154
	qw422016.N().S(` `)
//line template/settings.qtpl:155
	p.StreamField(qw422016, form.Field{
		ID:   "update_email.email",
		Name: "Email",
		Type: form.Text,
	})
//line template/settings.qtpl:159
	qw422016.N().S(` `)
//line template/settings.qtpl:160
	p.StreamField(qw422016, form.Field{
		ID:   "update_email.verify_password",
		Name: "Verify Password",
		Type: form.Password,
	})
//line template/settings.qtpl:164
	qw422016.N().S(` <div class="form-field"> <button type="submit" class="btn btn-primary">Update</button> </div> </form> `)
//line template/settings.qtpl:169
}

//line template/settings.qtpl:169
func (p *Settings) writeemailForm(qq422016 qtio422016.Writer) {
//line template/settings.qtpl:169
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template/settings.qtpl:169
	p.streamemailForm(qw422016)
//line template/settings.qtpl:169
	qt422016.ReleaseWriter(qw422016)
//line template/settings.qtpl:169
}

//line template/settings.qtpl:169
func (p *Settings) emailForm() string {
//line template/settings.qtpl:169
	qb422016 := qt422016.AcquireByteBuffer()
//line template/settings.qtpl:169
	p.writeemailForm(qb422016)
//line template/settings.qtpl:169
	qs422016 := string(qb422016.B)
//line template/settings.qtpl:169
	qt422016.ReleaseByteBuffer(qb422016)
//line template/settings.qtpl:169
	return qs422016
//line template/settings.qtpl:169
}

//line template/settings.qtpl:171
func (p *Settings) streampasswordForm(qw422016 *qt422016.Writer) {
//line template/settings.qtpl:171
	qw422016.N().S(` <form method="POST" action="/settings/password"> <h2>Change password</h2> `)
//line template/settings.qtpl:174
	form.StreamMethod(qw422016, "PATCH")
//line template/settings.qtpl:174
	qw422016.N().S(` `)
//line template/settings.qtpl:175
	qw422016.N().V(p.CSRF)
//line template/settings.qtpl:175
	qw422016.N().S(` `)
//line template/settings.qtpl:176
	p.StreamField(qw422016, form.Field{
		ID:   "update_password.old_password",
		Name: "Old password",
		Type: form.Password,
	})
//line template/settings.qtpl:180
	qw422016.N().S(` `)
//line template/settings.qtpl:181
	p.StreamField(qw422016, form.Field{
		ID:   "update_password.new_password",
		Name: "New Password",
		Type: form.Password,
	})
//line template/settings.qtpl:185
	qw422016.N().S(` `)
//line template/settings.qtpl:186
	p.StreamField(qw422016, form.Field{
		ID:   "update_password.verify_new_password",
		Name: "Verify Password",
		Type: form.Password,
	})
//line template/settings.qtpl:190
	qw422016.N().S(` <div class="form-field"> <button type="submit" class="btn btn-primary">Update</button> </div> </form> `)
//line template/settings.qtpl:195
}

//line template/settings.qtpl:195
func (p *Settings) writepasswordForm(qq422016 qtio422016.Writer) {
//line template/settings.qtpl:195
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template/settings.qtpl:195
	p.streampasswordForm(qw422016)
//line template/settings.qtpl:195
	qt422016.ReleaseWriter(qw422016)
//line template/settings.qtpl:195
}

//line template/settings.qtpl:195
func (p *Settings) passwordForm() string {
//line template/settings.qtpl:195
	qb422016 := qt422016.AcquireByteBuffer()
//line template/settings.qtpl:195
	p.writepasswordForm(qb422016)
//line template/settings.qtpl:195
	qs422016 := string(qb422016.B)
//line template/settings.qtpl:195
	qt422016.ReleaseByteBuffer(qb422016)
//line template/settings.qtpl:195
	return qs422016
//line template/settings.qtpl:195
}

//line template/settings.qtpl:197
func (p *Settings) streamdeleteForm(qw422016 *qt422016.Writer) {
//line template/settings.qtpl:197
	qw422016.N().S(` <form method="POST" action="/settings/delete"> <h2>Delete account</h2> `)
//line template/settings.qtpl:200
	form.StreamMethod(qw422016, "DELETE")
//line template/settings.qtpl:200
	qw422016.N().S(` `)
//line template/settings.qtpl:201
	qw422016.N().V(p.CSRF)
//line template/settings.qtpl:201
	qw422016.N().S(` `)
//line template/settings.qtpl:202
	p.StreamField(qw422016, form.Field{
		ID:   "delete_account.verify_password",
		Name: "Verify Password",
		Type: form.Password,
	})
//line template/settings.qtpl:206
	qw422016.N().S(` <div class="form-field"> <button type="submit" class="btn btn-danger">Delete</button> </div> </form> `)
//line template/settings.qtpl:211
}

//line template/settings.qtpl:211
func (p *Settings) writedeleteForm(qq422016 qtio422016.Writer) {
//line template/settings.qtpl:211
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template/settings.qtpl:211
	p.streamdeleteForm(qw422016)
//line template/settings.qtpl:211
	qt422016.ReleaseWriter(qw422016)
//line template/settings.qtpl:211
}

//line template/settings.qtpl:211
func (p *Settings) deleteForm() string {
//line template/settings.qtpl:211
	qb422016 := qt422016.AcquireByteBuffer()
//line template/settings.qtpl:211
	p.writedeleteForm(qb422016)
//line template/settings.qtpl:211
	qs422016 := string(qb422016.B)
//line template/settings.qtpl:211
	qt422016.ReleaseByteBuffer(qb422016)
//line template/settings.qtpl:211
	return qs422016
//line template/settings.qtpl:211
}

//line template/settings.qtpl:213
func (p *Settings) StreamBody(qw422016 *qt422016.Writer) {
//line template/settings.qtpl:213
	qw422016.N().S(` `)
//line template/settings.qtpl:214
	if p.Partial != nil {
//line template/settings.qtpl:214
		qw422016.N().S(` `)
//line template/settings.qtpl:215
		p.Partial.StreamBody(qw422016)
//line template/settings.qtpl:215
		qw422016.N().S(` `)
//line template/settings.qtpl:216
	} else {
//line template/settings.qtpl:216
		qw422016.N().S(` <div class="panel"> <div class="panel-body slim"> `)
//line template/settings.qtpl:219
		p.streamverifyForm(qw422016)
//line template/settings.qtpl:219
		qw422016.N().S(` `)
//line template/settings.qtpl:220
		p.streamproviderForms(qw422016)
//line template/settings.qtpl:220
		qw422016.N().S(` <div class="separator"></div> `)
//line template/settings.qtpl:222
		p.streamcleanupForm(qw422016)
//line template/settings.qtpl:222
		qw422016.N().S(` <div class="separator"></div> `)
//line template/settings.qtpl:224
		p.streamemailForm(qw422016)
//line template/settings.qtpl:224
		qw422016.N().S(` <div class="separator"></div> `)
//line template/settings.qtpl:226
		p.streampasswordForm(qw422016)
//line template/settings.qtpl:226
		qw422016.N().S(` <div class="separator"></div> `)
//line template/settings.qtpl:228
		p.streamdeleteForm(qw422016)
//line template/settings.qtpl:228
		qw422016.N().S(` </div> </div> `)
//line template/settings.qtpl:231
	}
//line template/settings.qtpl:231
	qw422016.N().S(` `)
//line template/settings.qtpl:232
}

//line template/settings.qtpl:232
func (p *Settings) WriteBody(qq422016 qtio422016.Writer) {
//line template/settings.qtpl:232
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template/settings.qtpl:232
	p.StreamBody(qw422016)
//line template/settings.qtpl:232
	qt422016.ReleaseWriter(qw422016)
//line template/settings.qtpl:232
}

//line template/settings.qtpl:232
func (p *Settings) Body() string {
//line template/settings.qtpl:232
	qb422016 := qt422016.AcquireByteBuffer()
//line template/settings.qtpl:232
	p.WriteBody(qb422016)
//line template/settings.qtpl:232
	qs422016 := string(qb422016.B)
//line template/settings.qtpl:232
	qt422016.ReleaseByteBuffer(qb422016)
//line template/settings.qtpl:232
	return qs422016
//line template/settings.qtpl:232
}
