// This file is automatically generated by qtc from "render.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line template/object/render.qtpl:2
package object

//line template/object/render.qtpl:2
import (
	"fmt"

	"github.com/andrewpillar/thrall/model"
	"github.com/andrewpillar/thrall/template"
)

//line template/object/render.qtpl:10
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line template/object/render.qtpl:10
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line template/object/render.qtpl:10
func StreamRenderTable(qw422016 *qt422016.Writer, oo []*model.Object, csrf string) {
	//line template/object/render.qtpl:10
	qw422016.N().S(`
	<table class="table">
		<thead>
			<tr>
				<th>NAME</th>
				<th>TYPE</th>
				<th>SIZE</th>
				<th>MD5</th>
				<th>SHA256</th>
				<th></th>
			</tr>
		</thead>
		<tbody>
			`)
	//line template/object/render.qtpl:23
	for _, o := range oo {
		//line template/object/render.qtpl:23
		qw422016.N().S(`
				<tr>
					<td><a href="`)
		//line template/object/render.qtpl:25
		qw422016.E().S(o.UIEndpoint())
		//line template/object/render.qtpl:25
		qw422016.N().S(`">`)
		//line template/object/render.qtpl:25
		qw422016.E().S(o.Name)
		//line template/object/render.qtpl:25
		qw422016.N().S(`</a></td>
					<td><span class="code">`)
		//line template/object/render.qtpl:26
		qw422016.E().S(o.Type)
		//line template/object/render.qtpl:26
		qw422016.N().S(`</span></td>
					<td>`)
		//line template/object/render.qtpl:27
		qw422016.E().S(template.RenderSize(o.Size))
		//line template/object/render.qtpl:27
		qw422016.N().S(`</td>
					<td><span class="code">`)
		//line template/object/render.qtpl:28
		qw422016.E().S(fmt.Sprintf("%x", o.MD5))
		//line template/object/render.qtpl:28
		qw422016.N().S(`</span></td>
					<td><span class="code">`)
		//line template/object/render.qtpl:29
		qw422016.E().S(fmt.Sprintf("%x", o.SHA256))
		//line template/object/render.qtpl:29
		qw422016.N().S(`</span></td>
					<td class="align-right">
						<form method="POST" action="`)
		//line template/object/render.qtpl:31
		qw422016.E().S(o.UIEndpoint())
		//line template/object/render.qtpl:31
		qw422016.N().S(`">
							`)
		//line template/object/render.qtpl:32
		qw422016.N().S(string(csrf))
		//line template/object/render.qtpl:32
		qw422016.N().S(`
							<input type="hidden" name="_method" value="DELETE"/>
							<button type="submit" class="btn btn-danger">Delete</button>
						</form>
					</td>
				</tr>
			`)
		//line template/object/render.qtpl:38
	}
	//line template/object/render.qtpl:38
	qw422016.N().S(`
		</tbody>
	</table>
`)
//line template/object/render.qtpl:41
}

//line template/object/render.qtpl:41
func WriteRenderTable(qq422016 qtio422016.Writer, oo []*model.Object, csrf string) {
	//line template/object/render.qtpl:41
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line template/object/render.qtpl:41
	StreamRenderTable(qw422016, oo, csrf)
	//line template/object/render.qtpl:41
	qt422016.ReleaseWriter(qw422016)
//line template/object/render.qtpl:41
}

//line template/object/render.qtpl:41
func RenderTable(oo []*model.Object, csrf string) string {
	//line template/object/render.qtpl:41
	qb422016 := qt422016.AcquireByteBuffer()
	//line template/object/render.qtpl:41
	WriteRenderTable(qb422016, oo, csrf)
	//line template/object/render.qtpl:41
	qs422016 := string(qb422016.B)
	//line template/object/render.qtpl:41
	qt422016.ReleaseByteBuffer(qb422016)
	//line template/object/render.qtpl:41
	return qs422016
//line template/object/render.qtpl:41
}

//line template/object/render.qtpl:43
func StreamRenderIndex(qw422016 *qt422016.Writer, oo []*model.Object, uri, search, csrf string) {
	//line template/object/render.qtpl:43
	qw422016.N().S(`
	`)
	//line template/object/render.qtpl:44
	if len(oo) == 0 && search == "" {
		//line template/object/render.qtpl:44
		qw422016.N().S(`
		<div class="panel-message muted">Objects are files that can be used in build environments.</div>
	`)
		//line template/object/render.qtpl:46
	} else {
		//line template/object/render.qtpl:46
		qw422016.N().S(`
		<div class="panel-header">`)
		//line template/object/render.qtpl:47
		template.StreamRenderSearch(qw422016, uri, search, "Find an object...")
		//line template/object/render.qtpl:47
		qw422016.N().S(`</div>
		`)
		//line template/object/render.qtpl:48
		if len(oo) == 0 && search != "" {
			//line template/object/render.qtpl:48
			qw422016.N().S(`
			<div class="panel-message muted">No results found.</div>
		`)
			//line template/object/render.qtpl:50
		} else {
			//line template/object/render.qtpl:50
			qw422016.N().S(`
			`)
			//line template/object/render.qtpl:51
			StreamRenderTable(qw422016, oo, csrf)
			//line template/object/render.qtpl:51
			qw422016.N().S(`
		`)
			//line template/object/render.qtpl:52
		}
		//line template/object/render.qtpl:52
		qw422016.N().S(`
	`)
		//line template/object/render.qtpl:53
	}
	//line template/object/render.qtpl:53
	qw422016.N().S(`
`)
//line template/object/render.qtpl:54
}

//line template/object/render.qtpl:54
func WriteRenderIndex(qq422016 qtio422016.Writer, oo []*model.Object, uri, search, csrf string) {
	//line template/object/render.qtpl:54
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line template/object/render.qtpl:54
	StreamRenderIndex(qw422016, oo, uri, search, csrf)
	//line template/object/render.qtpl:54
	qt422016.ReleaseWriter(qw422016)
//line template/object/render.qtpl:54
}

//line template/object/render.qtpl:54
func RenderIndex(oo []*model.Object, uri, search, csrf string) string {
	//line template/object/render.qtpl:54
	qb422016 := qt422016.AcquireByteBuffer()
	//line template/object/render.qtpl:54
	WriteRenderIndex(qb422016, oo, uri, search, csrf)
	//line template/object/render.qtpl:54
	qs422016 := string(qb422016.B)
	//line template/object/render.qtpl:54
	qt422016.ReleaseByteBuffer(qb422016)
	//line template/object/render.qtpl:54
	return qs422016
//line template/object/render.qtpl:54
}
