// Code generated by "stringer -type Level -linecomment"; DO NOT EDIT.

package log

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Debug-1]
	_ = x[Info-2]
	_ = x[Warn-3]
	_ = x[Error-4]
}

const _Level_name = "DEBUGINFOWARNERROR"

var _Level_index = [...]uint8{0, 5, 9, 13, 18}

func (i Level) String() string {
	i -= 1
	if i >= Level(len(_Level_index)-1) {
		return "Level(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Level_name[_Level_index[i]:_Level_index[i+1]]
}
