// Code generated by "stringer -type Resource -linecomment"; DO NOT EDIT.

package oauth2

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Build-1]
	_ = x[Invite-2]
	_ = x[Image-3]
	_ = x[Namespace-4]
	_ = x[Object-5]
	_ = x[Variable-6]
	_ = x[Key-7]
}

const _Resource_name = "buildinviteimagenamespaceobjectvariablekey"

var _Resource_index = [...]uint8{0, 5, 11, 16, 25, 31, 39, 42}

func (i Resource) String() string {
	i -= 1
	if i < 0 || i >= Resource(len(_Resource_index)-1) {
		return "Resource(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Resource_name[_Resource_index[i]:_Resource_index[i+1]]
}
