// Code generated by "stringer -type Resource -linecomment"; DO NOT EDIT.

package oauth2

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Build-1]
	_ = x[Collaborator-2]
	_ = x[Invite-3]
	_ = x[Image-4]
	_ = x[Namespace-5]
	_ = x[Object-6]
	_ = x[Variable-7]
	_ = x[Key-8]
}

const _Resource_name = "buildcollaboratorinviteimagenamespaceobjectvariablekey"

var _Resource_index = [...]uint8{0, 5, 17, 23, 28, 37, 43, 51, 54}

func (i Resource) String() string {
	i -= 1
	if i < 0 || i >= Resource(len(_Resource_index)-1) {
		return "Resource(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Resource_name[_Resource_index[i]:_Resource_index[i+1]]
}
