// Code generated by qtc from "section.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line oauth2/template/section.qtpl:2
package template

//line oauth2/template/section.qtpl:2
import (
	htmltemplate "html/template"

	"djinn-ci.com/oauth2"
	"djinn-ci.com/template"
)

//line oauth2/template/section.qtpl:10
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line oauth2/template/section.qtpl:10
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line oauth2/template/section.qtpl:11
type AppIndex struct {
	template.BasePage

	Apps []*oauth2.App
}

type ConnectionIndex struct {
	template.BasePage

	Tokens []*oauth2.Token
}

type TokenIndex struct {
	CSRF   htmltemplate.HTML
	Tokens []*oauth2.Token
}

//line oauth2/template/section.qtpl:30
func (p *AppIndex) StreamTitle(qw422016 *qt422016.Writer) {
//line oauth2/template/section.qtpl:30
	qw422016.N().S(` OAuth Apps - Djinn `)
//line oauth2/template/section.qtpl:32
}

//line oauth2/template/section.qtpl:32
func (p *AppIndex) WriteTitle(qq422016 qtio422016.Writer) {
//line oauth2/template/section.qtpl:32
	qw422016 := qt422016.AcquireWriter(qq422016)
//line oauth2/template/section.qtpl:32
	p.StreamTitle(qw422016)
//line oauth2/template/section.qtpl:32
	qt422016.ReleaseWriter(qw422016)
//line oauth2/template/section.qtpl:32
}

//line oauth2/template/section.qtpl:32
func (p *AppIndex) Title() string {
//line oauth2/template/section.qtpl:32
	qb422016 := qt422016.AcquireByteBuffer()
//line oauth2/template/section.qtpl:32
	p.WriteTitle(qb422016)
//line oauth2/template/section.qtpl:32
	qs422016 := string(qb422016.B)
//line oauth2/template/section.qtpl:32
	qt422016.ReleaseByteBuffer(qb422016)
//line oauth2/template/section.qtpl:32
	return qs422016
//line oauth2/template/section.qtpl:32
}

//line oauth2/template/section.qtpl:34
func (p *AppIndex) StreamBody(qw422016 *qt422016.Writer) {
//line oauth2/template/section.qtpl:34
	qw422016.N().S(` <div class="panel"> `)
//line oauth2/template/section.qtpl:36
	if len(p.Apps) == 0 {
//line oauth2/template/section.qtpl:36
		qw422016.N().S(` <div class="panel-message muted">No OAuth applications created.</div> `)
//line oauth2/template/section.qtpl:38
	} else {
//line oauth2/template/section.qtpl:38
		qw422016.N().S(` <table class="table"> <tbody> `)
//line oauth2/template/section.qtpl:41
		for _, a := range p.Apps {
//line oauth2/template/section.qtpl:41
			qw422016.N().S(` <tr> <td> <a href="`)
//line oauth2/template/section.qtpl:44
			qw422016.E().S(a.Endpoint())
//line oauth2/template/section.qtpl:44
			qw422016.N().S(`">`)
//line oauth2/template/section.qtpl:44
			qw422016.E().S(a.Name)
//line oauth2/template/section.qtpl:44
			qw422016.N().S(`</a> `)
//line oauth2/template/section.qtpl:45
			if a.Description != "" {
//line oauth2/template/section.qtpl:45
				qw422016.N().S(` <br/><span class="muted">`)
//line oauth2/template/section.qtpl:46
				qw422016.E().S(a.Description)
//line oauth2/template/section.qtpl:46
				qw422016.N().S(`</span> `)
//line oauth2/template/section.qtpl:47
			}
//line oauth2/template/section.qtpl:47
			qw422016.N().S(` </td> </tr> `)
//line oauth2/template/section.qtpl:50
		}
//line oauth2/template/section.qtpl:50
		qw422016.N().S(` </tbody> </table> `)
//line oauth2/template/section.qtpl:53
	}
//line oauth2/template/section.qtpl:53
	qw422016.N().S(` </div> `)
//line oauth2/template/section.qtpl:55
}

//line oauth2/template/section.qtpl:55
func (p *AppIndex) WriteBody(qq422016 qtio422016.Writer) {
//line oauth2/template/section.qtpl:55
	qw422016 := qt422016.AcquireWriter(qq422016)
//line oauth2/template/section.qtpl:55
	p.StreamBody(qw422016)
//line oauth2/template/section.qtpl:55
	qt422016.ReleaseWriter(qw422016)
//line oauth2/template/section.qtpl:55
}

//line oauth2/template/section.qtpl:55
func (p *AppIndex) Body() string {
//line oauth2/template/section.qtpl:55
	qb422016 := qt422016.AcquireByteBuffer()
//line oauth2/template/section.qtpl:55
	p.WriteBody(qb422016)
//line oauth2/template/section.qtpl:55
	qs422016 := string(qb422016.B)
//line oauth2/template/section.qtpl:55
	qt422016.ReleaseByteBuffer(qb422016)
//line oauth2/template/section.qtpl:55
	return qs422016
//line oauth2/template/section.qtpl:55
}

//line oauth2/template/section.qtpl:57
func (p *AppIndex) StreamHeader(qw422016 *qt422016.Writer) {
//line oauth2/template/section.qtpl:57
	qw422016.N().S(` Settings - OAuth Apps `)
//line oauth2/template/section.qtpl:59
}

//line oauth2/template/section.qtpl:59
func (p *AppIndex) WriteHeader(qq422016 qtio422016.Writer) {
//line oauth2/template/section.qtpl:59
	qw422016 := qt422016.AcquireWriter(qq422016)
//line oauth2/template/section.qtpl:59
	p.StreamHeader(qw422016)
//line oauth2/template/section.qtpl:59
	qt422016.ReleaseWriter(qw422016)
//line oauth2/template/section.qtpl:59
}

//line oauth2/template/section.qtpl:59
func (p *AppIndex) Header() string {
//line oauth2/template/section.qtpl:59
	qb422016 := qt422016.AcquireByteBuffer()
//line oauth2/template/section.qtpl:59
	p.WriteHeader(qb422016)
//line oauth2/template/section.qtpl:59
	qs422016 := string(qb422016.B)
//line oauth2/template/section.qtpl:59
	qt422016.ReleaseByteBuffer(qb422016)
//line oauth2/template/section.qtpl:59
	return qs422016
//line oauth2/template/section.qtpl:59
}

//line oauth2/template/section.qtpl:61
func (p *AppIndex) StreamActions(qw422016 *qt422016.Writer) {
//line oauth2/template/section.qtpl:61
	qw422016.N().S(` <li><a href="/settings/apps/create" class="btn btn-primary">Create</a></li> `)
//line oauth2/template/section.qtpl:63
}

//line oauth2/template/section.qtpl:63
func (p *AppIndex) WriteActions(qq422016 qtio422016.Writer) {
//line oauth2/template/section.qtpl:63
	qw422016 := qt422016.AcquireWriter(qq422016)
//line oauth2/template/section.qtpl:63
	p.StreamActions(qw422016)
//line oauth2/template/section.qtpl:63
	qt422016.ReleaseWriter(qw422016)
//line oauth2/template/section.qtpl:63
}

//line oauth2/template/section.qtpl:63
func (p *AppIndex) Actions() string {
//line oauth2/template/section.qtpl:63
	qb422016 := qt422016.AcquireByteBuffer()
//line oauth2/template/section.qtpl:63
	p.WriteActions(qb422016)
//line oauth2/template/section.qtpl:63
	qs422016 := string(qb422016.B)
//line oauth2/template/section.qtpl:63
	qt422016.ReleaseByteBuffer(qb422016)
//line oauth2/template/section.qtpl:63
	return qs422016
//line oauth2/template/section.qtpl:63
}

//line oauth2/template/section.qtpl:65
func (p *ConnectionIndex) StreamTitle(qw422016 *qt422016.Writer) {
//line oauth2/template/section.qtpl:65
	qw422016.N().S(` Authorized OAuth Apps - Djinn `)
//line oauth2/template/section.qtpl:67
}

//line oauth2/template/section.qtpl:67
func (p *ConnectionIndex) WriteTitle(qq422016 qtio422016.Writer) {
//line oauth2/template/section.qtpl:67
	qw422016 := qt422016.AcquireWriter(qq422016)
//line oauth2/template/section.qtpl:67
	p.StreamTitle(qw422016)
//line oauth2/template/section.qtpl:67
	qt422016.ReleaseWriter(qw422016)
//line oauth2/template/section.qtpl:67
}

//line oauth2/template/section.qtpl:67
func (p *ConnectionIndex) Title() string {
//line oauth2/template/section.qtpl:67
	qb422016 := qt422016.AcquireByteBuffer()
//line oauth2/template/section.qtpl:67
	p.WriteTitle(qb422016)
//line oauth2/template/section.qtpl:67
	qs422016 := string(qb422016.B)
//line oauth2/template/section.qtpl:67
	qt422016.ReleaseByteBuffer(qb422016)
//line oauth2/template/section.qtpl:67
	return qs422016
//line oauth2/template/section.qtpl:67
}

//line oauth2/template/section.qtpl:69
func (p *ConnectionIndex) StreamBody(qw422016 *qt422016.Writer) {
//line oauth2/template/section.qtpl:69
	qw422016.N().S(` <div class="panel"> `)
//line oauth2/template/section.qtpl:71
	if len(p.Tokens) == 0 {
//line oauth2/template/section.qtpl:71
		qw422016.N().S(` <div class="panel-message muted">No OAuth applications have been authorized.</div> `)
//line oauth2/template/section.qtpl:73
	} else {
//line oauth2/template/section.qtpl:73
		qw422016.N().S(` <table class="table"> <tbody> `)
//line oauth2/template/section.qtpl:76
		for _, t := range p.Tokens {
//line oauth2/template/section.qtpl:76
			qw422016.N().S(` <tr> <td> <a href="/settings/connections/`)
//line oauth2/template/section.qtpl:79
			qw422016.E().S(t.App.ClientID)
//line oauth2/template/section.qtpl:79
			qw422016.N().S(`">`)
//line oauth2/template/section.qtpl:79
			qw422016.E().S(t.App.Name)
//line oauth2/template/section.qtpl:79
			qw422016.N().S(`</a><br/> Owned by `)
//line oauth2/template/section.qtpl:80
			qw422016.E().S(t.App.User.Username)
//line oauth2/template/section.qtpl:80
			qw422016.N().S(` </td> </tr> `)
//line oauth2/template/section.qtpl:83
		}
//line oauth2/template/section.qtpl:83
		qw422016.N().S(` </tbody> </table> `)
//line oauth2/template/section.qtpl:86
	}
//line oauth2/template/section.qtpl:86
	qw422016.N().S(` </div> `)
//line oauth2/template/section.qtpl:88
}

//line oauth2/template/section.qtpl:88
func (p *ConnectionIndex) WriteBody(qq422016 qtio422016.Writer) {
//line oauth2/template/section.qtpl:88
	qw422016 := qt422016.AcquireWriter(qq422016)
//line oauth2/template/section.qtpl:88
	p.StreamBody(qw422016)
//line oauth2/template/section.qtpl:88
	qt422016.ReleaseWriter(qw422016)
//line oauth2/template/section.qtpl:88
}

//line oauth2/template/section.qtpl:88
func (p *ConnectionIndex) Body() string {
//line oauth2/template/section.qtpl:88
	qb422016 := qt422016.AcquireByteBuffer()
//line oauth2/template/section.qtpl:88
	p.WriteBody(qb422016)
//line oauth2/template/section.qtpl:88
	qs422016 := string(qb422016.B)
//line oauth2/template/section.qtpl:88
	qt422016.ReleaseByteBuffer(qb422016)
//line oauth2/template/section.qtpl:88
	return qs422016
//line oauth2/template/section.qtpl:88
}

//line oauth2/template/section.qtpl:90
func (p *ConnectionIndex) StreamHeader(qw422016 *qt422016.Writer) {
//line oauth2/template/section.qtpl:90
	qw422016.N().S(` Authorized OAuth Apps - Djinn `)
//line oauth2/template/section.qtpl:92
}

//line oauth2/template/section.qtpl:92
func (p *ConnectionIndex) WriteHeader(qq422016 qtio422016.Writer) {
//line oauth2/template/section.qtpl:92
	qw422016 := qt422016.AcquireWriter(qq422016)
//line oauth2/template/section.qtpl:92
	p.StreamHeader(qw422016)
//line oauth2/template/section.qtpl:92
	qt422016.ReleaseWriter(qw422016)
//line oauth2/template/section.qtpl:92
}

//line oauth2/template/section.qtpl:92
func (p *ConnectionIndex) Header() string {
//line oauth2/template/section.qtpl:92
	qb422016 := qt422016.AcquireByteBuffer()
//line oauth2/template/section.qtpl:92
	p.WriteHeader(qb422016)
//line oauth2/template/section.qtpl:92
	qs422016 := string(qb422016.B)
//line oauth2/template/section.qtpl:92
	qt422016.ReleaseByteBuffer(qb422016)
//line oauth2/template/section.qtpl:92
	return qs422016
//line oauth2/template/section.qtpl:92
}

//line oauth2/template/section.qtpl:94
func (p *ConnectionIndex) StreamActions(qw422016 *qt422016.Writer) {
//line oauth2/template/section.qtpl:94
}

//line oauth2/template/section.qtpl:94
func (p *ConnectionIndex) WriteActions(qq422016 qtio422016.Writer) {
//line oauth2/template/section.qtpl:94
	qw422016 := qt422016.AcquireWriter(qq422016)
//line oauth2/template/section.qtpl:94
	p.StreamActions(qw422016)
//line oauth2/template/section.qtpl:94
	qt422016.ReleaseWriter(qw422016)
//line oauth2/template/section.qtpl:94
}

//line oauth2/template/section.qtpl:94
func (p *ConnectionIndex) Actions() string {
//line oauth2/template/section.qtpl:94
	qb422016 := qt422016.AcquireByteBuffer()
//line oauth2/template/section.qtpl:94
	p.WriteActions(qb422016)
//line oauth2/template/section.qtpl:94
	qs422016 := string(qb422016.B)
//line oauth2/template/section.qtpl:94
	qt422016.ReleaseByteBuffer(qb422016)
//line oauth2/template/section.qtpl:94
	return qs422016
//line oauth2/template/section.qtpl:94
}

//line oauth2/template/section.qtpl:96
func (p *TokenIndex) StreamTitle(qw422016 *qt422016.Writer) {
//line oauth2/template/section.qtpl:96
	qw422016.N().S(` Access Tokens - Djinn `)
//line oauth2/template/section.qtpl:98
}

//line oauth2/template/section.qtpl:98
func (p *TokenIndex) WriteTitle(qq422016 qtio422016.Writer) {
//line oauth2/template/section.qtpl:98
	qw422016 := qt422016.AcquireWriter(qq422016)
//line oauth2/template/section.qtpl:98
	p.StreamTitle(qw422016)
//line oauth2/template/section.qtpl:98
	qt422016.ReleaseWriter(qw422016)
//line oauth2/template/section.qtpl:98
}

//line oauth2/template/section.qtpl:98
func (p *TokenIndex) Title() string {
//line oauth2/template/section.qtpl:98
	qb422016 := qt422016.AcquireByteBuffer()
//line oauth2/template/section.qtpl:98
	p.WriteTitle(qb422016)
//line oauth2/template/section.qtpl:98
	qs422016 := string(qb422016.B)
//line oauth2/template/section.qtpl:98
	qt422016.ReleaseByteBuffer(qb422016)
//line oauth2/template/section.qtpl:98
	return qs422016
//line oauth2/template/section.qtpl:98
}

//line oauth2/template/section.qtpl:100
func (p *TokenIndex) StreamBody(qw422016 *qt422016.Writer) {
//line oauth2/template/section.qtpl:100
	qw422016.N().S(` <div class="panel"> `)
//line oauth2/template/section.qtpl:102
	if len(p.Tokens) == 0 {
//line oauth2/template/section.qtpl:102
		qw422016.N().S(` <div class="panel-message muted">No access tokens created.</div> `)
//line oauth2/template/section.qtpl:104
	} else {
//line oauth2/template/section.qtpl:104
		qw422016.N().S(` <table class="table"> <tbody> `)
//line oauth2/template/section.qtpl:107
		for _, t := range p.Tokens {
//line oauth2/template/section.qtpl:107
			qw422016.N().S(` <tr> <td> <strong><a href="`)
//line oauth2/template/section.qtpl:110
			qw422016.E().S(t.Endpoint())
//line oauth2/template/section.qtpl:110
			qw422016.N().S(`">`)
//line oauth2/template/section.qtpl:110
			qw422016.E().S(t.Name)
//line oauth2/template/section.qtpl:110
			qw422016.N().S(`</a></strong> `)
//line oauth2/template/section.qtpl:111
			if t.Token != "" {
//line oauth2/template/section.qtpl:111
				qw422016.N().S(` - <span class="muted">`)
//line oauth2/template/section.qtpl:112
				qw422016.E().S(t.Token)
//line oauth2/template/section.qtpl:112
				qw422016.N().S(`</span> `)
//line oauth2/template/section.qtpl:113
			}
//line oauth2/template/section.qtpl:113
			qw422016.N().S(` </td> <td class="align-right"> <form method="POST" action="`)
//line oauth2/template/section.qtpl:116
			qw422016.E().S(t.Endpoint())
//line oauth2/template/section.qtpl:116
			qw422016.N().S(`"> `)
//line oauth2/template/section.qtpl:117
			qw422016.N().V(p.CSRF)
//line oauth2/template/section.qtpl:117
			qw422016.N().S(` <input type="hidden" name="_method" value="DELETE"/> <button type="submit" class="btn btn-danger">Delete</button> </form> </td> </tr> `)
//line oauth2/template/section.qtpl:123
		}
//line oauth2/template/section.qtpl:123
		qw422016.N().S(` </tbody> </table> `)
//line oauth2/template/section.qtpl:126
	}
//line oauth2/template/section.qtpl:126
	qw422016.N().S(` </div> `)
//line oauth2/template/section.qtpl:128
}

//line oauth2/template/section.qtpl:128
func (p *TokenIndex) WriteBody(qq422016 qtio422016.Writer) {
//line oauth2/template/section.qtpl:128
	qw422016 := qt422016.AcquireWriter(qq422016)
//line oauth2/template/section.qtpl:128
	p.StreamBody(qw422016)
//line oauth2/template/section.qtpl:128
	qt422016.ReleaseWriter(qw422016)
//line oauth2/template/section.qtpl:128
}

//line oauth2/template/section.qtpl:128
func (p *TokenIndex) Body() string {
//line oauth2/template/section.qtpl:128
	qb422016 := qt422016.AcquireByteBuffer()
//line oauth2/template/section.qtpl:128
	p.WriteBody(qb422016)
//line oauth2/template/section.qtpl:128
	qs422016 := string(qb422016.B)
//line oauth2/template/section.qtpl:128
	qt422016.ReleaseByteBuffer(qb422016)
//line oauth2/template/section.qtpl:128
	return qs422016
//line oauth2/template/section.qtpl:128
}

//line oauth2/template/section.qtpl:130
func (p *TokenIndex) StreamHeader(qw422016 *qt422016.Writer) {
//line oauth2/template/section.qtpl:130
	qw422016.N().S(` Settings - Access Tokens `)
//line oauth2/template/section.qtpl:132
}

//line oauth2/template/section.qtpl:132
func (p *TokenIndex) WriteHeader(qq422016 qtio422016.Writer) {
//line oauth2/template/section.qtpl:132
	qw422016 := qt422016.AcquireWriter(qq422016)
//line oauth2/template/section.qtpl:132
	p.StreamHeader(qw422016)
//line oauth2/template/section.qtpl:132
	qt422016.ReleaseWriter(qw422016)
//line oauth2/template/section.qtpl:132
}

//line oauth2/template/section.qtpl:132
func (p *TokenIndex) Header() string {
//line oauth2/template/section.qtpl:132
	qb422016 := qt422016.AcquireByteBuffer()
//line oauth2/template/section.qtpl:132
	p.WriteHeader(qb422016)
//line oauth2/template/section.qtpl:132
	qs422016 := string(qb422016.B)
//line oauth2/template/section.qtpl:132
	qt422016.ReleaseByteBuffer(qb422016)
//line oauth2/template/section.qtpl:132
	return qs422016
//line oauth2/template/section.qtpl:132
}

//line oauth2/template/section.qtpl:134
func (p *TokenIndex) StreamActions(qw422016 *qt422016.Writer) {
//line oauth2/template/section.qtpl:134
	qw422016.N().S(` <li> <form method="POST" action="/settings/tokens/revoke"> `)
//line oauth2/template/section.qtpl:137
	qw422016.N().V(p.CSRF)
//line oauth2/template/section.qtpl:137
	qw422016.N().S(` <input type="hidden" name="_method" value="DELETE"/> <button type="submit" class="btn btn-danger">Revoke All</button> </form> </li> <li><a href="/settings/tokens/create" class="btn btn-primary">Create</a></li> `)
//line oauth2/template/section.qtpl:143
}

//line oauth2/template/section.qtpl:143
func (p *TokenIndex) WriteActions(qq422016 qtio422016.Writer) {
//line oauth2/template/section.qtpl:143
	qw422016 := qt422016.AcquireWriter(qq422016)
//line oauth2/template/section.qtpl:143
	p.StreamActions(qw422016)
//line oauth2/template/section.qtpl:143
	qt422016.ReleaseWriter(qw422016)
//line oauth2/template/section.qtpl:143
}

//line oauth2/template/section.qtpl:143
func (p *TokenIndex) Actions() string {
//line oauth2/template/section.qtpl:143
	qb422016 := qt422016.AcquireByteBuffer()
//line oauth2/template/section.qtpl:143
	p.WriteActions(qb422016)
//line oauth2/template/section.qtpl:143
	qs422016 := string(qb422016.B)
//line oauth2/template/section.qtpl:143
	qt422016.ReleaseByteBuffer(qb422016)
//line oauth2/template/section.qtpl:143
	return qs422016
//line oauth2/template/section.qtpl:143
}
