// Code generated by qtc from "index.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line key/template/index.qtpl:2
package template

//line key/template/index.qtpl:2
import (
	htmltemplate "html/template"

	"github.com/andrewpillar/djinn/database"
	"github.com/andrewpillar/djinn/key"
	"github.com/andrewpillar/djinn/template"
)

//line key/template/index.qtpl:11
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line key/template/index.qtpl:11
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line key/template/index.qtpl:12
type Index struct {
	template.BasePage

	CSRF      htmltemplate.HTML
	Paginator database.Paginator
	Keys      []*key.Key
	Search    string
}

//line key/template/index.qtpl:23
func (p *Index) StreamTitle(qw422016 *qt422016.Writer) {
//line key/template/index.qtpl:23
	qw422016.N().S(` SSH Keys - Djinn CI `)
//line key/template/index.qtpl:25
}

//line key/template/index.qtpl:25
func (p *Index) WriteTitle(qq422016 qtio422016.Writer) {
//line key/template/index.qtpl:25
	qw422016 := qt422016.AcquireWriter(qq422016)
//line key/template/index.qtpl:25
	p.StreamTitle(qw422016)
//line key/template/index.qtpl:25
	qt422016.ReleaseWriter(qw422016)
//line key/template/index.qtpl:25
}

//line key/template/index.qtpl:25
func (p *Index) Title() string {
//line key/template/index.qtpl:25
	qb422016 := qt422016.AcquireByteBuffer()
//line key/template/index.qtpl:25
	p.WriteTitle(qb422016)
//line key/template/index.qtpl:25
	qs422016 := string(qb422016.B)
//line key/template/index.qtpl:25
	qt422016.ReleaseByteBuffer(qb422016)
//line key/template/index.qtpl:25
	return qs422016
//line key/template/index.qtpl:25
}

//line key/template/index.qtpl:27
func (p *Index) StreamBody(qw422016 *qt422016.Writer) {
//line key/template/index.qtpl:27
	qw422016.N().S(` <div class="panel"> `)
//line key/template/index.qtpl:29
	if len(p.Keys) == 0 && p.Search == "" {
//line key/template/index.qtpl:29
		qw422016.N().S(` <div class="panel-message muted">SSH keys can allow build environments to access other environments.</div> `)
//line key/template/index.qtpl:31
	} else {
//line key/template/index.qtpl:31
		qw422016.N().S(` <div class="panel-header">`)
//line key/template/index.qtpl:32
		template.StreamRenderSearch(qw422016, p.URL.Path, p.Search, "Find an SSH key...")
//line key/template/index.qtpl:32
		qw422016.N().S(`</div> `)
//line key/template/index.qtpl:33
		if len(p.Keys) == 0 && p.Search != "" {
//line key/template/index.qtpl:33
			qw422016.N().S(` <div class="panel-message muted">No results found.</div> `)
//line key/template/index.qtpl:35
		} else {
//line key/template/index.qtpl:35
			qw422016.N().S(` <table class="table"> <thead> <tr> <th>NAME</th> <th>NAMESPACE</th> <th></th> <th></th> </tr> </thead> <tbody> `)
//line key/template/index.qtpl:46
			for _, k := range p.Keys {
//line key/template/index.qtpl:46
				qw422016.N().S(` <tr> <td><a href="`)
//line key/template/index.qtpl:48
				qw422016.E().S(k.Endpoint("edit"))
//line key/template/index.qtpl:48
				qw422016.N().S(`">`)
//line key/template/index.qtpl:48
				qw422016.E().S(k.Name)
//line key/template/index.qtpl:48
				qw422016.N().S(`</a></td> <td> `)
//line key/template/index.qtpl:50
				if k.Namespace != nil {
//line key/template/index.qtpl:50
					qw422016.N().S(` <a href="`)
//line key/template/index.qtpl:51
					qw422016.E().S(k.Namespace.Endpoint())
//line key/template/index.qtpl:51
					qw422016.N().S(`">`)
//line key/template/index.qtpl:51
					qw422016.E().S(k.Namespace.Path)
//line key/template/index.qtpl:51
					qw422016.N().S(`</a> `)
//line key/template/index.qtpl:52
				} else {
//line key/template/index.qtpl:52
					qw422016.N().S(` <span class="muted">--</span> `)
//line key/template/index.qtpl:54
				}
//line key/template/index.qtpl:54
				qw422016.N().S(` </td> <td class="align-right"> `)
//line key/template/index.qtpl:57
				if p.User.ID != k.UserID {
//line key/template/index.qtpl:57
					qw422016.N().S(` <span class="muted">`)
//line key/template/index.qtpl:58
					qw422016.N().S(`<!-- Generated by IcoMoon.io -->
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
<path d="M15.984 12.984c2.344 0 7.031 1.172 7.031 3.516v2.484h-6v-2.484c0-1.5-0.797-2.625-1.969-3.469 0.328-0.047 0.656-0.047 0.938-0.047zM8.016 12.984c2.344 0 6.984 1.172 6.984 3.516v2.484h-14.016v-2.484c0-2.344 4.688-3.516 7.031-3.516zM8.016 11.016c-1.641 0-3-1.359-3-3s1.359-3 3-3 2.953 1.359 2.953 3-1.313 3-2.953 3zM15.984 11.016c-1.641 0-3-1.359-3-3s1.359-3 3-3 3 1.359 3 3-1.359 3-3 3z"></path>
</svg>
`)
//line key/template/index.qtpl:58
					qw422016.N().S(`</span> `)
//line key/template/index.qtpl:59
				}
//line key/template/index.qtpl:59
				qw422016.N().S(` </td> <td class="align-right"> `)
//line key/template/index.qtpl:62
				if p.User.ID == k.UserID || k.Namespace != nil && k.Namespace.UserID == p.User.ID {
//line key/template/index.qtpl:62
					qw422016.N().S(` <form method="POST" action="`)
//line key/template/index.qtpl:63
					qw422016.E().S(k.Endpoint())
//line key/template/index.qtpl:63
					qw422016.N().S(`"> `)
//line key/template/index.qtpl:64
					qw422016.N().V(p.CSRF)
//line key/template/index.qtpl:64
					qw422016.N().S(` <input type="hidden" name="_method" value="DELETE"/> <button type="submit" class="btn btn-danger">Delete</button> </form> `)
//line key/template/index.qtpl:68
				}
//line key/template/index.qtpl:68
				qw422016.N().S(` </td> </tr> `)
//line key/template/index.qtpl:71
			}
//line key/template/index.qtpl:71
			qw422016.N().S(` </tbody> </table> `)
//line key/template/index.qtpl:74
		}
//line key/template/index.qtpl:74
		qw422016.N().S(` `)
//line key/template/index.qtpl:75
	}
//line key/template/index.qtpl:75
	qw422016.N().S(` </div> `)
//line key/template/index.qtpl:77
	template.StreamRenderPaginator(qw422016, p.URL, p.Paginator)
//line key/template/index.qtpl:77
	qw422016.N().S(` `)
//line key/template/index.qtpl:78
}

//line key/template/index.qtpl:78
func (p *Index) WriteBody(qq422016 qtio422016.Writer) {
//line key/template/index.qtpl:78
	qw422016 := qt422016.AcquireWriter(qq422016)
//line key/template/index.qtpl:78
	p.StreamBody(qw422016)
//line key/template/index.qtpl:78
	qt422016.ReleaseWriter(qw422016)
//line key/template/index.qtpl:78
}

//line key/template/index.qtpl:78
func (p *Index) Body() string {
//line key/template/index.qtpl:78
	qb422016 := qt422016.AcquireByteBuffer()
//line key/template/index.qtpl:78
	p.WriteBody(qb422016)
//line key/template/index.qtpl:78
	qs422016 := string(qb422016.B)
//line key/template/index.qtpl:78
	qt422016.ReleaseByteBuffer(qb422016)
//line key/template/index.qtpl:78
	return qs422016
//line key/template/index.qtpl:78
}

//line key/template/index.qtpl:80
func (p *Index) StreamSection(qw422016 *qt422016.Writer) {
//line key/template/index.qtpl:80
	qw422016.N().S(` `)
//line key/template/index.qtpl:81
	p.StreamBody(qw422016)
//line key/template/index.qtpl:81
	qw422016.N().S(` `)
//line key/template/index.qtpl:82
}

//line key/template/index.qtpl:82
func (p *Index) WriteSection(qq422016 qtio422016.Writer) {
//line key/template/index.qtpl:82
	qw422016 := qt422016.AcquireWriter(qq422016)
//line key/template/index.qtpl:82
	p.StreamSection(qw422016)
//line key/template/index.qtpl:82
	qt422016.ReleaseWriter(qw422016)
//line key/template/index.qtpl:82
}

//line key/template/index.qtpl:82
func (p *Index) Section() string {
//line key/template/index.qtpl:82
	qb422016 := qt422016.AcquireByteBuffer()
//line key/template/index.qtpl:82
	p.WriteSection(qb422016)
//line key/template/index.qtpl:82
	qs422016 := string(qb422016.B)
//line key/template/index.qtpl:82
	qt422016.ReleaseByteBuffer(qb422016)
//line key/template/index.qtpl:82
	return qs422016
//line key/template/index.qtpl:82
}

//line key/template/index.qtpl:84
func (p *Index) StreamHeader(qw422016 *qt422016.Writer) {
//line key/template/index.qtpl:84
	qw422016.N().S(` SSH Keys `)
//line key/template/index.qtpl:86
}

//line key/template/index.qtpl:86
func (p *Index) WriteHeader(qq422016 qtio422016.Writer) {
//line key/template/index.qtpl:86
	qw422016 := qt422016.AcquireWriter(qq422016)
//line key/template/index.qtpl:86
	p.StreamHeader(qw422016)
//line key/template/index.qtpl:86
	qt422016.ReleaseWriter(qw422016)
//line key/template/index.qtpl:86
}

//line key/template/index.qtpl:86
func (p *Index) Header() string {
//line key/template/index.qtpl:86
	qb422016 := qt422016.AcquireByteBuffer()
//line key/template/index.qtpl:86
	p.WriteHeader(qb422016)
//line key/template/index.qtpl:86
	qs422016 := string(qb422016.B)
//line key/template/index.qtpl:86
	qt422016.ReleaseByteBuffer(qb422016)
//line key/template/index.qtpl:86
	return qs422016
//line key/template/index.qtpl:86
}

//line key/template/index.qtpl:88
func (p *Index) StreamActions(qw422016 *qt422016.Writer) {
//line key/template/index.qtpl:88
	qw422016.N().S(` `)
//line key/template/index.qtpl:89
	if _, ok := p.User.Permissions["key:write"]; ok {
//line key/template/index.qtpl:89
		qw422016.N().S(` <li><a href="/keys/create" class="btn btn-primary">Create</a></li> `)
//line key/template/index.qtpl:91
	}
//line key/template/index.qtpl:91
	qw422016.N().S(` `)
//line key/template/index.qtpl:92
}

//line key/template/index.qtpl:92
func (p *Index) WriteActions(qq422016 qtio422016.Writer) {
//line key/template/index.qtpl:92
	qw422016 := qt422016.AcquireWriter(qq422016)
//line key/template/index.qtpl:92
	p.StreamActions(qw422016)
//line key/template/index.qtpl:92
	qt422016.ReleaseWriter(qw422016)
//line key/template/index.qtpl:92
}

//line key/template/index.qtpl:92
func (p *Index) Actions() string {
//line key/template/index.qtpl:92
	qb422016 := qt422016.AcquireByteBuffer()
//line key/template/index.qtpl:92
	p.WriteActions(qb422016)
//line key/template/index.qtpl:92
	qs422016 := string(qb422016.B)
//line key/template/index.qtpl:92
	qt422016.ReleaseByteBuffer(qb422016)
//line key/template/index.qtpl:92
	return qs422016
//line key/template/index.qtpl:92
}

//line key/template/index.qtpl:94
func (p *Index) StreamNavigation(qw422016 *qt422016.Writer) {
//line key/template/index.qtpl:94
}

//line key/template/index.qtpl:94
func (p *Index) WriteNavigation(qq422016 qtio422016.Writer) {
//line key/template/index.qtpl:94
	qw422016 := qt422016.AcquireWriter(qq422016)
//line key/template/index.qtpl:94
	p.StreamNavigation(qw422016)
//line key/template/index.qtpl:94
	qt422016.ReleaseWriter(qw422016)
//line key/template/index.qtpl:94
}

//line key/template/index.qtpl:94
func (p *Index) Navigation() string {
//line key/template/index.qtpl:94
	qb422016 := qt422016.AcquireByteBuffer()
//line key/template/index.qtpl:94
	p.WriteNavigation(qb422016)
//line key/template/index.qtpl:94
	qs422016 := string(qb422016.B)
//line key/template/index.qtpl:94
	qt422016.ReleaseByteBuffer(qb422016)
//line key/template/index.qtpl:94
	return qs422016
//line key/template/index.qtpl:94
}
