// This file is automatically generated by qtc from "index.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line template/namespace/index.qtpl:2
package namespace

//line template/namespace/index.qtpl:2
import (
	"github.com/andrewpillar/thrall/model"
	"github.com/andrewpillar/thrall/template"
)

//line template/namespace/index.qtpl:8
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line template/namespace/index.qtpl:8
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line template/namespace/index.qtpl:9
type IndexPage struct {
	*template.Page

	Namespaces []*model.Namespace
}

//line template/namespace/index.qtpl:16
func (p *IndexPage) StreamTitle(qw422016 *qt422016.Writer) {
	//line template/namespace/index.qtpl:16
	qw422016.N().S(`
`)
	//line template/namespace/index.qtpl:17
	p.Page.StreamTitle(qw422016)
	//line template/namespace/index.qtpl:17
	qw422016.N().S(` - Namespaces
`)
//line template/namespace/index.qtpl:18
}

//line template/namespace/index.qtpl:18
func (p *IndexPage) WriteTitle(qq422016 qtio422016.Writer) {
	//line template/namespace/index.qtpl:18
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line template/namespace/index.qtpl:18
	p.StreamTitle(qw422016)
	//line template/namespace/index.qtpl:18
	qt422016.ReleaseWriter(qw422016)
//line template/namespace/index.qtpl:18
}

//line template/namespace/index.qtpl:18
func (p *IndexPage) Title() string {
	//line template/namespace/index.qtpl:18
	qb422016 := qt422016.AcquireByteBuffer()
	//line template/namespace/index.qtpl:18
	p.WriteTitle(qb422016)
	//line template/namespace/index.qtpl:18
	qs422016 := string(qb422016.B)
	//line template/namespace/index.qtpl:18
	qt422016.ReleaseByteBuffer(qb422016)
	//line template/namespace/index.qtpl:18
	return qs422016
//line template/namespace/index.qtpl:18
}

//line template/namespace/index.qtpl:20
func (p *IndexPage) StreamBody(qw422016 *qt422016.Writer) {
	//line template/namespace/index.qtpl:20
	qw422016.N().S(`
<div class="dashboard-header">
	<h1>Namespaces</h1>
	<ul class="actions">
		<li><a href="/namespaces/create" class="button button-primary">Create</a></li>
	</ul>
</div>
`)
	//line template/namespace/index.qtpl:27
	if len(p.Namespaces) == 0 {
		//line template/namespace/index.qtpl:27
		qw422016.N().S(`
<div class="dashboard-message">Namespaces allow you to group related builds together.</div>
`)
		//line template/namespace/index.qtpl:29
	} else {
		//line template/namespace/index.qtpl:29
		qw422016.N().S(`
<div class="dashboard-body">
	`)
		//line template/namespace/index.qtpl:31
		for _, n := range p.Namespaces {
			//line template/namespace/index.qtpl:31
			qw422016.N().S(`
		<div class="panel">
			<a href="/u/`)
			//line template/namespace/index.qtpl:33
			qw422016.E().S(n.User.Username)
			//line template/namespace/index.qtpl:33
			qw422016.N().S(`/`)
			//line template/namespace/index.qtpl:33
			qw422016.E().S(n.Name)
			//line template/namespace/index.qtpl:33
			qw422016.N().S(`">`)
			//line template/namespace/index.qtpl:33
			qw422016.E().S(n.User.Username)
			//line template/namespace/index.qtpl:33
			qw422016.N().S(`/`)
			//line template/namespace/index.qtpl:33
			qw422016.E().S(n.Name)
			//line template/namespace/index.qtpl:33
			qw422016.N().S(`</a>
		</div>
	`)
			//line template/namespace/index.qtpl:35
		}
		//line template/namespace/index.qtpl:35
		qw422016.N().S(`
</div>
`)
		//line template/namespace/index.qtpl:37
	}
	//line template/namespace/index.qtpl:37
	qw422016.N().S(`
`)
//line template/namespace/index.qtpl:38
}

//line template/namespace/index.qtpl:38
func (p *IndexPage) WriteBody(qq422016 qtio422016.Writer) {
	//line template/namespace/index.qtpl:38
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line template/namespace/index.qtpl:38
	p.StreamBody(qw422016)
	//line template/namespace/index.qtpl:38
	qt422016.ReleaseWriter(qw422016)
//line template/namespace/index.qtpl:38
}

//line template/namespace/index.qtpl:38
func (p *IndexPage) Body() string {
	//line template/namespace/index.qtpl:38
	qb422016 := qt422016.AcquireByteBuffer()
	//line template/namespace/index.qtpl:38
	p.WriteBody(qb422016)
	//line template/namespace/index.qtpl:38
	qs422016 := string(qb422016.B)
	//line template/namespace/index.qtpl:38
	qt422016.ReleaseByteBuffer(qb422016)
	//line template/namespace/index.qtpl:38
	return qs422016
//line template/namespace/index.qtpl:38
}
