#!/bin/sh

set -e

if ! hash mdsrv &> /dev/null; then
	>&2 printf "could not find mdsrv\n"
	>&2 printf "download and install to serve markdown documents locally\n"
	>&2 printf "https://github.com/andrewpillar/mdsrv\n"
	exit 1
fi

dir="$(dirname $(realpath "$0"))"

mdsrv -dir "$dir" \
	-assets "$dir"/assets \
	-tmpl "$dir"/document.tmpl \
	-var host=https://localhost:8443 \
	-var apihost=https://localhost:8443/api \
	-var imgsrv=https://images.djinn-ci.com
