// This file is automatically generated by qtc from "show.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line template/job/show.qtpl:2
package job

//line template/job/show.qtpl:2
import (
	"fmt"

	"github.com/andrewpillar/thrall/model"
	"github.com/andrewpillar/thrall/template"
)

//line template/job/show.qtpl:10
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line template/job/show.qtpl:10
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line template/job/show.qtpl:11
type ShowPage struct {
	template.Page

	Job *model.Job
}

//line template/job/show.qtpl:19
func (p *ShowPage) StreamTitle(qw422016 *qt422016.Writer) {
	//line template/job/show.qtpl:19
	qw422016.N().S(` `)
	//line template/job/show.qtpl:20
	qw422016.E().S(p.Job.Name)
	//line template/job/show.qtpl:20
	qw422016.N().S(` - Thrall `)
//line template/job/show.qtpl:21
}

//line template/job/show.qtpl:21
func (p *ShowPage) WriteTitle(qq422016 qtio422016.Writer) {
	//line template/job/show.qtpl:21
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line template/job/show.qtpl:21
	p.StreamTitle(qw422016)
	//line template/job/show.qtpl:21
	qt422016.ReleaseWriter(qw422016)
//line template/job/show.qtpl:21
}

//line template/job/show.qtpl:21
func (p *ShowPage) Title() string {
	//line template/job/show.qtpl:21
	qb422016 := qt422016.AcquireByteBuffer()
	//line template/job/show.qtpl:21
	p.WriteTitle(qb422016)
	//line template/job/show.qtpl:21
	qs422016 := string(qb422016.B)
	//line template/job/show.qtpl:21
	qt422016.ReleaseByteBuffer(qb422016)
	//line template/job/show.qtpl:21
	return qs422016
//line template/job/show.qtpl:21
}

//line template/job/show.qtpl:23
func (p *ShowPage) StreamBody(qw422016 *qt422016.Writer) {
	//line template/job/show.qtpl:23
	qw422016.N().S(` <div class="overflow"> <div class="col-75 mb-10 pr-5 left"> <div class="panel"> `)
	//line template/job/show.qtpl:27
	if p.Job.Output.Valid {
		//line template/job/show.qtpl:27
		qw422016.N().S(` <div class="panel-header"> <h3>Output</h3> <ul class="panel-actions"> <li><a class="btn btn-primary" href="`)
		//line template/job/show.qtpl:31
		qw422016.E().S(p.Job.UIEndpoint("output", "raw"))
		//line template/job/show.qtpl:31
		qw422016.N().S(`">`)
		//line template/job/show.qtpl:31
		qw422016.N().S(`<!-- Generated by IcoMoon.io -->
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
<path d="M12.984 9h5.531l-5.531-5.484v5.484zM15.984 14.016v-2.016h-7.969v2.016h7.969zM15.984 18v-2.016h-7.969v2.016h7.969zM14.016 2.016l6 6v12c0 1.078-0.938 1.969-2.016 1.969h-12c-1.078 0-2.016-0.891-2.016-1.969l0.047-16.031c0-1.078 0.891-1.969 1.969-1.969h8.016z"></path>
</svg>
`)
		//line template/job/show.qtpl:31
		qw422016.N().S(`<span>Raw</span></a></li> </ul> </div> `)
		//line template/job/show.qtpl:34
		template.StreamRenderCode(qw422016, p.Job.Output.String)
		//line template/job/show.qtpl:34
		qw422016.N().S(` `)
		//line template/job/show.qtpl:35
	} else {
		//line template/job/show.qtpl:35
		qw422016.N().S(` <div class="panel-message muted">No job output has been produced.</div> `)
		//line template/job/show.qtpl:37
	}
	//line template/job/show.qtpl:37
	qw422016.N().S(` </div> </div> <div class="col-25 mb-10 pl-5 right"> <div class="panel"> <table class="table"> <tr> <td>Status:</td> <td class="align-right">`)
	//line template/job/show.qtpl:45
	template.StreamRenderStatus(qw422016, p.Job.Status)
	//line template/job/show.qtpl:45
	qw422016.N().S(`</td> </tr> <tr> <td>Started at:</td> <td class="align-right"> `)
	//line template/job/show.qtpl:50
	if p.Job.StartedAt.Valid {
		//line template/job/show.qtpl:50
		qw422016.N().S(` `)
		//line template/job/show.qtpl:51
		qw422016.E().V(p.Job.StartedAt.Time.Format("2006-01-02T15:04:05"))
		//line template/job/show.qtpl:51
		qw422016.N().S(` `)
		//line template/job/show.qtpl:52
	} else {
		//line template/job/show.qtpl:52
		qw422016.N().S(` <span class="muted">--</span> `)
		//line template/job/show.qtpl:54
	}
	//line template/job/show.qtpl:54
	qw422016.N().S(` </td> </tr> <tr> <td>Finished at:</td> <td class="align-right"> `)
	//line template/job/show.qtpl:60
	if p.Job.FinishedAt.Valid {
		//line template/job/show.qtpl:60
		qw422016.N().S(` `)
		//line template/job/show.qtpl:61
		qw422016.E().V(p.Job.FinishedAt.Time.Format("2006-01-02T15:04:05"))
		//line template/job/show.qtpl:61
		qw422016.N().S(` `)
		//line template/job/show.qtpl:62
	} else {
		//line template/job/show.qtpl:62
		qw422016.N().S(` <span class="muted">--</span> `)
		//line template/job/show.qtpl:64
	}
	//line template/job/show.qtpl:64
	qw422016.N().S(` </td> </tr> <tr> <td>Duration:</td> <td class="align-right"> `)
	//line template/job/show.qtpl:70
	if !p.Job.FinishedAt.Valid || !p.Job.StartedAt.Valid {
		//line template/job/show.qtpl:70
		qw422016.N().S(` <span class="muted">--</span> `)
		//line template/job/show.qtpl:72
	} else {
		//line template/job/show.qtpl:72
		qw422016.N().S(` `)
		//line template/job/show.qtpl:73
		qw422016.E().V(p.Job.FinishedAt.Time.Sub(p.Job.StartedAt.Time))
		//line template/job/show.qtpl:73
		qw422016.N().S(` `)
		//line template/job/show.qtpl:74
	}
	//line template/job/show.qtpl:74
	qw422016.N().S(` </td> </tr> </table> </div> </div> </div> <div class="panel"> <div class="panel-header"><h3>Artifacts</h3></div> `)
	//line template/job/show.qtpl:83
	if len(p.Job.Artifacts) > 0 {
		//line template/job/show.qtpl:83
		qw422016.N().S(` <table class="table"> <thead> <tr> <th>SOURCE</th> <th>NAME</th> <tH>SIZE</th> <th>HASHES</th> </tr> </thead> <tbody> `)
		//line template/job/show.qtpl:94
		for _, a := range p.Job.Artifacts {
			//line template/job/show.qtpl:94
			qw422016.N().S(` <tr> <td><span class="code">`)
			//line template/job/show.qtpl:96
			qw422016.E().S(a.Source)
			//line template/job/show.qtpl:96
			qw422016.N().S(`</span></td> <td>`)
			//line template/job/show.qtpl:97
			qw422016.E().S(a.Name)
			//line template/job/show.qtpl:97
			qw422016.N().S(`</td> <td>`)
			//line template/job/show.qtpl:98
			qw422016.E().S(template.RenderSize(a.Size.Int64))
			//line template/job/show.qtpl:98
			qw422016.N().S(`</td> <td> <div class="mb-10">MD5 <span class="code right">`)
			//line template/job/show.qtpl:100
			qw422016.E().S(fmt.Sprintf("%x", a.MD5))
			//line template/job/show.qtpl:100
			qw422016.N().S(`</span></div> <div class="mb-10">SHA256 <span class="code right">`)
			//line template/job/show.qtpl:101
			qw422016.E().S(fmt.Sprintf("%x", a.SHA256))
			//line template/job/show.qtpl:101
			qw422016.N().S(`</span></div> </td> </tr> `)
			//line template/job/show.qtpl:104
		}
		//line template/job/show.qtpl:104
		qw422016.N().S(` </tbody> </table> `)
		//line template/job/show.qtpl:107
	} else {
		//line template/job/show.qtpl:107
		qw422016.N().S(` <div class="panel-message muted">No artifacts have been collected for this job.</div> `)
		//line template/job/show.qtpl:109
	}
	//line template/job/show.qtpl:109
	qw422016.N().S(` </div> <div class="panel"> <div class="panel-header"><h3>Dependencies</h3></div> `)
	//line template/job/show.qtpl:113
	if len(p.Job.Dependencies) > 0 {
		//line template/job/show.qtpl:113
		qw422016.N().S(` `)
		//line template/job/show.qtpl:114
		StreamRenderTable(qw422016, p.Job.Dependencies)
		//line template/job/show.qtpl:114
		qw422016.N().S(` `)
		//line template/job/show.qtpl:115
	} else {
		//line template/job/show.qtpl:115
		qw422016.N().S(` <div class="panel-message muted">No dependencies for this job.</div> `)
		//line template/job/show.qtpl:117
	}
	//line template/job/show.qtpl:117
	qw422016.N().S(` </div> `)
//line template/job/show.qtpl:119
}

//line template/job/show.qtpl:119
func (p *ShowPage) WriteBody(qq422016 qtio422016.Writer) {
	//line template/job/show.qtpl:119
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line template/job/show.qtpl:119
	p.StreamBody(qw422016)
	//line template/job/show.qtpl:119
	qt422016.ReleaseWriter(qw422016)
//line template/job/show.qtpl:119
}

//line template/job/show.qtpl:119
func (p *ShowPage) Body() string {
	//line template/job/show.qtpl:119
	qb422016 := qt422016.AcquireByteBuffer()
	//line template/job/show.qtpl:119
	p.WriteBody(qb422016)
	//line template/job/show.qtpl:119
	qs422016 := string(qb422016.B)
	//line template/job/show.qtpl:119
	qt422016.ReleaseByteBuffer(qb422016)
	//line template/job/show.qtpl:119
	return qs422016
//line template/job/show.qtpl:119
}

//line template/job/show.qtpl:121
func (p *ShowPage) StreamHeader(qw422016 *qt422016.Writer) {
	//line template/job/show.qtpl:121
	qw422016.N().S(` <a href="`)
	//line template/job/show.qtpl:122
	qw422016.E().S(p.Job.Build.UIEndpoint())
	//line template/job/show.qtpl:122
	qw422016.N().S(`" class="back">`)
	//line template/job/show.qtpl:122
	qw422016.N().S(`<!-- Generated by IcoMoon.io -->
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
<path d="M20.016 11.016v1.969h-12.188l5.578 5.625-1.406 1.406-8.016-8.016 8.016-8.016 1.406 1.406-5.578 5.625h12.188z"></path>
</svg>
`)
	//line template/job/show.qtpl:122
	qw422016.N().S(`</a> Build #`)
	//line template/job/show.qtpl:122
	qw422016.E().V(p.Job.BuildID)
	//line template/job/show.qtpl:122
	qw422016.N().S(` / `)
	//line template/job/show.qtpl:122
	qw422016.E().S(p.Job.Stage.Name)
	//line template/job/show.qtpl:122
	qw422016.N().S(` - `)
	//line template/job/show.qtpl:122
	qw422016.E().S(p.Job.Name)
	//line template/job/show.qtpl:122
	qw422016.N().S(` `)
	//line template/job/show.qtpl:122
	template.StreamRenderStatus(qw422016, p.Job.Build.Status)
	//line template/job/show.qtpl:122
	qw422016.N().S(` `)
//line template/job/show.qtpl:123
}

//line template/job/show.qtpl:123
func (p *ShowPage) WriteHeader(qq422016 qtio422016.Writer) {
	//line template/job/show.qtpl:123
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line template/job/show.qtpl:123
	p.StreamHeader(qw422016)
	//line template/job/show.qtpl:123
	qt422016.ReleaseWriter(qw422016)
//line template/job/show.qtpl:123
}

//line template/job/show.qtpl:123
func (p *ShowPage) Header() string {
	//line template/job/show.qtpl:123
	qb422016 := qt422016.AcquireByteBuffer()
	//line template/job/show.qtpl:123
	p.WriteHeader(qb422016)
	//line template/job/show.qtpl:123
	qs422016 := string(qb422016.B)
	//line template/job/show.qtpl:123
	qt422016.ReleaseByteBuffer(qb422016)
	//line template/job/show.qtpl:123
	return qs422016
//line template/job/show.qtpl:123
}

//line template/job/show.qtpl:125
func (p *ShowPage) StreamActions(qw422016 *qt422016.Writer) {
//line template/job/show.qtpl:125
}

//line template/job/show.qtpl:125
func (p *ShowPage) WriteActions(qq422016 qtio422016.Writer) {
	//line template/job/show.qtpl:125
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line template/job/show.qtpl:125
	p.StreamActions(qw422016)
	//line template/job/show.qtpl:125
	qt422016.ReleaseWriter(qw422016)
//line template/job/show.qtpl:125
}

//line template/job/show.qtpl:125
func (p *ShowPage) Actions() string {
	//line template/job/show.qtpl:125
	qb422016 := qt422016.AcquireByteBuffer()
	//line template/job/show.qtpl:125
	p.WriteActions(qb422016)
	//line template/job/show.qtpl:125
	qs422016 := string(qb422016.B)
	//line template/job/show.qtpl:125
	qt422016.ReleaseByteBuffer(qb422016)
	//line template/job/show.qtpl:125
	return qs422016
//line template/job/show.qtpl:125
}

//line template/job/show.qtpl:126
func (p *ShowPage) StreamNavigation(qw422016 *qt422016.Writer) {
//line template/job/show.qtpl:126
}

//line template/job/show.qtpl:126
func (p *ShowPage) WriteNavigation(qq422016 qtio422016.Writer) {
	//line template/job/show.qtpl:126
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line template/job/show.qtpl:126
	p.StreamNavigation(qw422016)
	//line template/job/show.qtpl:126
	qt422016.ReleaseWriter(qw422016)
//line template/job/show.qtpl:126
}

//line template/job/show.qtpl:126
func (p *ShowPage) Navigation() string {
	//line template/job/show.qtpl:126
	qb422016 := qt422016.AcquireByteBuffer()
	//line template/job/show.qtpl:126
	p.WriteNavigation(qb422016)
	//line template/job/show.qtpl:126
	qs422016 := string(qb422016.B)
	//line template/job/show.qtpl:126
	qt422016.ReleaseByteBuffer(qb422016)
	//line template/job/show.qtpl:126
	return qs422016
//line template/job/show.qtpl:126
}
