// This file is automatically generated by qtc from "index.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line template/artifact/index.qtpl:2
package artifact

//line template/artifact/index.qtpl:2
import (
	"github.com/andrewpillar/thrall/model"
	"github.com/andrewpillar/thrall/template"
	"github.com/andrewpillar/thrall/template/build"
)

//line template/artifact/index.qtpl:9
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line template/artifact/index.qtpl:9
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line template/artifact/index.qtpl:10
type IndexPage struct {
	build.ShowPage

	Search    string
	Artifacts []*model.Artifact
}

//line template/artifact/index.qtpl:19
func (p *IndexPage) StreamTitle(qw422016 *qt422016.Writer) {
	//line template/artifact/index.qtpl:19
	qw422016.N().S(` Build #`)
	//line template/artifact/index.qtpl:20
	qw422016.E().V(p.Build.ID)
	//line template/artifact/index.qtpl:20
	qw422016.N().S(` - Artifacts `)
//line template/artifact/index.qtpl:21
}

//line template/artifact/index.qtpl:21
func (p *IndexPage) WriteTitle(qq422016 qtio422016.Writer) {
	//line template/artifact/index.qtpl:21
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line template/artifact/index.qtpl:21
	p.StreamTitle(qw422016)
	//line template/artifact/index.qtpl:21
	qt422016.ReleaseWriter(qw422016)
//line template/artifact/index.qtpl:21
}

//line template/artifact/index.qtpl:21
func (p *IndexPage) Title() string {
	//line template/artifact/index.qtpl:21
	qb422016 := qt422016.AcquireByteBuffer()
	//line template/artifact/index.qtpl:21
	p.WriteTitle(qb422016)
	//line template/artifact/index.qtpl:21
	qs422016 := string(qb422016.B)
	//line template/artifact/index.qtpl:21
	qt422016.ReleaseByteBuffer(qb422016)
	//line template/artifact/index.qtpl:21
	return qs422016
//line template/artifact/index.qtpl:21
}

//line template/artifact/index.qtpl:23
func (p *IndexPage) StreamBody(qw422016 *qt422016.Writer) {
	//line template/artifact/index.qtpl:23
	qw422016.N().S(` <div class="panel">`)
	//line template/artifact/index.qtpl:24
	StreamRenderIndex(qw422016, p.Artifacts, p.URI, p.Search)
	//line template/artifact/index.qtpl:24
	qw422016.N().S(`</div> `)
//line template/artifact/index.qtpl:25
}

//line template/artifact/index.qtpl:25
func (p *IndexPage) WriteBody(qq422016 qtio422016.Writer) {
	//line template/artifact/index.qtpl:25
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line template/artifact/index.qtpl:25
	p.StreamBody(qw422016)
	//line template/artifact/index.qtpl:25
	qt422016.ReleaseWriter(qw422016)
//line template/artifact/index.qtpl:25
}

//line template/artifact/index.qtpl:25
func (p *IndexPage) Body() string {
	//line template/artifact/index.qtpl:25
	qb422016 := qt422016.AcquireByteBuffer()
	//line template/artifact/index.qtpl:25
	p.WriteBody(qb422016)
	//line template/artifact/index.qtpl:25
	qs422016 := string(qb422016.B)
	//line template/artifact/index.qtpl:25
	qt422016.ReleaseByteBuffer(qb422016)
	//line template/artifact/index.qtpl:25
	return qs422016
//line template/artifact/index.qtpl:25
}
